export interface Study {
  id: string;
  title: string;
  artist: string;
  year: string;
  kind: "Furniture" | "Architecture" | "Graphic design";
  representation: "book" | "poster" | "sign" | "sculpture" | "model";
  material: string;
  description: string;
  relation: string;
  image: string;
  model?: string;
  poster?: string;
  source: string;
  sourceLabel: string;
  angle: number;
}

export const studies: Study[] = [
  {
    id: "chair-35",
    title: "Chair no. 35",
    artist: "Paul Schuitema",
    year: "1934",
    kind: "Furniture",
    representation: "model",
    material: "Chrome, upholstery, open space",
    description: "A continuous line becomes a structure. The cantilever holds its weight with an economy of means.",
    relation: "An original spatial study after Schuitema. The construction stays visible, just as Vlak keeps its underlying grid visible.",
    image: "/about/schuitema-chair-35.webp",
    model: "/inspiration/chair.glb",
    poster: "/inspiration/chair-poster.webp",
    source: "https://www.boijmans.nl/en/collection/artworks/112372/35",
    sourceLabel: "Museum Boijmans Van Beuningen",
    angle: -0.5,
  },
  {
    id: "grid-systems",
    title: "Grid systems",
    artist: "Josef Müller-Brockmann",
    year: "1981",
    kind: "Graphic design",
    representation: "book",
    material: "Printed matter, proportion, order",
    description: "A field divided with purpose. Repetition makes room for difference without losing the whole.",
    relation: "The modular grid is a working tool: a shared measure for type, space, and relationships.",
    image: "/about/mueller-brockmann-grid-systems.webp",
    source: "https://niggli.ch/products/rastersysteme-fur-die-visuelle-gestaltung",
    sourceLabel: "Niggli",
    angle: -0.13,
  },
  {
    id: "hfg-ulm",
    title: "HfG Ulm",
    artist: "Max Bill",
    year: "1955",
    kind: "Architecture",
    representation: "model",
    material: "Planes, glass, light",
    description: "Volumes step across a landscape. Long windows and open terraces give a strict system a human rhythm.",
    relation: "An original architectural study after the Ulm campus. Planes, intervals, and repeated bays become a small landscape.",
    image: "/about/bill-hfg-ulm.webp",
    model: "/inspiration/pavilion.glb",
    poster: "/inspiration/pavilion-poster.webp",
    source: "https://hfg-archiv.museumulm.de/en/the-hfg-archive/building/",
    sourceLabel: "HfG Archive",
    angle: -0.55,
  },
  {
    id: "new-alphabet",
    title: "New Alphabet",
    artist: "Wim Crouwel",
    year: "1967",
    kind: "Graphic design",
    representation: "poster",
    material: "Type, constraint, possibility",
    description: "Letters made from a small vocabulary of straight lines. A technical constraint becomes a visual language.",
    relation: "A reminder that a system can be rigorous and still produce an unexpected form.",
    image: "/about/crouwel-new-alphabet.webp",
    source: "https://www.moma.org/collection/works/139322",
    sourceLabel: "The Museum of Modern Art",
    angle: 0.1,
  },
  {
    id: "designing-programmes",
    title: "Designing programmes",
    artist: "Karl Gerstner",
    year: "1968 edition",
    kind: "Graphic design",
    representation: "book",
    material: "Rules, variation, printed matter",
    description: "Design the conditions, then explore what they make possible. The programme holds many answers.",
    relation: "The pictured English edition expands the 1964 book. Vlak shares its interest in repeatable rules that leave room for decisions.",
    image: "/about/gerstner-designing-programmes.webp",
    source: "https://www.helveticarchives.admin.ch/detail.aspx?ID=493677",
    sourceLabel: "Swiss National Library",
    angle: -0.1,
  },
  {
    id: "typographie",
    title: "Typographie",
    artist: "Emil Ruder",
    year: "1967",
    kind: "Graphic design",
    representation: "book",
    material: "Typography, rhythm, white space",
    description: "Type and image share one measured field. Scale and empty space carry the hierarchy.",
    relation: "An approach to typography in which the space around a letter is as deliberate as the letter itself.",
    image: "/about/ruder-typographie.webp",
    source: "https://www.niggli.ch/produkt/typographie/",
    sourceLabel: "Niggli",
    angle: 0.12,
  },
  {
    id: "eisenbeton",
    title: "100 Jahre Eisenbeton",
    artist: "Richard Paul Lohse",
    year: "1950",
    kind: "Graphic design",
    representation: "poster",
    material: "Exhibition poster, photolithograph",
    description: "An exhibition about reinforced concrete becomes a composition of structure, image, and type.",
    relation: "The grid gives different kinds of information a common measure without making them identical.",
    image: "/about/lohse-100-jahre-eisenbeton.webp",
    source: "https://www.moma.org/collection/works/7251",
    sourceLabel: "The Museum of Modern Art",
    angle: -0.1,
  },
  {
    id: "konstruktive-grafik",
    title: "Konstruktive Grafik",
    artist: "Hans Neuburg",
    year: "1958",
    kind: "Graphic design",
    representation: "poster",
    material: "Exhibition poster, geometric composition",
    description: "Orthogonal bands and measured intervals announce an exhibition of constructive graphic design in Zurich.",
    relation: "A few repeated elements can define an entire field. Their alignment carries the structure.",
    image: "/about/neuburg-konstruktive-grafik.webp",
    source: "https://www.emuseum.ch/en/people/42349/hans-neuburg",
    sourceLabel: "Museum für Gestaltung Zürich",
    angle: 0.1,
  },
  {
    id: "fur-das-alter",
    title: "Für das Alter. Per la vecchiaia",
    artist: "Carlo Vivarelli",
    year: "1949",
    kind: "Graphic design",
    representation: "poster",
    material: "Charity poster, photograph and type",
    description: "A closely cropped face and vertical lettering give a public appeal a direct human presence.",
    relation: "Photography and typography have distinct roles while sharing one carefully composed surface.",
    image: "/about/vivarelli-fur-das-alter.webp",
    source: "https://posterhouse.org/blog/collecting-swiss-posters/",
    sourceLabel: "Poster House",
    angle: -0.09,
  },
  {
    id: "micorene",
    title: "Micorène",
    artist: "Thérèse Moll",
    year: "c. 1958",
    kind: "Graphic design",
    representation: "book",
    material: "Geigy prospectus, printed paper",
    description: "Overlapping shapes give a pharmaceutical prospectus a vivid sense of circulation and movement.",
    relation: "Repeated forms change through overlap. The cover brings variation into a limited visual vocabulary.",
    image: "/about/moll-micorene.webp",
    source: "https://eyemagazine.com/feature/article/the-enigma-of-therese-moll",
    sourceLabel: "Eye magazine",
    angle: 0.12,
  },
  {
    id: "form-farbe",
    title: "Form Farbe",
    artist: "Armin Hofmann",
    year: "1951",
    kind: "Graphic design",
    representation: "poster",
    material: "Exhibition poster, linocut",
    description: "Form, lettering, and contrast become the subject of an exhibition poster for Winterthur.",
    relation: "Differences in scale and weight create hierarchy before extra decoration is needed.",
    image: "/about/hofmann-form-farbe.webp",
    source: "https://www.moma.org/collection/works/7718",
    sourceLabel: "The Museum of Modern Art",
    angle: -0.12,
  },
  {
    id: "saffa-zurich",
    title: "Saffa 1958 Zürich",
    artist: "Nelly Rudin",
    year: "1958",
    kind: "Graphic design",
    representation: "book",
    material: "Exhibition catalogue, printed paper",
    description: "A portrait meets a geometric field on the catalogue for the Swiss exhibition of women's work.",
    relation: "The photographic image keeps its presence inside a clear framework of type and space.",
    image: "/about/rudin-saffa-1958.webp",
    source: "https://old.eguide.ch/fr/objekt/saffa/",
    sourceLabel: "Museum für Gestaltung Zürich",
    angle: 0.09,
  },
  {
    id: "gertrud-kurz",
    title: "Gertrud Kurz, 20 francs",
    artist: "Rosmarie Tissi",
    year: "1992",
    kind: "Graphic design",
    representation: "sculpture",
    material: "Commemorative coin, silver",
    description: "Lettering and broken barbed wire mark a Swiss coin commemorating refugee advocate Gertrud Kurz.",
    relation: "An enlarged study of a small commemorative object, with the inscription and its meaning held together.",
    image: "/about/tissi-gertrud-kurz.webp",
    source: "https://www.swissmint.ch/dam/fr/sd-web/xNpQunrGcgCg/1992-getrudkurz-flyer-dfie.pdf",
    sourceLabel: "Swissmint",
    angle: -0.18,
  },
  {
    id: "japanische-plakate",
    title: "Japanische Plakate heute",
    artist: "Shizuko Yoshikawa",
    year: "1979",
    kind: "Graphic design",
    representation: "poster",
    material: "Exhibition poster, screen print",
    description: "A red disc and dark waves frame the announcement of an exhibition of Japanese posters in Zurich.",
    relation: "The pictured poster names the exhibition dates in 1979. A measured typographic field holds a fluid image.",
    image: "/about/yoshikawa-japanische-plakate-heute.webp",
    source: "https://artplatform.go.jp/ja/collections/W1292711",
    sourceLabel: "Art Platform Japan",
    angle: 0.1,
  },
  {
    id: "bruynzeel-kitchen",
    title: "Bruynzeel kitchen",
    artist: "Piet Zwart",
    year: "1938",
    kind: "Furniture",
    representation: "model",
    material: "Cabinetry, work surfaces, standard modules",
    description: "Standard elements form a kitchen around everyday work, with storage and preparation within reach.",
    relation: "An original spatial study after Zwart. Repeated modules let one system adapt to different rooms and routines.",
    image: "/about/zwart-bruynzeel.webp",
    model: "/inspiration/kitchen.glb",
    poster: "/inspiration/kitchen-poster.webp",
    source: "https://www.kunstmuseum.nl/en/collection/bruynzeel-kitchen",
    sourceLabel: "Kunstmuseum Den Haag",
    angle: -0.38,
  },
  {
    id: "sdap-nvv",
    title: "Op naar Den Haag",
    artist: "Fré Cohen",
    year: "1926",
    kind: "Graphic design",
    representation: "poster",
    material: "SDAP / NVV poster, printed paper",
    description: "An invitation to a workers' demonstration gives illustration and lettering a shared direction.",
    relation: "The poster brings a dense public message into a single composition with a clear point of attention.",
    image: "/about/cohen-sdap-nvv.webp",
    source: "https://search.iisg.amsterdam/Record/848116",
    sourceLabel: "International Institute of Social History",
    angle: -0.1,
  },
  {
    id: "vught-memorial",
    title: "Memorial plaque, Station Vught",
    artist: "Otto Treumann",
    year: "1984",
    kind: "Graphic design",
    representation: "sign",
    material: "Memorial inscription, station wall",
    description: "An inscription at Vught station remembers the people deported from this place in 1943 and 1944.",
    relation: "This reference records a public act of remembrance. The inscription remains integral to the work.",
    image: "/about/treumann-vught.webp",
    source: "https://www.4en5mei.nl/oorlogsmonumenten/zoeken/796/vught-joodse-plaquette",
    sourceLabel: "Nationaal Comité 4 en 5 mei",
    angle: -0.14,
  },
  {
    id: "stedelijk-enamel",
    title: "Stedelijk Museum enamel sign",
    artist: "Willem Sandberg",
    year: "1954",
    kind: "Graphic design",
    representation: "sign",
    material: "Enamel sign, metal backing",
    description: "A museum name becomes an object. Bold lettering occupies a durable public surface.",
    relation: "A spatial study of the sign in the reference photograph, preserving its letterforms and proportion.",
    image: "/about/sandberg-stedelijk-email-1954.webp",
    source: "https://commons.wikimedia.org/wiki/File:Stedelijk_085_email_sandberg_1954.jpg",
    sourceLabel: "Reference photograph",
    angle: 0.14,
  },
  {
    id: "letter-op-straat",
    title: "De letter op straat",
    artist: "Jurriaan Schrofer",
    year: "1956",
    kind: "Graphic design",
    representation: "book",
    material: "Photobook, printed paper",
    description: "Street lettering, photographs by Violette Cornelius, and words by Jan Elburg meet in a small book.",
    relation: "Schrofer's layout treats words and photographs as parts of the same reading experience.",
    image: "/about/schrofer-de-letter-op-straat.webp",
    source: "https://www.dbnl.org/tekst/_med003mede01_01/_med003mede01_01_0231.php",
    sourceLabel: "Digitale Bibliotheek voor de Nederlandse Letteren",
    angle: -0.1,
  },
  {
    id: "co-westerik",
    title: "Co Westerik",
    artist: "Total Design / Wim Crouwel and Magda Tsfaty",
    year: "1971",
    kind: "Graphic design",
    representation: "poster",
    material: "Stedelijk exhibition poster, printed paper",
    description: "An image and a compact announcement share a poster for the Stedelijk exhibition of Co Westerik.",
    relation: "A consistent museum identity leaves enough room for the character of an individual artist.",
    image: "/about/total-design-westerik-1971.webp",
    source: "https://vanabbemuseum.nl/en/collection-research/library/publications/co-westerik-2",
    sourceLabel: "Exhibition catalogue, Van Abbemuseum",
    angle: 0.11,
  },
  {
    id: "schiphol-signage",
    title: "Schiphol signage",
    artist: "Benno Wissing / Total Design",
    year: "1967",
    kind: "Graphic design",
    representation: "sign",
    material: "Wayfinding panels, type and arrows",
    description: "Clear words and directional marks guide travellers through the new Schiphol terminal.",
    relation: "Information appears where a decision is needed. Consistent forms make a large environment easier to read.",
    image: "/about/wissing-schiphol-signposting.webp",
    source: "https://www.schiphol.nl/nl/blog/kho-liang-le-nederlands-ontwerp-en-schiphol/",
    sourceLabel: "Amsterdam Airport Schiphol",
    angle: -0.18,
  },
  {
    id: "neue-grafik",
    title: "Neue Grafik",
    artist: "Hans Neuburg",
    year: "July 1963",
    kind: "Graphic design",
    representation: "book",
    material: "Graphic design journal, printed paper",
    description: "A multilingual journal gives the ideas of Swiss graphic design a shared printed forum.",
    relation: "The July 1963 cover brings several languages into one modular composition without losing their hierarchy.",
    image: "/about/neue-grafik.webp",
    source: "https://www.aboutswitzerland.eda.admin.ch/en/swiss-style-forever-the-story-of-a-graphic-design-tradition",
    sourceLabel: "Presence Switzerland",
    angle: 0.1,
  },
];
