import { OrbitBoard } from "../../../app/interfaces/concepts/orbit";
const cue = (id, selector, start, from = {}, extra = {}) => ({
	id,
	selector,
	start,
	from,
	sound: "tick",
	volume: 0.13,
	...extra,
});
const telemetry = (start) => [
	cue("pass-label", ".so-pass-head .so-eyebrow", start, { x: -18 }),
	cue(
		"pass-title",
		".so-pass-head h2",
		start + 0.12,
		{ y: 20 },
		{ sound: "release" },
	),
	cue("pass-window", ".so-window", start + 0.25, {
		y: 16,
	}),
	...Array.from({ length: 3 }, (_, i) =>
		cue(
			`telemetry-${i}`,
			".so-telemetry .rs-item",
			start + 0.34 + i * 0.12,
			{ x: 20 },
			{ index: i },
		),
	),
	cue("cloud-cover", ".so-cloud", start + 0.73, { y: 16 }),
	cue(
		"pass-status",
		'.so-tasking > [class*="rs-badge"]',
		start + 0.9,
		{ scale: 0.85 },
		{ sound: "release" },
	),
];
export default {
	slug: "orbit",
	title: "Satellite operations",
	theme: "dark",
	Component: OrbitBoard,
	props: {},
	rootSelector: ".so",
	width: 1180,
	height: 772,
	duration: 40,
	hero: { selector: ".so-telemetry .rs-item", index: 0, scale: 4 },
	intro: [
		cue(
			"hero-item",
			".so-telemetry .rs-item",
			0.15,
			{ scale: 0.8 },
			{ index: 0, surface: true, sound: "press", volume: 0.24 },
		),
		cue(
			"hero-label",
			".so-telemetry .rs-item-title",
			0.42,
			{ x: -28 },
			{ index: 0 },
		),
		cue(
			"hero-altitude",
			".so-telemetry .rs-item-meta",
			0.72,
			{ y: 28, scale: 0.65 },
			{ index: 0, sound: "release", volume: 0.22 },
		),
		cue(
			"pass-card",
			".so-pass",
			3.5,
			{},
			{ surface: true, sound: null },
		),
		...telemetry(3.62).filter((item) => item.id !== "telemetry-0"),
		cue(
			"header",
			".so-header",
			3.2,
			{},
			{ surface: true, sound: null },
		),
		cue("network-name", ".so-brand", 3.3, { x: -30 }),
		cue(
			"capture-control",
			".so-header > button",
			3.5,
			{ y: -24, scale: 0.8 },
			{ sound: "release" },
		),
		cue(
			"assets-rail",
			'.so-assets',
			3.6,
			{},
			{ surface: true, sound: null },
		),
		cue("assets-label", ".so-panel-head", 3.68, { x: -20 }),
		...Array.from({ length: 4 }, (_, i) => [
			cue(
				`asset-${i}`,
				".so-asset",
				3.8 + i * 0.23,
				{},
				{ index: i, surface: true, sound: null },
			),
			cue(
				`asset-name-${i}`,
				".so-asset > strong",
				3.9 + i * 0.23,
				{ x: -35 },
				{ index: i, sound: "release" },
			),
			cue(
				`asset-region-${i}`,
				".so-asset > span:not(.so-asset-top)",
				4.03 + i * 0.23,
				{ y: 14 },
				{ index: i, sound: null },
			),
		]).flat(),
		cue(
			"map-surface",
			".so-map",
			4.1,
			{},
			{ surface: true, sound: null },
		),
		cue(
			"observation-line-map",
			".so-map-art",
			4.22,
			{ scale: 0.97 },
			{ sound: "bloom", volume: 0.1 },
		),
		cue(
			"reference-grid",
			".so-grid",
			4.55,
			{},
			{ surface: true, sound: null },
		),
		cue(
			"pass-track",
			".so-track",
			4.65,
			{ scale: 0.95 },
			{ sound: "scan", volume: 0.08 },
		),
		cue("sweep", ".so-sweep", 4.85, {}, { surface: true, sound: null }),
		cue(
			"reticle",
			".so-target",
			5.41,
			{ scale: 0.7 },
			{ sound: "ready", volume: 0.12 },
		),
		cue("coordinates", ".so-map-selection > div:first-child", 5.65, { x: -20 }),
		cue("layer-frame", ".so-layers", 5.8, {}, { surface: true, sound: null }),
		...Array.from({ length: 3 }, (_, i) =>
			cue(
				`layer-${i}`,
				".so-layers button",
				5.87 + i * 0.17,
				{ y: 20, scale: 0.85 },
				{ index: i, sound: "release" },
			),
		),
		cue(
			"zoom-frame",
			".so-map-tools .rs-canvas-controls",
			6.25,
			{},
			{ surface: true, sound: null },
		),
		...Array.from({ length: 3 }, (_, i) =>
			cue(
				`zoom-${i}`,
				".so-map-tools .rs-canvas-controls button",
				6.34 + i * 0.13,
				{ y: 20, scale: 0.85 },
				{ index: i, sound: "release" },
			),
		),
	],
	actions: [
		{
			id: "helios",
			time: 9.6,
			kind: "click",
			selector: ".so-asset",
			index: 1,
			sound: "press",
			assert: { selector: ".so-pass", text: "Alpine corridor" },
		},
		{
			id: "moisture",
			time: 13,
			kind: "click",
			selector: ".so-layers button",
			label: "Moisture",
			sound: "toggle",
			assert: { selector: '.so-map[data-layer="moisture"]' },
		},
		{
			id: "zoom",
			time: 16.4,
			kind: "click",
			selector: '.so-map-tools .rs-canvas-controls button[aria-label="Zoom in"]',
			sound: "press",
			assert: { selector: ".so-scale", text: "125%" },
		},
		{
			id: "thermal",
			time: 19.5,
			kind: "click",
			selector: ".so-layers button",
			label: "Thermal",
			sound: "toggle",
			assert: { selector: '.so-map[data-layer="thermal"]' },
		},
		{
			id: "queue-helios",
			time: 23.2,
			kind: "click",
			selector: ".so-header > button",
			label: "Queue capture",
			sound: "success",
			volume: 0.22,
			assert: { selector: '.so-tasking > [class*="rs-badge"]', text: "Capture queued" },
		},
		{
			id: "northwatch",
			time: 27,
			kind: "click",
			selector: ".so-asset",
			index: 2,
			sound: "press",
			assert: { selector: ".so-pass", text: "Baltic coast" },
		},
		{
			id: "queue-northwatch",
			time: 30.3,
			kind: "click",
			selector: ".so-header > button",
			label: "Queue capture",
			sound: "success",
			volume: 0.22,
			assert: { selector: '.so-tasking > [class*="rs-badge"]', text: "Capture queued" },
		},
	],
	rebuilds: [
		{ after: "helios", cues: telemetry(9.65) },
		{ after: "northwatch", cues: telemetry(27.05) },
		...[
			["queue-helios", 23.25],
			["queue-northwatch", 30.35],
		].map(([after, start]) => ({
			after,
			cues: [
				cue(
					"capture-queued",
					'.so-tasking > [class*="rs-badge"]',
					start,
					{ scale: 0.82 },
					{ sound: "release", volume: 0.14 },
				),
			],
		})),
	],
	shots: [
		{ start: 10.25, end: 12.5, selector: ".so-telemetry", scale: 3.2 },
		{ start: 27.8, end: 29.7, selector: ".so-telemetry", scale: 3.2 },
	],
	inspect(root) {
		return {
			asset: root
				.querySelector('.so-asset[aria-pressed="true"] strong')
				?.textContent.trim(),
			layer: root.querySelector(".so-map").dataset.layer,
			coordinates: root.querySelector(".so-map-selection > div:first-child").textContent,
			queued: [...root.querySelectorAll(".so-asset")]
				.filter((el) => el.textContent.includes("Capture queued"))
				.map((el) => el.querySelector("strong").textContent.trim()),
		};
	},
};
