import { ConceptBoard } from "../../../app/interfaces/concepts/board";
const cue = (id, selector, start, from = {}, extra = {}) => ({
	id,
	selector,
	start,
	from,
	sound: "tick",
	volume: 0.13,
	...extra,
});
const telemetry = (start) => [
	cue("pass-label", ".cx-orbit-inspector .rs-card-label", start, { x: -18 }),
	cue(
		"pass-title",
		".cx-orbit-inspector .rs-card-title",
		start + 0.12,
		{ y: 20 },
		{ sound: "release" },
	),
	cue("pass-window", ".cx-orbit-inspector .rs-card-body", start + 0.25, {
		y: 16,
	}),
	...Array.from({ length: 3 }, (_, i) =>
		cue(
			`telemetry-${i}`,
			".cx-orbit-telemetry .rs-item",
			start + 0.34 + i * 0.12,
			{ x: 20 },
			{ index: i },
		),
	),
	cue("cloud-cover", ".cx-orbit-progress", start + 0.73, { y: 16 }),
	cue(
		"pass-status",
		".cx-status",
		start + 0.9,
		{ scale: 0.85 },
		{ sound: "release" },
	),
];
export default {
	slug: "orbit",
	title: "Satellite operations",
	theme: "dark",
	Component: ConceptBoard,
	props: { kind: "orbit" },
	rootSelector: ".cx-orbit",
	width: 1180,
	height: 772,
	duration: 40,
	hero: { selector: ".cx-orbit-telemetry .rs-item", index: 0, scale: 4 },
	intro: [
		cue(
			"hero-item",
			".cx-orbit-telemetry .rs-item",
			0.15,
			{ scale: 0.8 },
			{ index: 0, surface: true, sound: "press", volume: 0.24 },
		),
		cue(
			"hero-label",
			".cx-orbit-telemetry .rs-item-title",
			0.42,
			{ x: -28 },
			{ index: 0 },
		),
		cue(
			"hero-altitude",
			".cx-orbit-telemetry .rs-item-meta",
			0.72,
			{ y: 28, scale: 0.65 },
			{ index: 0, sound: "release", volume: 0.22 },
		),
		cue(
			"pass-card",
			".cx-orbit-inspector",
			3.5,
			{},
			{ surface: true, sound: null },
		),
		...telemetry(3.62).filter((item) => item.id !== "telemetry-0"),
		cue(
			"header",
			".cx-orbit > header",
			3.2,
			{},
			{ surface: true, sound: null },
		),
		cue("network-name", ".cx-orbit > header > span", 3.3, { x: -30 }),
		cue(
			"capture-control",
			".cx-orbit > header > button",
			3.5,
			{ y: -24, scale: 0.8 },
			{ sound: "release" },
		),
		cue(
			"assets-rail",
			'.cx-orbit > aside[aria-label="Observation assets"]',
			3.6,
			{},
			{ surface: true, sound: null },
		),
		cue("assets-label", ".cx-orbit > aside .cx-label", 3.68, { x: -20 }),
		...Array.from({ length: 4 }, (_, i) => [
			cue(
				`asset-${i}`,
				".cx-orbit-asset",
				3.8 + i * 0.23,
				{},
				{ index: i, surface: true, sound: null },
			),
			cue(
				`asset-name-${i}`,
				".cx-orbit-asset > span",
				3.9 + i * 0.23,
				{ x: -35 },
				{ index: i, sound: "release" },
			),
			cue(
				`asset-region-${i}`,
				".cx-orbit-asset > small",
				4.03 + i * 0.23,
				{ y: 14 },
				{ index: i, sound: null },
			),
		]).flat(),
		cue(
			"map-surface",
			".cx-orbit .cx-workspace",
			4.1,
			{},
			{ surface: true, sound: null },
		),
		cue(
			"observation-image",
			".cx-orbit-visual > img",
			4.22,
			{ scale: 0.97 },
			{ sound: "bloom", volume: 0.1 },
		),
		cue(
			"reference-grid",
			".cx-orbit-grid",
			4.55,
			{},
			{ surface: true, sound: null },
		),
		cue(
			"pass-track",
			".cx-pass-track",
			4.65,
			{ scale: 0.95 },
			{ sound: "scan", volume: 0.08 },
		),
		cue("sweep", ".cx-sweep", 4.85, {}, { surface: true, sound: null }),
		cue(
			"target-a",
			".cx-target-a",
			5.04,
			{ scale: 0.35 },
			{ sound: "release" },
		),
		cue(
			"target-b",
			".cx-target-b",
			5.23,
			{ scale: 0.35 },
			{ sound: "release" },
		),
		cue(
			"reticle",
			".cx-reticle",
			5.41,
			{ scale: 0.7 },
			{ sound: "ready", volume: 0.12 },
		),
		cue("coordinates", ".cx-coords", 5.65, { x: -20 }),
		cue("layer-frame", ".cx-layers", 5.8, {}, { surface: true, sound: null }),
		...Array.from({ length: 3 }, (_, i) =>
			cue(
				`layer-${i}`,
				".cx-layers button",
				5.87 + i * 0.17,
				{ y: 20, scale: 0.85 },
				{ index: i, sound: "release" },
			),
		),
		cue(
			"zoom-frame",
			".cx-orbit-controls",
			6.25,
			{},
			{ surface: true, sound: null },
		),
		...Array.from({ length: 3 }, (_, i) =>
			cue(
				`zoom-${i}`,
				".cx-orbit-controls button",
				6.34 + i * 0.13,
				{ y: 20, scale: 0.85 },
				{ index: i, sound: "release" },
			),
		),
	],
	actions: [
		{
			id: "helios",
			time: 9.6,
			kind: "click",
			selector: ".cx-orbit-asset",
			index: 1,
			sound: "press",
			assert: { selector: ".cx-orbit-inspector", text: "Alpine corridor" },
		},
		{
			id: "moisture",
			time: 13,
			kind: "click",
			selector: ".cx-layers button",
			label: "Moisture",
			sound: "toggle",
			assert: { selector: '.cx-workspace[data-layer="moisture"]' },
		},
		{
			id: "zoom",
			time: 16.4,
			kind: "click",
			selector: '.cx-orbit-controls button[aria-label="Zoom in"]',
			sound: "press",
			assert: { selector: ".cx-coords", text: "8 m / px" },
		},
		{
			id: "thermal",
			time: 19.5,
			kind: "click",
			selector: ".cx-layers button",
			label: "Thermal",
			sound: "toggle",
			assert: { selector: '.cx-workspace[data-layer="thermal"]' },
		},
		{
			id: "queue-helios",
			time: 23.2,
			kind: "click",
			selector: ".cx-orbit > header button",
			label: "Queue capture",
			sound: "success",
			volume: 0.22,
			assert: { selector: ".cx-status", text: "Capture queued" },
		},
		{
			id: "northwatch",
			time: 27,
			kind: "click",
			selector: ".cx-orbit-asset",
			index: 2,
			sound: "press",
			assert: { selector: ".cx-orbit-inspector", text: "Baltic coast" },
		},
		{
			id: "queue-northwatch",
			time: 30.3,
			kind: "click",
			selector: ".cx-orbit > header button",
			label: "Queue capture",
			sound: "success",
			volume: 0.22,
			assert: { selector: ".cx-status", text: "Capture queued" },
		},
	],
	rebuilds: [
		{ after: "helios", cues: telemetry(9.65) },
		{ after: "northwatch", cues: telemetry(27.05) },
		...[
			["queue-helios", 23.25],
			["queue-northwatch", 30.35],
		].map(([after, start]) => ({
			after,
			cues: [
				cue(
					"capture-queued",
					".cx-status",
					start,
					{ scale: 0.82 },
					{ sound: "release", volume: 0.14 },
				),
			],
		})),
	],
	shots: [
		{ start: 10.25, end: 12.5, selector: ".cx-orbit-telemetry", scale: 3.2 },
		{ start: 27.8, end: 29.7, selector: ".cx-orbit-telemetry", scale: 3.2 },
	],
	inspect(root) {
		return {
			asset: root
				.querySelector('.cx-orbit-asset[aria-pressed="true"] span')
				?.textContent.trim(),
			layer: root.querySelector(".cx-workspace").dataset.layer,
			coordinates: root.querySelector(".cx-coords").textContent,
			queued: [...root.querySelectorAll(".cx-orbit-asset")]
				.filter((el) => el.textContent.includes("Capture queued"))
				.map((el) => el.querySelector("span").textContent.trim()),
		};
	},
};
