import { scienceStudies, scienceMobilePatterns } from "./science-studies";
import { engineeringStudies, engineeringMobilePatterns } from "./engineering-studies";
import { careStudies, careMobilePatterns } from "./care-studies";
import { musicStudies, musicMobilePatterns } from "./music-studies";

const originalInterfaces = [
  {
    slug: "line",
    title: "AI chat",
    voice: "Keep questions, responses, and working notes in context.",
    law: "A research notebook with separate conversations, local writing templates, and a response inspector.",
    story: "A focused notebook for working through product and research questions. Search or create conversations, choose a response format, and inspect the question behind each response. Save useful replies in the conversation or export the actual history as Markdown. Each conversation keeps its own messages and unfinished draft.",
    what: "AI chat",
    type: "Chat list, conversation, reply inspector",
    module: "Grid system",
    ink: "Neutral surfaces, hairline dividers, and a quiet active state.",
    use: "Choose a conversation → send a question → inspect, save, or export the response",
    field: "Conversation rail, bounded reading column, composer at the lower edge.",
    note: "Messages stay in this tab. Replies are authored samples or local writing templates; no model or research service is connected. Export downloads the actual conversation as a Markdown file.",
    components: ["Button", "Card", "Description list", "Icon", "Input", "Select", "Textarea"],
    modifications: [
      "Input filters the conversation list. Select chooses a response format, and Textarea pairs with Button in the pinned composer. Control or Command plus Enter sends the current draft.",
      "Card and Description list organize the response, its starting question, and its source. Buttons save replies and export the current history as Markdown.",
      "Flush conversation rows use full-surface selection. Narrow containers move from list to conversation to response details, preserving independent drafts and restoring keyboard focus.",
    ],
  },
  {
    slug: "press",
    title: "Dashboard",
    voice: "Connect the production overview to the record that needs attention.",
    law: "A print production desk with dated work, supplied output totals, and local review notes.",
    story: "A production workspace for reviewing print jobs and invoice records. Week and month views filter work by supplied due dates and update the recorded-output chart. Search by job or client, narrow the stage, then open a brief or invoice to record a local review. Linked invoices lead back to their jobs without changing payment status.",
    what: "Dashboard",
    type: "Production overview, job register, invoice and review detail",
    module: "Grid system",
    ink: "Monochrome chart bars, paper and ink panels, and flush record rows.",
    use: "Choose a period → find a job or invoice → record a local review",
    field: "Navigation rail, output summary and work register, with a focused record inspector.",
    note: "All production figures, due dates, briefs, and invoice amounts are supplied sample records. Review notes and reviewed states stay in this tab; they do not start production, send payments, or mark an invoice paid.",
    components: ["Badge", "Button", "Card", "Icon", "Input", "Select", "Textarea", "Toggle group"],
    modifications: [
      "Toggle group switches Week and Month, filtering the job and invoice registers by due date. Card groups the output summary, while the custom bar chart includes exact supplied values in its accessible description.",
      "Input searches jobs and clients, Select filters job stages, and Badge preserves the supplied record status. Buttons open briefs, invoice line items, and linked jobs.",
      "Textarea records a local review note, and Button marks or undoes the review. Focused mobile detail screens replace the register while keeping Back and the review action reachable.",
    ],
  },
  {
    slug: "wall",
    title: "Social feed",
    voice: "Give work in progress room to be seen.",
    law: "An image-led studio feed with comments and contributor profiles.",
    story:
      "A studio feed for reviewing work in progress. Large images sit above short updates, with authors and discussion counts close to each post. Comments and contributor profiles open in the same side pane, keeping the feed in view.",
    what: "Social feed",
    type: "Feed, comments, profile",
    module: "Grid system",
    ink: "Photographs carry the field; neutral controls and hairlines stay secondary.",
    use: "Browse posts → read comments → view a contributor",
    field: "A chronological studio journal beside contributors and a focused discussion pane.",
    note: "Publish a text update, filter contributors, like posts, add comments or follow a profile locally. The people, posts, and comments are fictional sample content.",
    components: ["Avatar", "Button", "Card", "Icon", "Input", "Select", "Textarea", "Toggle group"],
    modifications: [
      "Card groups each post, with Avatar for authors and Button for likes and discussion. Full-width photographs meet the post boundaries.",
      "Select and Toggle group filter the feed. Input composes comments and Textarea writes a new post, each with a fixed-height send action.",
      "A shared context pane hosts comments, profiles and publishing. Mobile navigation gives each destination a focused screen with Back and restored focus.",
    ],
  },
  {
    slug: "night",
    title: "Fleet management",
    voice: "Keep the selected vehicle, route, and dispatch note together.",
    law: "A fleet desk with a Mapbox map of Dogpatch, supplied vehicle records, and local dispatch notes.",
    story: "A dispatch workspace centered on San Francisco’s Dogpatch neighborhood. Search or filter the sample fleet to update both the list and map markers, then inspect one vehicle’s route, recorded arrival, and battery. Pan and zoom the map or open a trip to save a dispatch note. Missing arrival times remain explicitly unavailable.",
    what: "Fleet management",
    type: "Filtered fleet, geographic map, trip record and dispatch note",
    module: "Grid system",
    ink: "Monochrome map geometry, full-surface vehicle selection, and flush working panels.",
    use: "Filter vehicles → inspect a route → save a dispatch note",
    field: "Vehicle rail, a Mapbox map of Dogpatch, and a focused trip record.",
    note: "Vehicle positions, battery levels and times are sample records. Mapbox Directions supplies street routes between the sample stops. Drafts and saved dispatch notes are independent for each vehicle. No live feed is connected and no vehicle command is sent.",
    components: ["Badge", "Button", "Canvas controls", "Card", "Icon", "Input", "Progress", "Select", "Textarea"],
    modifications: [
      "Input and Select filter vehicles by name, driver, location, and supplied status. The same filter controls visible map markers and keeps the selected record consistent.",
      "Mapbox GL JS supplies geographic context in a monochrome map. Vlak vehicle icons and accessible buttons mark the sample fleet; Canvas controls keeps zoom and reset synchronized with the map camera.",
      "Textarea keeps a separate dispatch draft for each vehicle. Buttons save local notes and move between the focused Vehicles, Map, and Trip screens with Back focus restoration.",
    ],
  },
  {
    slug: "evening",
    title: "Food ordering",
    voice: "Find a kitchen and build an order.",
    law: "A food marketplace with search, filters, menus, and an order bag.",
    story:
      "A food-ordering interface that moves from kitchen discovery to a filled bag. Search and filters narrow the restaurants, large photographs lead into their menus, and dish details stay close to the order summary.",
    what: "Food ordering",
    type: "Market, store, bag",
    module: "Grid system",
    ink: "Large food photography, restrained controls, and clear selected states.",
    use: "Filter kitchens → choose a dish → review the bag",
    field: "Search and filters above an image-led market; details open alongside it.",
    note: "Filter the kitchens, open a menu, and add dishes to the bag. Orders stay in the demo; checkout creates a local receipt and does not place a real order or take payment.",
    components: ["Button", "Card", "Checkbox", "Icon", "Input", "Number field", "Select", "Toggle group"],
    modifications: [
      "Input searches kitchens, Select and Toggle group narrow the menu, and Card organizes the result and order regions.",
      "Number field edits item quantities. Buttons add and remove dishes while Checkbox acknowledges the local demonstration before checkout.",
      "Kitchen discovery, menu, item, bag and receipt share one responsive flow. Flush dividers separate sections while photography keeps its useful visual role.",
    ],
  },
  {
    slug: "room",
    title: "Team chat",
    voice: "Keep shared decisions close to their conversations.",
    law: "A studio workspace with editable channels, local messages, and threaded follow-up.",
    story: "A team chat for coordinating studio work. Search, create, or edit a channel, send a message, and keep its follow-up in a dedicated thread. Acknowledgements and pinned messages update locally, while reply counts follow the actual thread history. The channel overview gives way to a focused discussion when a message needs attention.",
    what: "Team chat",
    type: "Channels, messages, thread",
    module: "Grid system",
    ink: "Paper and ink surfaces, compact initial avatars, and full-surface channel selection.",
    use: "Choose a channel → send a message → reply, acknowledge, or pin it",
    field: "Channel and team rail, a readable conversation, and a focused thread or channel overview.",
    note: "Channel creation, purpose edits, messages, acknowledgements, pins, and replies stay in this tab. Duplicate channel names are rejected. No messages or notifications are sent to other people.",
    components: ["Avatar", "Button", "Card", "Icon", "Input", "Textarea"],
    modifications: [
      "Avatar identifies contributors in messages and threads. Input and Textarea edit channel details and supply separate message and reply composers.",
      "Buttons create channels, acknowledge and pin messages, and open threads. Card groups the channel editor’s context; the conversation remains selectable text with separate actions.",
      "A wide workspace keeps the channel beside its thread. Narrow containers use focused channel, conversation, thread, and editor screens with pinned actions and restored focus.",
    ],
  },
  {
    slug: "agents",
    title: "Agent management",
    voice: "Coordinate agents, review their work, and decide what runs next.",
    law: "An agent workspace with a task queue, run activity, and approval controls.",
    story: "A workspace for delegating work to a small team of agents. The queue keeps assignments and status in view, while the detail pane follows one task from its brief to its output. Approval requests sit beside the work they affect. On a phone, the queue and task become separate views.",
    what: "Agent management",
    type: "Task queue, agent activity, review and approval",
    module: "Grid system",
    ink: "Monochrome status marks, tonal selection, and flush working panels.",
    use: "Choose a task → inspect the work → approve or pause the agent",
    field: "A compact queue beside a focused task detail and activity log.",
    note: "Queue a task, pause or resume a run, and respond to a review request. This is a local simulation with sample agents; it does not run models, edit files, or connect to an agent service. Changes reset when the page reloads.",
    components: ["Button", "Card", "Icon", "Input", "Progress", "Textarea", "Toggle group"],
    modifications: [
      "Cards become flush summary regions above a custom task queue. Full-row tonal selection, status text, and Icons keep states legible without color.",
      "Buttons handle task actions and mobile navigation. Input and Textarea compose the new-task form; Vlak's compact control radius stays separate from the square workspace frame.",
      "Toggle groups switch queue filters and detail views, while Progress shows task completion. Container queries turn the split workspace into a list-to-detail flow when the panel becomes narrow.",
    ],
  },
  {
    slug: "graphics",
    title: "Wallpaper generator",
    voice: "Make a geometric wallpaper and export it at 6K.",
    law: "A working wallpaper tool with canvas formats, variations, and PNG export.",
    story: "A wallpaper studio with a direction rail, one large selected canvas and a three-result variation strip. Change the seed, format or variation, generate a new set, then export the selected artwork as a full-resolution PNG.",
    what: "Wallpaper generator",
    type: "Prompt, composition controls, 6K export",
    module: "Grid system",
    ink: "Working chrome stays neutral so color belongs to the generated work.",
    use: "Set direction → generate three fields → export a 6K PNG",
    field: "Control rail beside a large, image-led results canvas.",
    note: "Exports are real PNG files with a 6,144-pixel long edge. A geometric generator runs in the browser, using the direction text and variation setting to seed each composition.",
    components: ["Button", "Icon", "Native select", "Slider", "Textarea"],
    modifications: [
      "Textarea supplies the seed, Native select chooses the canvas format, and Slider changes variation. All controls retain Vlak's standard geometry.",
      "Buttons generate, select and export compositions. The selected canvas fills the work area while a compact variation strip keeps all three alternatives available.",
      "Custom SVG previews and canvas PNG export share the same seeded geometry. Mobile separates Preview and Direction with pinned navigation and export.",
    ],
  },
  {
    slug: "render",
    title: "3D workspace",
    voice: "Inspect an industrial design object in a 3D workspace.",
    law: "A modeling workspace with a live Braun T3 radio, model tree and focused property inspector.",
    story: "A modeling workspace built around the Braun T3 pocket radio. Orbit the model, inspect its mesh and compare line treatments. A Vlak context header, flush viewport tools and a readable property inspector keep the model and its settings connected.",
    what: "3D workspace",
    type: "Viewport, toolbars, object properties",
    module: "Grid system",
    ink: "Paper and ink controls, hairline panel boundaries and matching model contours.",
    use: "Rotate the model → show the mesh → adjust the linework",
    field: "A dominant live viewport beside a structured model inspector and a shared status footer.",
    note: "The licensed 32,027-triangle radio model renders locally with Three.js and WebGL. Background-colored faces and fine contours match the EV study. Line intensity can be adjusted in the viewer. Geometry editing and production rendering are outside this study's scope.",
    components: ["Button", "Card", "Icon", "Tree view", "Property grid", "Description list"],
    modifications: [
      "Vlak Buttons form a readable viewport toolbar. Centered Icons and full-surface selected states identify auto-rotation, mesh view and camera reset.",
      "Tree view selects the inspector section. Property grid edits line intensity, mesh and rotation settings; Description list aligns the mesh metadata.",
      "Three.js renders the locally hosted radio model. Vlak controls change its camera, wireframe and materials; loading and retry remain part of the workspace, and model attribution sits below Components used.",
    ],
  },
  {
    slug: "drive",
    title: "EV controls",
    voice: "Bring range, climate, and media into one display.",
    law: "A vehicle workspace with a live 3D model, an animated journey and an exploded battery view.",
    story: "A detailed vehicle model connects three views of the same electric concept. Vehicle opens in side profile; Journey rotates smoothly into a third-person chase camera with moving wheels and a looping 3D streetscape; Energy reveals the battery modules and their current load. Cabin, charging and media controls share the same flush panels and typography as the other Vlak workspaces.",
    what: "EV controls",
    type: "Vehicle status, media, climate, connectivity",
    module: "Grid system",
    ink: "Paper and ink surfaces, monochrome vehicle linework and clear status records.",
    use: "Choose a vehicle view → adjust the cabin → control media",
    field: "Vehicle and journey views beside focused climate, charging and media panels.",
    note: "Three.js renders the licensed Evoque geometry with paper-colored surfaces and a simplified selection of source contours. The electric system, battery assembly, vehicle settings and journey are fictional simulations, independent of the source vehicle's engineering. The player shows Fortress Down by Loathe; playback controls are simulated and do not stream audio.",
    components: ["Button", "Card", "Icon", "Progress", "Toggle group", "Metric", "Number field", "Playback controls", "Media scrubber", "Connection status"],
    modifications: [
      "Flush working panels separate the vehicle visualization from local controls. Metrics present range and battery records; a focused inspector keeps cabin, charging and media actions readable.",
      "Toggle group switches Vehicle, Journey, and Energy views. Buttons and Icons handle local vehicle settings, climate, and media, retaining the small control radius and centered icon geometry.",
      "Playback controls and Media scrubber provide transport and seeking. Number field edits cabin temperature with reachable increase and decrease actions. Connection status reports the local phone state.",
      "The local Three.js scene uses fine outlines with background-colored faces. The Journey view follows the car through a looping monochrome streetscape with real perspective; Energy reveals the battery assembly. Range and battery, cabin and media blocks open sliding detail panes. Headlights switch the site to night mode and illuminate the road. Charge and cabin settings update the displayed load.",
    ],
  },
  {
    slug: "orbit",
    title: "Satellite operations",
    voice: "Put coverage, pass timing, and telemetry in context.",
    law: "An observation workspace with an asset list, map tools and a structured pass inspector.",
    story: "A fictional European satellite operations workspace. A monochrome vector map shares a flush working frame with asset selection and pass details. Selecting an asset updates its telemetry, while local capture status, layer controls and map tools keep the scene and its records connected.",
    what: "Satellite operations",
    type: "Earth observation, passes, telemetry",
    module: "Grid system",
    ink: "Paper and ink coastlines, precise grid lines, a pass corridor and a restrained scanning reticle.",
    use: "Select an asset → compare display layers → queue a capture",
    field: "Asset rail, a technical vector map, telemetry and pass detail.",
    note: "Asset selection, display layers, and the capture queue work locally. Satellites, telemetry, and observation layers are illustrative examples.",
    components: ["Badge", "Button", "Card", "Icon", "Item", "Progress", "Toggle group", "Canvas controls"],
    modifications: [
      "Button supplies the capture action and asset selection. Selected assets use a full-surface fill, never a leading bar or inset edge stripe.",
      "Card, Card label, Card title, Item, Progress, and Badge compose the pass inspector. Compact Item rows align telemetry labels and values; Progress shows cloud cover; Badge reports queue state.",
      "Toggle group switches base, moisture and thermal layers, each drawn in grayscale. Canvas controls zooms or resets the map; the scanning reticle, pass corridor and target markers pause together and respect reduced motion.",
    ],
  },
  {
    slug: "frontier",
    title: "Website",
    voice: "Introduce a model with a clear next step.",
    law: "A company landing page with a model proposition, capability cards, and research overview.",
    story: "A landing page for Athena Labs, a fictional model company. A slowly rotating Athena bust, drawn entirely in fine contours, sits beside the opening statement. The primary action opens a model overview, while a secondary action reveals the research summary in the same card layout.",
    what: "Website",
    type: "Company landing page, model and research summaries",
    module: "Grid system",
    ink: "Editorial white space, monochrome type and a sculptural field of fine contour lines.",
    use: "Read the proposition → explore the model → open the system card",
    field: "Compact navigation, a large opening statement, three summary cards.",
    note: "Switch between Models, Research, and Company to explore the page. Athena Labs and its model capabilities are fictional.",
    components: ["Button", "Card"],
    modifications: [
      "Card, Card label, Card title, and Card body form the model summary. Their outer sizing is adapted to equal columns with shared dividers.",
      "Buttons use the page's local paper-and-ink colors. A custom text-style button opens the research summary beside the primary model action.",
      "A local Three.js renderer draws the licensed Athena bust as fine contours and silhouettes. Slow rotation pauses on request and respects reduced motion; the same model supplies the static fallback. Creator attribution sits below Components used.",
    ],
  },
  {
    slug: "platforms",
    title: "Transit app",
    voice: "Find a route and keep the journey close.",
    law: "A local transit planner with sample routes, saved travel days, and a responsive workspace.",
    story: "One working travel planner in a shared Vlak language. Choose stations, a date, and a departure time, compare illustrative route options, then inspect the stops and save a journey. Your travel day shows the actual saved records for its selected date. Desktop navigation becomes focused planner, journey, travel day, and profile screens on narrow layouts.",
    what: "Transit app",
    type: "Route planner, journey detail, saved itinerary and traveler profile",
    module: "Grid system",
    ink: "Paper and ink timetables, flush route rows, and clear travel navigation.",
    use: "Choose stations and time → inspect a sample route → save it to your travel day",
    field: "Travel navigation beside a route planner, with focused journey and profile screens.",
    note: "Times, durations, connections, and platforms are illustrative sample data. The planner has no live timetable, booking, or ticketing connection. Your name, preferences, and saved journeys stay in this tab.",
    components: ["Avatar", "Button", "Card", "Description list", "Icon", "Input", "Select", "Switch"],
    modifications: [
      "Select chooses the departure and destination stations, and native date and time inputs define the search. Buttons swap stations, find sample routes, and save the selected journey.",
      "Description list and a custom stop diagram keep exact times, endpoints, changes, and next-day arrivals together. Today filters actual saved journeys by date; Input and Switch edit the local profile and direct-route preference.",
      "Desktop navigation keeps the planner, itinerary, and profile close. Narrow layouts use dedicated screens with pinned navigation, a reachable save action, and focus restoration when returning from journey details.",
    ],
  },
  {
    slug: "android",
    title: "Android",
    voice: "Explore an Android phone through Vlak.",
    law: "An interactive Android study with everyday apps, Material navigation and system controls.",
    story: "A focused Android workspace with a Home screen, All Apps drawer and sixteen local apps. Material app bars, floating actions, grouped settings and gesture navigation preserve the platform structure. Open an app, edit its records and use Quick Settings without leaving the phone.",
    what: "Android",
    type: "Home screen, core apps, system menus and settings",
    module: "Grid system",
    ink: "Paper and ink surfaces over Material geometry, with Inter typography and Vlak icons.",
    use: "Open an app → create or edit → return with Back, Home or Recents",
    field: "One Android phone workspace, with independently scrolling app content and reachable system controls.",
    note: "This browser study keeps app data in the current tab. Calls, email, messages, camera captures, weather and device switches are local demonstrations. It does not operate a phone or connect to account services.",
    components: ["Button", "Icon", "Input", "Number field", "Progress", "Select", "Textarea", "Toggle group"],
    modifications: [
      "An All Apps drawer, Home gesture, app bars, floating actions and a Quick Settings shade retain Android navigation conventions. Explicit Back and Recents controls remain available below the device.",
      "Platform-specific native checkbox and range inputs reproduce Material switch and slider geometry. The platform hierarchy uses Vlak’s Inter typography and monochrome palette.",
      "The Android route renders one device. Change its hardware profile or rotate its display while preserving the mounted app, records and settings.",
      "Core apps provide local editing and useful actions. The music player synthesizes browser audio, while the other simulated services report their local scope.",
    ],
  },
  {
    slug: "ios",
    title: "iOS",
    voice: "Explore an iPhone through Vlak.",
    law: "An interactive iOS study with everyday apps, familiar navigation and system controls.",
    story: "A focused iPhone workspace with a Home screen, App Library and sixteen local apps. Contextual back navigation, grouped settings and separate Control and Notification Centers preserve the platform structure. Open an app, edit its records and return Home through the indicator.",
    what: "iOS",
    type: "Home screen, core apps, system menus and settings",
    module: "Grid system",
    ink: "Paper and ink surfaces over iOS geometry, with Inter typography and Vlak icons.",
    use: "Open an app → create or edit → return Home or explore system controls",
    field: "One iPhone workspace, with independently scrolling app content and reachable system controls.",
    note: "This browser study keeps app data in the current tab. Calls, email, messages, camera captures, weather and device switches are local demonstrations. It does not operate a phone or connect to account services.",
    components: ["Button", "Icon", "Input", "Number field", "Progress", "Select", "Textarea", "Toggle group"],
    modifications: [
      "A Home indicator, App Library, contextual back navigation and separate Control and Notification Centers retain iPhone navigation conventions.",
      "Platform-specific native checkbox and range inputs reproduce iOS switch and slider geometry. The platform hierarchy uses Vlak’s Inter typography and monochrome palette.",
      "The iOS route renders one device. Change its hardware profile, open or fold a supported display, or rotate it while preserving the mounted app, records and settings.",
      "Core apps provide local editing and useful actions. The music player synthesizes browser audio, while the other simulated services report their local scope.",
    ],
  },
  {
    slug: "documentation",
    title: "Documentation",
    voice: "Give the reader a clear path through the material.",
    law: "An editorial documentation index and reader with contents navigation and reading preferences.",
    story: "A documentation reader adapted from the essays design at renatovaldes.com. An open index pairs document summaries with quiet metadata. Articles use a 592px reading measure and a compact heading outline that reveals readable labels on approach. Inter carries every heading, paragraph and control. Reader settings adjust appearance and text size.",
    what: "Documentation",
    type: "Document index, article, contents and reader settings",
    module: "Grid system",
    ink: "Paper, ink, a restrained editorial layout and Inter throughout.",
    use: "Browse the index → read a document → navigate its contents",
    field: "A 184px navigation rail beside an editorial index or bounded reading column.",
    note: "Documents are original sample copy. Navigation and reader preferences work within this study; no publishing service or subscription is connected.",
    components: ["Button", "Field", "Icon", "Popover", "Toggle group"],
    modifications: [
      "Vlak Button and Icon provide document navigation, contents actions and reader controls. The 204px module, metadata track and article measure follow the reference site's editorial layout.",
      "Popover, Field and the shared settings mark compose reader preferences. Toggle group selects appearance; text-size actions resize the reading content without changing the surrounding site.",
      "The heading outline tracks the current section, reveals labels on hover or keyboard focus and can stay open while reading. Document navigation preserves the index position, with a responsive disclosure replacing the desktop rail.",
    ],
  },
  {
    slug: "video-player",
    title: "Video player",
    voice: "Give music videos a quiet place to play.",
    law: "A screening room for three selected music videos with a focused playlist and playback controls.",
    story: "A quiet space for watching, with the playlist close at hand and room for the picture. Playback controls stay within reach as you move between films.",
    what: "Video player",
    type: "Music video playlist, viewing room and playback preferences",
    module: "Grid system",
    ink: "A full-width picture, monochrome thumbnails, paper and ink controls, and flush playlist rows.",
    use: "Choose a music video → watch → move through the playlist",
    field: "A focused viewing room beside three selected official music videos.",
    note: "Official videos stream through YouTube and Vimeo embedded players. Availability, captions and playback options depend on the publisher, region and browser. Each video includes a direct publisher link if embedded playback is unavailable.",
    components: ["Button", "Icon", "Media scrubber", "Native select", "Playback controls", "Slider"],
    modifications: [
      "Playback controls, Media scrubber and Slider operate the official YouTube and Vimeo player APIs. Position, duration, volume and buffered ranges follow the real player.",
      "The playlist keeps the selected film, artist and official publisher together. Previous and next actions move between the three videos without introducing a separate library workflow.",
      "Native select exposes the current video’s available playback speeds. The embedded players retain native captions, quality and full-screen controls; direct links remain available if embedding is restricted.",
    ],
  },
  {
    slug: "music-player",
    title: "Music player",
    voice: "Keep the music, artwork and listening queue together.",
    law: "A personal music library with a selected playlist, artwork and working playback controls.",
    story: "A focused player built around a hand-picked 23-track playlist. Browse the library, select a track, inspect its artwork and manage the queue. Official previews are available as individual listening samples with direct store links. Attach your own audio files to use full local playback and queue controls.",
    what: "Music player",
    type: "Music library, now playing and listening queue",
    module: "Grid system",
    ink: "Album artwork, paper and ink controls, and flush library and queue rows.",
    use: "Choose a track → listen to its preview or local audio → arrange the queue",
    field: "Library and queue rails around a focused artwork and transport view.",
    note: "Official previews stream directly from their provider and remain individually initiated promotional samples. Full tracks open through official store links. Attached audio stays in the browser and is not uploaded.",
    components: ["Button", "Icon", "Input", "Media scrubber", "Playback controls", "Slider", "Toggle group"],
    modifications: [
      "Input searches the supplied playlist and Buttons select tracks, favorites and queue actions. Artwork and official store links stay with the selected recording.",
      "Playback controls, Media scrubber and Slider operate the actual browser audio element. Progress and duration follow loaded audio; local files enable full queue and repeat behavior.",
      "The mobile composition separates Library, Playing and Queue while preserving the selected track, playback state and listening order.",
    ],
  },
] as const;

const microscopyStudy = {
  slug: "microscopy",
  title: "Microscopy acquisition planner",
  voice: "Keep the planned acquisition explicit.",
  law: "Plan stage positions, exposure sequences and multidimensional stacks before an acquisition.",
  story: "Prepare a bounded acquisition plan with named stage positions, capture steps and depth and time axes. Inspect the planned coordinates, review the frame count and total exposure, then export the working plan as JSON. Import validates a candidate before replacing the current draft.",
  what: "Microscopy",
  type: "Stage positions, exposure sequence, stack preview and plan review",
  module: "Grid system",
  ink: "A monochrome stage diagram, precise coordinates and flush planning controls.",
  use: "Edit positions and capture steps → inspect the planned stack → review and export",
  field: "A stage and stack preview beside a focused planning workflow.",
  note: "All records are local planning examples. No microscope is connected, no images are acquired and no movement is commanded. Total exposure is an arithmetic sum, not a wall-clock acquisition estimate. JSON exports retain the actual plan and its coordinate units.",
  components: ["Button", "Icon", "Input", "Select", "Quantity field", "Stage position list", "Acquisition sequencer", "Stack navigator"],
  modifications: [
    "Stage position list keeps selection, inclusion and order tied to stable record IDs. Quantity field edits supplied coordinates and exposures without treating missing values as zero.",
    "Acquisition sequencer defines the ordered capture steps. Stack navigator inspects planned depth and time coordinates while keeping every frame marked Not acquired.",
    "Review validates the working plan before export. Import stages a bounded JSON candidate; malformed files preserve the current records and unsaved position draft.",
  ],
} as const;

const calendarStudy = {
  slug: "calendar",
  title: "Calendar",
  voice: "Plan events and keep the week in view.",
  law: "A local calendar with month, week, day and agenda views, recurring events and iCalendar files.",
  story: "Move between the month, a timed week, a single day and an agenda. Create or edit events, organize calendars, and repeat a schedule. Search finds events across the calendar, while import and export let you move supported iCalendar records between tools. Desktop events can be dragged to a new time; a focused day agenda keeps the phone layout readable.",
  what: "Calendar",
  type: "Month, week, day, agenda and event editor",
  module: "Grid system",
  ink: "Paper and ink date grids, hairline time divisions and full-surface event selection.",
  use: "Choose a date → create or edit an event → organize the schedule → export",
  field: "Calendar navigation beside a date grid or agenda, with a focused event editor.",
  note: "Events and calendar settings stay in this browser. Import and export use .ics files; no account, invitations or calendar sync service is connected.",
  components: ["Button", "Calendar popover", "Checkbox", "Dialog", "Icon", "Input", "Native select", "Textarea"],
  modifications: [
    "Button and Icon navigate dates, switch views and open events. Checkbox controls calendar visibility, while Input searches the actual event records.",
    "Calendar popover edits dates and times with a keyboard-accessible month grid. Input, Native select and Textarea edit calendars, recurrence, location and notes. Dialog keeps event editing and recurring-event decisions within the working calendar.",
    "The custom month grid, timed week and day views, and agenda share the same local records. Desktop dragging changes an event’s schedule; validated browser storage and iCalendar files preserve actual event data.",
  ],
} as const;

const desktopStudy = {
  slug: "desktop-os",
  title: "Desktop OS",
  voice: "Familiar places to work, in a shared visual language.",
  law: "Four working desktops with independent files, windows and everyday applications.",
  story: "Mac OS, Windows, Linux and BeOS each bring their own way of working. Open and arrange windows, move between apps, write a document or draw something. The file manager, editor and terminal share the same files, and each desktop keeps its own workspace when you return.",
  what: "Desktop OS",
  type: "Window manager, file system, applications and desktop preferences",
  module: "Grid system",
  ink: "Paper, ink, hairline window frames and Inter across four distinct desktop conventions.",
  use: "Choose a desktop → open an app → save your work → return to it",
  field: "A working desktop with platform-specific menus, window controls and app switching.",
  note: "These browser workspaces adapt classic Mac OS, Windows XP, GNOME and BeOS conventions. Files and preferences stay in this browser, separately for each desktop. Terminal commands act on those files; external websites open in a browser tab. No native operating system is running.",
  components: ["Button", "Icon", "Input", "Slider", "Tabs", "Textarea", "Toggle group"],
  modifications: [
    "Tabs preserve independent desktops. Window controls support focus, movement, resizing, minimizing and maximizing, with platform-specific menus and application switching.",
    "Input, Textarea and Button connect the file manager, editor and command line to a persistent local file system. Drawings and text can be exported; the calculator, calendar and Mines game work locally.",
    "Desktop preferences adjust the workspace, while the process view lists its actual open windows. Classic Mac, Windows XP and BeOS behaviors adapt the creator’s existing browser prototypes using Vlak components and original interface artwork.",
  ],
} as const;

const reconciliationStudy = {
  slug: "reconciliation", title: "CSV reconciliation", what: "Reconciliation",
  voice: "Make differences explicit.",
  law: "Compare two CSV exports, review exceptions and keep a reusable reconciliation project.",
  story: "Choose two local CSV files and identify their key columns. Exact text matching preserves leading zeros and separates matches, missing records, conflicting values and ambiguous keys. Review the exceptions, then export the result and the recipe that produced it.",
  type: "Source comparison, exception review and export", module: "Grid system",
  ink: "Readable tables, stable record identities and a focused review panel.",
  use: "Open two files → choose keys → review differences → export",
  field: "Two source previews lead to a filtered worklist and record comparison.",
  note: "Files are processed in this browser. Matching is exact; duplicate keys require review. Data-preserving and spreadsheet-safe exports are separate choices. No accounting system is connected.",
  components: ["Badge", "Button", "Input", "Select"],
  modifications: [
    "Native file inputs preserve the source CSV. Input and Select configure key columns and comparison fields; a worker keeps parsing and matching away from the main interface.",
    "Badge and Button expose the actual comparison state. Decisions remain tied to the source records and are invalidated when their inputs change.",
    "Project files retain sources, recipe and review decisions. Browser copies, previous revisions and recovery downloads share the same lifecycle as the other local workspaces.",
  ],
} as const;

const specialistStudies = [...scienceStudies, ...engineeringStudies, ...careStudies, ...musicStudies] as const;
export const interfaces = [...originalInterfaces, ...specialistStudies, microscopyStudy, calendarStudy, desktopStudy, reconciliationStudy] as const;
export const orderedInterfaces = [...specialistStudies, microscopyStudy, calendarStudy, desktopStudy, reconciliationStudy, ...originalInterfaces.slice(6), ...originalInterfaces.slice(0, 6)];

export type InterfaceSlug = (typeof interfaces)[number]["slug"];

export const INTERFACE_SLUGS = interfaces.map((item) => item.slug);

export function interfaceBySlug(slug: string) {
  return interfaces.find((item) => item.slug === slug);
}

/** Each compact workspace changes its flow, not just its column widths. */
export const mobilePatterns: Record<InterfaceSlug, string> = {
  reconciliation: "On mobile, source setup stacks vertically. Selecting a result opens a focused record comparison with a Back action that retains filters, keys and review decisions.",
  calendar: "On mobile, a focused day agenda replaces the wide time grid. Date navigation, calendar filters, search and event creation remain reachable. The event editor uses the available screen width, preserving the selected day and saved records when returning to the agenda or opening fullscreen preview.",
  "desktop-os": "On mobile, the selected application fills the workspace. Apps and Tasks become separate drawers, keeping file operations and app switching within reach. Window positions, unsaved drafts and independent platform files survive changes between compact and desktop layouts.",
  microscopy: "On mobile, Positions, Sequence, Stack and Review are focused screens. Opening a position replaces the list with its editor; Back preserves the unsaved draft, while Apply and Discard remain explicit. The planned stack and import/export controls stay available without shrinking the desktop workspace.",
  ...scienceMobilePatterns,
  ...engineeringMobilePatterns,
  ...careMobilePatterns,
  ...musicMobilePatterns,
  agents: "On mobile, bottom navigation switches Tasks, Active, and Review. Opening a task replaces the workspace header and summaries with a full-height detail screen. Approvals and new-task submission stay in a bottom action area while the content scrolls.",
  line: "On mobile, conversations open into a full-width reading screen with a pinned composer. Response details replace the conversation, expose a keyboard-scrollable text region, and return focus to their opening action. Separate drafts survive conversation changes.",
  room: "On mobile, channels, conversations, threads, and channel editing use focused screens. The conversation and thread each keep their own pinned composer, while Back restores the selected channel or message and its keyboard focus.",
  wall: "On mobile, Feed and People sit in bottom navigation. A post opens into a full-width comments screen with a pinned reply field; profiles use the same focused navigation. The feed remains one readable column.",
  press: "On mobile, Overview, Jobs, and Invoices use bottom navigation. Selecting a job or invoice opens a full-height record screen with scrollable details and a pinned review action. Back returns focus to the record that opened it.",
  night: "On mobile, Vehicles, Map, and Trip are separate destinations in bottom navigation. Selecting a vehicle opens its map; trip details preserve all supplied stops, battery, arrival text, and the vehicle’s dispatch note. Back returns focus to the map’s trip action.",
  evening: "On mobile, browsing, filters, the restaurant menu, dish details, and the bag use focused screens. A bottom bag action keeps the order within reach, while Back navigation preserves the current restaurant and filters.",
  graphics: "On mobile, Preview and Direction replace the desktop control rail. One composition fills the preview, with a three-option picker below it. Generate returns to the preview; the full set of canvas, seed, variation, and export controls remains available.",
  render: "On mobile, Viewport and Inspector are separate destinations. The model keeps the full working width, its tools move into a horizontal bar, and the inspector provides scrollable material, mesh, and rotation controls without covering the model.",
  drive: "Three persistent blocks open Range & battery, Cabin and Media details. A right-hand pane slides over the vehicle on narrow screens and sits beside it on wide screens. Tap the active block again, close the pane or press Escape to return to the larger visualization.",
  orbit: "On mobile, Map, Assets, and Pass details replace the side rails. The observation fills the map view, assets become full-width selection rows, and all telemetry remains available in a separate scrollable inspector.",
  frontier: "On mobile, a disclosure menu replaces the desktop navigation row. Selecting a section closes the menu and moves to a single-column reading layout. The menu supports Escape and returns focus to its trigger.",
  android: "On mobile, Android opens at readable app size. View device switches to the proportional hardware drawing, while Use phone returns to the unscaled app. Back, Home, Recents and Quick Settings remain reachable, and full-screen preview preserves the mounted workspace.",
  ios: "On mobile, iOS opens at readable app size. View device switches to the proportional hardware drawing, while Use phone returns to the unscaled app. Contextual Back, the Home indicator and system centers remain reachable, and full-screen preview preserves the mounted workspace.",
  platforms: "On mobile, one full-width travel app keeps Plan, Today, and Profile in bottom navigation; journey details have a pinned save action and Back focus restoration. The same stations, profile, preferences, and saved trips persist between screens. Native date entry receives its own full-width row.",
  documentation: "On mobile, the document index and reader use the full specimen width. A disclosure exposes navigation or article contents; reader settings and Back stay reachable while the text scrolls independently.",
  "video-player": "On mobile, Watching and Playlist become separate full-width screens. The video keeps its natural aspect ratio, transport stays reachable, and volume receives its own row. Opening Playlist pauses the picture and preserves the selected video and position.",
  "music-player": "On mobile, Library, Playing and Queue use focused screens with persistent transport access. Playback and queue state survive navigation, and artwork keeps a readable, bounded scale.",
};
