export const interfaces = [
  {
    slug: "line",
    title: "AI chat",
    voice: "Keep long conversations easy to read and return to.",
    law: "A music discussion with a chat list, reading column, and reply inspector.",
    story:
      "An assistant for discussing music. A compact conversation list leaves room for longer replies, while an inspect pane lets readers revisit a response without losing their place. On mobile, the list and conversation become separate views.",
    what: "AI chat",
    type: "Chat list, conversation, reply inspector",
    module: "Grid system",
    ink: "Neutral surfaces, hairline dividers, and a quiet active state.",
    use: "Choose a conversation → send a message → inspect a reply",
    field: "Conversation rail, bounded reading column, composer at the lower edge.",
    note: "Try the conversation switcher, message field, and reply inspector. Replies are scripted; no text is sent to an AI service.",
    components: ["Button", "Icon", "Input", "Input group"],
    modifications: [
      "Input group joins Input and a grouped Button into a composer. The message field grows while Send keeps its width.",
      "A ghost Button with the close Icon sits in the inspector header. It shares the compact sizing of the other pane controls.",
      "Conversation rows use custom layout styles: title, preview, and date are stacked above a divider, with a tonal background for the active conversation.",
    ],
  },
  {
    slug: "press",
    title: "Dashboard",
    voice: "Track production without losing the job detail.",
    law: "A print-floor overview with output metrics, throughput, and job sheets.",
    story:
      "A print-floor dashboard for checking output and following up on a job. Three headline metrics lead into a throughput chart and a job list. Selecting a job reveals its next step; the full sheet opens in a side pane.",
    what: "Dashboard",
    type: "Rail, metrics, job sheet",
    module: "Grid system",
    ink: "Neutral chrome with one red signal reserved for live production.",
    use: "Scan metrics → select a job → open its sheet",
    field: "Three summary metrics above throughput and job detail.",
    note: "Switch between sample week and month figures, select a job, and open its sheet. The production data is fictional.",
    components: ["Button", "Card", "Icon", "Toggle group"],
    modifications: [
      "Toggle group becomes a compact Week/Month switch. Calendar and history Icons sit beside the labels, and one selection updates all summary figures.",
      "Cards form the metric, chart, and job regions. Shared dividers and square outer edges keep the dashboard aligned as a single grid.",
      "The throughput chart is a custom SVG. A ghost Button and close Icon give the job sheet the same dismissal control as the other interface studies.",
    ],
  },
  {
    slug: "wall",
    title: "Social feed",
    voice: "Give work in progress room to be seen.",
    law: "An image-led studio feed with comments and contributor profiles.",
    story:
      "A studio feed for reviewing work in progress. Large images sit above short updates, with authors and discussion counts close to each post. Comments and contributor profiles open in the same side pane, keeping the feed in view.",
    what: "Social feed",
    type: "Feed, comments, profile",
    module: "Grid system",
    ink: "Photographs carry the field; neutral controls and hairlines stay secondary.",
    use: "Browse posts → read comments → view a contributor",
    field: "People in the rail, masonry feed in the center, context on the right.",
    note: "Open a post or contributor to explore the side pane. The people, posts, and comments are fictional sample content.",
    components: ["Avatar", "Button", "Card", "Icon", "Input"],
    modifications: [
      "Card provides each post's outer frame. Custom content places photography above the author, update, and discussion counts, with square edges and inset text.",
      "Avatar is shared between posts, comments, and profiles. Names sit beside the small version; profiles use the larger size.",
      "The people rail becomes a compact row and the feed becomes a single column at narrow widths. The shared ghost Button closes either kind of side pane.",
    ],
  },
  {
    slug: "night",
    title: "Fleet management",
    voice: "Connect vehicle status with location and trip detail.",
    law: "A dispatch console with a selectable fleet, city map, and trip pane.",
    story:
      "A dispatch view for a small urban fleet. Each vehicle row pairs its status with a street location. Selecting a vehicle updates the map and trip detail, while the city view remains the main point of reference.",
    what: "Fleet management",
    type: "Fleet list, city map, trip detail",
    module: "Grid system",
    ink: "Muted map tones with one red position marker and high-contrast controls.",
    use: "Scan fleet → select a vehicle → inspect its trip",
    field: "Status rail, city-scale map, and an on-demand detail pane.",
    note: "Select a van and open its trip. The city scene is animated; vehicle positions and routes are sample data.",
    components: ["Button", "Card", "Icon"],
    modifications: [
      "Icons give vehicle, status, and location labels a consistent size. The fleet rows themselves are custom buttons with shared dividers.",
      "The trip action uses Button; the pane uses its ghost variant with a close Icon in the top-right corner.",
      "The city is a custom 3D scene inside the Vlak frame. On mobile, Fleet and Map navigation replace the desktop split view.",
    ],
  },
  {
    slug: "evening",
    title: "Food ordering",
    voice: "Find a kitchen and build an order.",
    law: "A food marketplace with search, filters, menus, and an order bag.",
    story:
      "A food-ordering interface that moves from kitchen discovery to a filled bag. Search and filters narrow the restaurants, large photographs lead into their menus, and dish details stay close to the order summary.",
    what: "Food ordering",
    type: "Market, store, bag",
    module: "Grid system",
    ink: "Large food photography, restrained controls, and clear selected states.",
    use: "Filter kitchens → choose a dish → review the bag",
    field: "Search and filters above an image-led market; details open alongside it.",
    note: "Filter the kitchens, open a menu, and add dishes to the bag. Orders stay in the demo; there is no checkout or payment.",
    components: ["Button", "Card", "Icon", "Input", "Input group", "Toggle group"],
    modifications: [
      "Input group pairs the search Icon with Input, keeping the icon fixed while the search field fills the available space.",
      "Toggle groups handle delivery, diet, and price filters. Their selected backgrounds provide a consistent state across all three groups.",
      "Restaurant and dish tiles are custom image buttons with compact text below. The shared ghost Button closes the dish or bag pane.",
    ],
  },
  {
    slug: "room",
    title: "Team chat",
    voice: "Keep channels, messages, and threads together.",
    law: "A studio chat with channel navigation, a composer, and threaded replies.",
    story:
      "A team chat for coordinating studio work. Channels and people sit beside the conversation, with a composer at the bottom. A message can open into a thread, and a person's profile uses the same pane.",
    what: "Team chat",
    type: "Channels, messages, thread",
    module: "Grid system",
    ink: "Neutral surfaces, compact avatars, and clear unread and active states.",
    use: "Choose a channel → read or reply → open a thread",
    field: "Channels and people in the rail, messages in the center, thread at right.",
    note: "Switch channels, send a sample message, or open a thread. Messages stay in the current browser session.",
    components: ["Avatar", "Button", "Icon", "Input", "Input group"],
    modifications: [
      "Avatar is reused in the people rail, message rows, and profile pane, pairing the same portrait with the same author throughout the workspace.",
      "Input group holds the message Icon and Input. A Send Button sits alongside it in a composer with equal outer padding and a flexible text field.",
      "Channel rows and thread layouts are custom. Vlak Icons mark actions, and the shared ghost Button closes the contextual pane.",
    ],
  },
  {
    slug: "agents",
    title: "Agent management",
    voice: "Coordinate agents, review their work, and decide what runs next.",
    law: "An agent workspace with a task queue, run activity, and approval controls.",
    story: "A workspace for delegating work to a small team of agents. The queue keeps assignments and status in view, while the detail pane follows one task from its brief to its output. Approval requests sit beside the work they affect. On a phone, the queue and task become separate views.",
    what: "Agent management",
    type: "Task queue, agent activity, review and approval",
    module: "Grid system",
    ink: "Monochrome status marks, tonal selection, and flush working panels.",
    use: "Choose a task → inspect the work → approve or pause the agent",
    field: "A compact queue beside a focused task detail and activity log.",
    note: "Queue a task, pause or resume a run, and respond to a review request. This is a local simulation with sample agents; it does not run models, edit files, or connect to an agent service. Changes reset when the page reloads.",
    components: ["Button", "Card", "Icon", "Input", "Progress", "Textarea", "Toggle group"],
    modifications: [
      "Cards become flush summary regions above a custom task queue. Full-row tonal selection, status text, and Icons keep states legible without color.",
      "Buttons handle task actions and mobile navigation. Input and Textarea compose the new-task form; Vlak's compact control radius stays separate from the square workspace frame.",
      "Toggle groups switch queue filters and detail views, while Progress shows task completion. Container queries turn the split workspace into a list-to-detail flow when the panel becomes narrow.",
    ],
  },
  {
    slug: "graphics",
    title: "Wallpaper generator",
    voice: "Make a geometric wallpaper and export it at 6K.",
    law: "A working wallpaper tool with canvas formats, variations, and PNG export.",
    story: "A geometric wallpaper generator with a control rail and three composition previews. Choose a canvas format, generate a set, then select a result to export. The preview area gives each composition room while keeping the controls within reach.",
    what: "Wallpaper generator",
    type: "Prompt, composition controls, 6K export",
    module: "Grid system",
    ink: "Working chrome stays neutral so color belongs to the generated work.",
    use: "Set direction → generate three fields → export a 6K PNG",
    field: "Control rail beside a large, image-led results canvas.",
    note: "Exports are real PNG files with a 6,144-pixel long edge. A geometric generator runs in the browser, using the direction text and variation setting to seed each composition.",
    components: ["Button", "Icon", "Textarea", "Toggle group"],
    modifications: [
      "Button handles Generate and Export, with the image Icon beside the generation action. Fixed control heights keep both actions aligned with their surroundings.",
      "Textarea and Toggle group retain Vlak's small control radius, including on mobile. Content-sized canvas options and a wider control rail keep each label readable. The variation slider is a native range input.",
      "Preview buttons contain generated SVG artwork and a caption. A selected border identifies the composition used for the full-resolution PNG export.",
    ],
  },
  {
    slug: "render",
    title: "3D workspace",
    voice: "Inspect a live vehicle model in a 3D workspace.",
    law: "A 3D editor study with a live vehicle model, tool rail, and properties pane.",
    story: "A modeling workspace built around a detailed production vehicle. Orbit the model, inspect its mesh, and compare body finishes. A narrow tool rail and model information frame the live viewport without covering the car.",
    what: "3D workspace",
    type: "Viewport, toolbars, object properties",
    module: "Grid system",
    ink: "Dark production chrome, pale selected controls, and neutral model lighting.",
    use: "Rotate the model → show the mesh → compare materials",
    field: "Full toolbar chrome around a dominant visual viewport.",
    note: "The licensed 204,461-triangle vehicle model loads through Sketchfab and needs an internet connection and WebGL. Body paint is adapted in the viewer. Geometry editing and production rendering are outside this study's scope.",
    components: ["Button", "Icon", "Tree view", "Property grid", "Description list"],
    modifications: [
      "Ghost Buttons become equal square tool cells. Centered Icons and a high-contrast selected state identify auto-rotation, mesh view, and camera reset.",
      "Tree view selects the inspector section. Property grid edits the real material, mesh, and rotation settings; Description list aligns the mesh metadata.",
      "The vehicle model runs in an embedded Sketchfab viewer. Vlak controls use its camera, wireframe, and material APIs; loading, retry, and attribution remain visible parts of the workspace.",
    ],
  },
  {
    slug: "drive",
    title: "EV controls",
    voice: "Bring range, climate, and media into one display.",
    law: "A vehicle display with a profile illustration and four status and control panels.",
    story: "An electric vehicle concept developed from the vehicle study in the Vlak films. A line illustration anchors the display above range, battery, cabin, and media panels. Large values and short labels make the lower row easy to scan.",
    what: "EV controls",
    type: "Vehicle status, media, climate, connectivity",
    module: "Grid system",
    ink: "Charcoal surfaces, silver linework, pale type, and quiet status indicators.",
    use: "Choose a vehicle view → adjust the cabin → control media",
    field: "Vehicle profile above four equal status and control fields.",
    note: "The vehicle silhouette connects the study to the Vlak films. Vehicle settings, journey details, and electric-system data are fictional. The player shows Fortress Down by Loathe; playback controls are simulated and do not stream audio.",
    components: ["Button", "Card", "Icon", "Progress", "Toggle group", "Metric", "Number field", "Playback controls", "Media scrubber", "Connection status"],
    modifications: [
      "Four Cards share borders beneath the vehicle illustration. Metrics and the numeric cabin input share the same label and value tracks. Narrow layouts stack the panels without clipping their controls.",
      "Toggle group switches Vehicle, Journey, and Energy views. Buttons and Icons handle local vehicle settings, climate, and media, retaining the small control radius and centered icon geometry.",
      "Playback controls and Media scrubber provide reusable transport and seeking with space before the track. Number field stacks temperature actions at the top right. Connection status aligns the icon and text in the header.",
    ],
  },
  {
    slug: "orbit",
    title: "Satellite operations",
    voice: "Put coverage, pass timing, and telemetry in context.",
    law: "An Earth-observation console with an asset rail, animated map, and pass detail.",
    story: "A fictional European satellite operations console. The observation image holds the center, flanked by an asset list and pass details. Selecting an asset updates its telemetry, while layer controls and animated markers keep the map and its context connected.",
    what: "Satellite operations",
    type: "Earth observation, passes, telemetry",
    module: "Grid system",
    ink: "Dark analytical chrome with cyan telemetry and full-color earth imagery.",
    use: "Select an asset → compare display layers → queue a capture",
    field: "Asset rail, dominant orbital image, telemetry and pass detail.",
    note: "Asset selection, display layers, and the capture queue work locally. Satellites and telemetry are fictional; the map uses an illustrative image.",
    components: ["Badge", "Button", "Card", "Icon", "Item", "Progress", "Toggle group", "Canvas controls"],
    modifications: [
      "Button supplies the capture action and asset selection. Selected assets use a full-surface fill, never a leading bar or inset edge stripe.",
      "Card, Card label, Card title, Item, Progress, and Badge compose the pass inspector. Compact Item rows align telemetry labels and values; Progress shows cloud cover; Badge reports queue state.",
      "Toggle group switches map layers and Canvas controls zooms or resets the observation image. Track lines and target markers remain custom overlays, with their motion disabled when the visitor requests reduced animation.",
    ],
  },
  {
    slug: "frontier",
    title: "Frontier model company",
    voice: "Introduce a model with a clear next step.",
    law: "A company landing page with a model proposition, capability cards, and research overview.",
    story: "A landing page for a fictional European model company. The opening statement sits at the lower edge of a subtle perspective grid. The primary action opens a model overview, while a secondary action reveals the research summary in the same card layout.",
    what: "Frontier model company",
    type: "Company landing page, model and research summaries",
    module: "Grid system",
    ink: "Editorial white space, black type, and one cobalt research signal.",
    use: "Read the proposition → explore the model → open the system card",
    field: "Compact navigation, a large opening statement, three summary cards.",
    note: "Switch between Models, Research, and Company to explore the page. Aster Labs and its model capabilities are fictional.",
    components: ["Button", "Card"],
    modifications: [
      "Card, Card label, Card title, and Card body form the model summary. Their outer sizing is adapted to equal columns with shared dividers.",
      "Buttons use the page's local paper-and-ink colors. A custom text-style button opens the research summary beside the primary model action.",
      "The hero's perspective grid is a custom CSS background. The heading and actions align to its lower-left edge, then reflow into a single column on mobile.",
    ],
  },
  {
    slug: "platforms",
    title: "Mobile platforms",
    voice: "One travel plan, two familiar mobile experiences.",
    law: "A side-by-side travel app study using iOS and Android conventions.",
    story: "The same Rotterdam itinerary shown on an iPhone and an Android device. Train information, appointments, and destinations match. Header treatment, navigation, and action placement change to reflect the conventions of each platform.",
    what: "Mobile platforms",
    type: "iOS and Android interface comparison",
    module: "Grid system",
    ink: "Shared content palette with platform-specific navigation and control treatment.",
    use: "Compare the same itinerary, actions, and states across platforms",
    field: "Two complete phone frames shown at equal scale.",
    note: "Switch tabs, save the trip, and open the profile on either device. Each web preview keeps its own local state.",
    components: ["Button", "Card", "Icon", "Toggle group"],
    modifications: [
      "Both devices reuse the same Vlak Icons for Plan, Today, and You, keeping destinations recognizable across the two layouts.",
      "Card holds the train summary in both devices. Local spacing and colors adapt it to each platform while retaining the same departure, route, and status.",
      "Navigation, itinerary rows, and phone frames are custom. iOS uses a large title and tab bar; Android uses an app bar, navigation bar, and separate save action.",
    ],
  },
] as const;

export type InterfaceSlug = (typeof interfaces)[number]["slug"];

export const INTERFACE_SLUGS = interfaces.map((item) => item.slug);

export function interfaceBySlug(slug: string) {
  return interfaces.find((item) => item.slug === slug);
}

/** Each compact workspace changes its flow, not just its column widths. */
export const mobilePatterns: Record<InterfaceSlug, string> = {
  agents: "On mobile, bottom navigation switches Tasks, Active, and Review. Opening a task replaces the workspace header and summaries with a full-height detail screen. Approvals and new-task submission stay in a bottom action area while the content scrolls.",
  line: "On mobile, the chat list opens into a full-width conversation with a pinned composer. Conversation information and response details use their own screen with Back navigation. Text entry stays at 16px and focus returns to the control that opened the screen.",
  room: "On mobile, channels open into a conversation, and a message opens into a separate thread screen with its own reply field. A contextual header replaces the desktop rail, and Back preserves the current channel and conversation.",
  wall: "On mobile, Feed and People sit in bottom navigation. A post opens into a full-width comments screen with a pinned reply field; profiles use the same focused navigation. The feed remains one readable column.",
  press: "On mobile, Overview, Jobs, and Invoices become separate destinations in bottom navigation. The overview prioritizes output and jobs needing attention. A job opens into a full-screen production brief with a Back action.",
  night: "On mobile, Fleet and Map are separate views. Selecting a vehicle opens its map and a compact vehicle card. Trip details replace the map with a readable itinerary, with Back and Show on map actions.",
  evening: "On mobile, browsing, filters, the restaurant menu, dish details, and the bag use focused screens. A bottom bag action keeps the order within reach, while Back navigation preserves the current restaurant and filters.",
  graphics: "On mobile, Preview and Direction replace the desktop control rail. One composition fills the preview, with a three-option picker below it. Generate returns to the preview; the full set of canvas, seed, variation, and export controls remains available.",
  render: "On mobile, Viewport and Inspector are separate destinations. The model keeps the full working width, its tools move into a horizontal bar, and the inspector provides scrollable material, mesh, and rotation controls without covering the model.",
  drive: "On mobile, Vehicle, Controls, and Media replace the four-column dashboard. Vehicle keeps the illustration and journey actions in focus; settings become readable control rows, and media gets a dedicated playback screen. State is shared between views.",
  orbit: "On mobile, Map, Assets, and Pass details replace the side rails. The observation fills the map view, assets become full-width selection rows, and all telemetry remains available in a separate scrollable inspector.",
  frontier: "On mobile, a disclosure menu replaces the desktop navigation row. Selecting a section closes the menu and moves to a single-column reading layout. The menu supports Escape and returns focus to its trigger.",
  platforms: "On mobile, an iOS/Android picker shows one full-width handset at a time instead of shrinking two phones side by side. Both keep their own saved-trip and navigation state, with a scrollable content area and persistent platform-specific navigation.",
};
