import type { VlakComponent } from "./schema";

/** Specialist editor surfaces with explicit host-owned state and units. */
export const workbenchComponents: VlakComponent[] = [
  {
    name: "patchbay", title: "Patchbay", category: "creative",
    description: "Connects supplied source and destination ports through a keyboard-navigable matrix, with signal types, channel groups, and blocked-route reasons.",
    classes: ["rs-patchbay", "rs-patchbay-legend", "rs-patchbay-viewport", "rs-patchbay-table", "rs-patchbay-header", "rs-patchbay-detail", "rs-patchbay-cell", "rs-patchbay-control", "rs-patchbay-connected", "rs-patchbay-blocked", "rs-patchbay-input", "rs-patchbay-note"],
    css: ["components/patchbay.css"], react: "components/patchbay.tsx", registryDependencies: [],
    snippet: `<fieldset class="rs-patchbay"><legend class="rs-patchbay-legend">Studio routing</legend><div class="rs-patchbay-viewport"><table class="rs-patchbay-table"><thead><tr><th class="rs-patchbay-header" scope="col">Source / destination</th><th class="rs-patchbay-header" scope="col">Monitor left<span class="rs-patchbay-detail">Outputs · audio</span></th></tr></thead><tbody><tr><th class="rs-patchbay-header" scope="row">Mix left<span class="rs-patchbay-detail">Mix bus · audio</span></th><td class="rs-patchbay-cell"><label class="rs-patchbay-control rs-patchbay-connected"><span aria-hidden="true">✓</span><input class="rs-patchbay-input" type="checkbox" checked aria-label="Mix left to Monitor left" /></label></td></tr></tbody></table></div></fieldset>`,
    example: `import { Patchbay } from "@noorddev/vlak-react";

<Patchbay label="Studio routing" name="routes"
  sources={[{ id: "mix-l", label: "Mix left", group: "Mix bus", signalType: "audio" }]}
  destinations={[{ id: "out-l", label: "Monitor left", group: "Outputs", signalType: "audio" }, { id: "clock", label: "Clock", signalType: "control" }]}
  defaultValue={[{ sourceId: "mix-l", destinationId: "out-l" }]} />`,
    usage: { use: ["An audio or signal-routing matrix whose ports and confirmed connections come from the host.", "value/defaultValue/onValueChange for controlled routing requests or a local prototype; the host applies real routing changes.", "Signal type strings must match; getBlockReason can add a host-specific restriction with a visible explanation.", "Existing incompatible connections can be disconnected; routes involving unavailable ports remain explicitly listed and preserved."], avoid: ["Assuming the component creates audio streams, manages clocking, or configures a routing engine.", "Silently deleting host connections when a port temporarily disappears."] },
    keyboard: [{ keys: "Tab", does: "Enters the connection matrix at one enabled checkbox, then leaves the matrix." }, { keys: "Arrow keys", does: "Moves focus through enabled crosspoints in the same row or column." }, { keys: "Home, End", does: "Moves to the first or last enabled crosspoint in the row; Control includes the whole matrix." }, { keys: "Space", does: "Toggles the focused connection through the native checkbox." }],
    a11y: ["Native table headers identify sources and destinations; every checkbox also names both ports.", "Connection targets are at least 44px, with a full-surface checked state and forced-colors support.", "Blocked crosspoints expose reasons in text and descriptions. Roving focus skips disabled cells.", "Named checkboxes submit connection pairs; read-only hidden values preserve existing routes. Form reset restores uncontrolled defaults.", "The ref and native fieldset attributes reach the root fieldset."],
    aliases: ["Patchbay", "Routing matrix", "Audio routing", "Crosspoint matrix", "Connection matrix", "Signal patching"],
  },
  {
    name: "kerning-pair-editor", title: "Kerning pair editor", category: "creative",
    description: "Edits supplied glyph-pair offsets in font units, with baseline and edited previews, bounded keyboard nudging, and one-step undo.",
    classes: ["rs-kerning-pair-editor", "rs-kerning-pair-editor-legend", "rs-kerning-pair-editor-toolbar", "rs-kerning-pair-editor-field", "rs-kerning-pair-editor-input", "rs-kerning-pair-editor-button", "rs-kerning-pair-editor-previews", "rs-kerning-pair-editor-preview", "rs-kerning-pair-editor-glyphs", "rs-kerning-pair-editor-glyph", "rs-kerning-pair-editor-note"],
    css: ["components/kerning-pair-editor.css"], react: "components/kerning-pair-editor.tsx", registryDependencies: ["select", "input", "button"],
    snippet: `<fieldset class="rs-kerning-pair-editor"><legend class="rs-kerning-pair-editor-legend">Pair spacing</legend><div class="rs-kerning-pair-editor-previews"><figure class="rs-kerning-pair-editor-preview"><figcaption class="rs-kerning-pair-editor-note">Edited: -80 units</figcaption><div class="rs-kerning-pair-editor-glyphs" style="font-family:Georgia,serif" role="img" aria-label="A followed by V, edited offset -80 units"><span class="rs-kerning-pair-editor-glyph" aria-hidden="true">A</span><span class="rs-kerning-pair-editor-glyph" aria-hidden="true" style="margin-inline-start:-0.08em">V</span></div></figure></div><label class="rs-kerning-pair-editor-field">Offset (font units)<input class="rs-input rs-input-full rs-kerning-pair-editor-input" type="number" value="-80" min="-1000" max="1000" step="any" /></label></fieldset>`,
    example: `import { KerningPairEditor } from "@noorddev/vlak-react";

<KerningPairEditor label="Pair spacing" name="kerning" fontFamily="Georgia, serif" unitsPerEm={1000}
  pairs={[{ id: "av", left: "A", right: "V" }, { id: "to", left: "T", right: "o" }]}
  baselineOffsets={{ av: -60, to: -40 }} defaultValue={{ av: -80, to: -50 }} />`,
    usage: { use: ["Supplied glyph strings, a caller-selected font family, and explicit units per em.", "value/defaultValue/onValueChange as a map from pair id to offset; null or an absent entry means not supplied.", "baselineOffsets to compare and reset a pair; missing baselines never imply zero.", "Optional min/max bounds default to negative and positive units per em; typed values retain native validation.", "activePairId/defaultActivePairId/onActivePairChange for caller-owned pair navigation."], avoid: ["Treating the preview as a font shaping engine, font-file editor, or source of baseline kerning.", "Assuming a requested font is installed; the browser uses its normal font fallback.", "Undoing external host changes; undo is available only while the latest requested edit remains current."] },
    keyboard: [{ keys: "Tab", does: "Moves through the pair selector, navigation, offset editor, reset, and undo actions." }, { keys: "Arrow left, Arrow right", does: "Nudges the focused offset by one font unit within the supplied bounds." }, { keys: "Shift + Arrow left, Shift + Arrow right", does: "Nudges the focused offset by ten font units." }, { keys: "Enter, Space", does: "Activates the focused previous, next, reset, or undo button." }],
    a11y: ["A fieldset and legend name the editor; Vlak Select and Input controls have 44px targets.", "Baseline and edited offsets remain text, and each pair preview has an accessible description.", "Preview spacing is offset divided by units per em; intrinsic browser kerning and ligatures are disabled for the comparison.", "Missing or invalid font units suppress geometry; typed out-of-bounds values expose native validity and a visible explanation.", "The ref and native attributes reach the fieldset. Named offsets submit per pair; reset restores uncontrolled offsets and clears undo."],
    aliases: ["KerningPairEditor", "Kerning editor", "Glyph pair spacing", "Font pair editor", "Pair adjustment"],
  },
  {
    name: "assembly-variant-matrix", title: "Assembly variant matrix", category: "electronics",
    description: "Edits independent population, bill-of-materials, and placement flags per reference and assembly variant, preserving unspecified choices.",
    classes: ["rs-assembly-variant-matrix", "rs-assembly-variant-matrix-legend", "rs-assembly-variant-matrix-viewport", "rs-assembly-variant-matrix-table", "rs-assembly-variant-matrix-header", "rs-assembly-variant-matrix-part", "rs-assembly-variant-matrix-cell", "rs-assembly-variant-matrix-details", "rs-assembly-variant-matrix-summary", "rs-assembly-variant-matrix-editor", "rs-assembly-variant-matrix-field", "rs-assembly-variant-matrix-select", "rs-assembly-variant-matrix-note"],
    css: ["components/assembly-variant-matrix.css"], react: "components/assembly-variant-matrix.tsx", registryDependencies: ["select", "dropdown-menu"],
    snippet: `<fieldset class="rs-assembly-variant-matrix"><legend class="rs-assembly-variant-matrix-legend">Assembly options</legend><div class="rs-assembly-variant-matrix-viewport"><table class="rs-assembly-variant-matrix-table"><thead><tr><th class="rs-assembly-variant-matrix-header" scope="col">Reference / variant</th><th class="rs-assembly-variant-matrix-header" scope="col">Pilot</th></tr></thead><tbody><tr><th class="rs-assembly-variant-matrix-header" scope="row">R1<span class="rs-assembly-variant-matrix-part">10 kΩ resistor</span></th><td class="rs-assembly-variant-matrix-cell"><details class="rs-assembly-variant-matrix-details"><summary class="rs-assembly-variant-matrix-summary">Edit R1 in Pilot<span class="rs-assembly-variant-matrix-part">Not specified</span></summary><div class="rs-assembly-variant-matrix-editor"><div class="rs-assembly-variant-matrix-field"><span>Populated</span><div class="rs-select rs-select-fluid rs-assembly-variant-matrix-select"><button class="rs-dropdown" role="combobox" aria-label="Populated, R1 in Pilot" aria-haspopup="listbox" aria-expanded="false" type="button">Unspecified</button></div></div></div></details></td></tr></tbody></table></div></fieldset>`,
    example: `import { AssemblyVariantMatrix } from "@noorddev/vlak-react";

<AssemblyVariantMatrix label="Assembly options" name="assembly"
  references={[{ id: "r1", label: "R1", partLabel: "10 kΩ resistor" }]}
  variants={[{ id: "pilot", label: "Pilot" }, { id: "production", label: "Production" }]}
  defaultValue={[{ referenceId: "r1", variantId: "pilot", populated: true, includeInBom: true, includeInPlacement: true }, { referenceId: "r1", variantId: "production", populated: false, includeInBom: true, includeInPlacement: false }]} />`,
    usage: { use: ["Caller-owned assembly references, part labels, and named build variants.", "Three independent boolean-or-null flags: population, bill-of-materials inclusion, and placement-file inclusion.", "value/defaultValue/onValueChange to receive the proposed cell array; editing one flag leaves the other flags unchanged.", "Missing cells begin unspecified. Conflicting duplicate cells and unavailable references remain visible rather than being silently merged."], avoid: ["Inferring bill-of-materials or placement policy from the populated flag.", "Assuming the component generates manufacturing files or changes a board design.", "Treating unspecified flags as excluded or not populated."] },
    keyboard: [{ keys: "Tab", does: "Moves through native cell summaries and controls in expanded editors." }, { keys: "Enter, Space", does: "Opens or closes the focused cell's native details editor." }, { keys: "Arrow keys", does: "Opens and navigates the Vlak selector between Unspecified, Yes, and No; Enter confirms the highlighted choice." }],
    a11y: ["Native row and column headers identify each reference and variant; cell editor summaries repeat that context.", "Each independent Vlak Select has a flag-specific name including its reference and variant, and a 44px target.", "Compact summaries expose all three flags in text; no color or population shortcut carries policy.", "Native details reveal the editor without focus traps; Vlak Select supplies the choice menu, and overflow remains inside the matrix.", "Named controls submit each flag separately. Read-only values and native form reset are supported; the ref reaches the fieldset."],
    aliases: ["AssemblyVariantMatrix", "Assembly options", "Population matrix", "Bill of materials variants", "Placement options", "Reference variant table"],
  },
];
