import type { VlakComponent } from "./schema";

/** Patient context and application-controlled care workflows. */
export const healthCare: VlakComponent[] = [
  {
    name: "patient-banner",
    title: "Patient banner",
    description: "Keeps a supplied patient identity, identifiers, and recorded context together in a responsive band.",
    category: "health",
    classes: ["rs-patient-banner", "rs-patient-banner-name", "rs-patient-banner-identifiers", "rs-patient-banner-field", "rs-patient-banner-label", "rs-patient-banner-value", "rs-patient-banner-context", "rs-patient-banner-missing"],
    css: ["components/patient-banner.css"],
    react: "components/patient-banner.tsx",
    registryDependencies: [],
    snippet: '<div class="rs-patient-banner" role="group" aria-label="Robin Ellis"><p class="rs-patient-banner-name">Robin Ellis</p><dl class="rs-patient-banner-identifiers"><div class="rs-patient-banner-field"><dt class="rs-patient-banner-label">Patient ID</dt><dd class="rs-patient-banner-value">Demo 042</dd></div></dl><dl class="rs-patient-banner-context"><div class="rs-patient-banner-field"><dt class="rs-patient-banner-label">Allergies</dt><dd class="rs-patient-banner-value">Not reviewed</dd></div></dl></div>',
    example: 'import { PatientBanner } from "@noorddev/vlak-react";\n\n<PatientBanner patientName="Robin Ellis" identifiers={[{ id: "record", label: "Patient ID", value: "Demo 042" }]} contextItems={[{ id: "allergies", label: "Allergies", value: "Not reviewed" }, { id: "language", label: "Preferred language", value: "English, as recorded" }]} />',
    usage: {
      use: ["Patient record headers and care workspaces where identity and recorded context must stay together.", "Supply explicit values such as Unknown, Not reviewed, or None recorded according to the actual source record."],
      avoid: ["Inferring age from a birth date or treating missing context as no allergies.", "Urgent notifications that need a live announcement; the banner is static context."],
    },
    keyboard: [{ keys: "None", does: "Static identity and description lists add no keyboard stop. Any supplied child controls keep their native behavior." }],
    a11y: ["The patient name labels a group; identifiers and context use dl, dt, and dd in reading order.", "Unknown and none-recorded distinctions are supplied as visible text. Empty defaults describe missing data without making clinical claims.", "The root forwards its div ref, native attributes, className, and style."],
    aliases: ["PatientBanner", "Patient header", "Patient summary", "Clinical context", "EHR header"],
  },
  {
    name: "medication-schedule",
    title: "Medication schedule",
    description: "Lists supplied medication, dose, time, and recorded status with controlled 44px recording actions.",
    category: "health",
    classes: ["rs-medication-schedule", "rs-medication-schedule-header", "rs-medication-schedule-zone", "rs-medication-schedule-list", "rs-medication-schedule-row", "rs-medication-schedule-time", "rs-medication-schedule-body", "rs-medication-schedule-name", "rs-medication-schedule-detail", "rs-medication-schedule-status", "rs-medication-schedule-actions", "rs-medication-schedule-action", "rs-medication-schedule-empty"],
    css: ["components/medication-schedule.css"],
    react: "components/medication-schedule.tsx",
    registryDependencies: ["button"],
    snippet: '<div class="rs-medication-schedule" role="group" aria-label="Medication schedule"><div class="rs-medication-schedule-header"><span>14 September</span><span class="rs-medication-schedule-zone">Europe/Amsterdam, UTC+02:00</span></div><ol class="rs-medication-schedule-list"><li class="rs-medication-schedule-row"><span class="rs-medication-schedule-time">08:00</span><div class="rs-medication-schedule-body"><p class="rs-medication-schedule-name">Example medication</p><p class="rs-medication-schedule-detail">Dose supplied by the care team</p><p class="rs-medication-schedule-status">Not recorded</p></div></li></ol></div>',
    example: 'import { MedicationSchedule } from "@noorddev/vlak-react";\n\n<MedicationSchedule dateLabel="14 September" timeZone="Europe/Amsterdam, UTC+02:00" items={[{ id: "morning", name: "Example medication", dose: "Dose supplied by the care team", timeLabel: "08:00", status: "Not recorded", instructions: "Instructions supplied by the care team" }]} />\n\n// For editing, pass explicit item.actions and onAction(itemId, actionId).\n// The caller persists the choice, sets item.pending, and supplies the new status.',
    usage: {
      use: ["Displaying an existing medication schedule and requesting explicit record updates.", "Supply timezone, dosing text, instructions, action labels, and recorded statuses from the application."],
      avoid: ["Calculating doses, suggesting medication, guessing overdue entries, or declaring a record saved from a click alone.", "Treating an empty list as evidence that a patient takes no medication."],
    },
    keyboard: [{ keys: "Tab", does: "Moves between enabled recording buttons when onAction and item actions are supplied." }, { keys: "Enter, Space", does: "Requests the selected recording action. Pending or disabled rows cannot request changes." }],
    a11y: ["Rows remain in supplied order in an ordered list. Optional dateTime values are passed through unchanged.", "Action names include the visible action label and medication name. Each action is described by its scheduled time, dose, and recorded status to distinguish repeated doses. Buttons have at least 44px targets.", "Pending state remains visible alongside the existing status, uses aria-busy and a polite status region, and disables recording actions.", "No internal persistence or automatic success state. Without onAction the schedule is read-only."],
    aliases: ["MedicationSchedule", "Medication list", "Medication record", "Dose log", "Medication administration record"],
  },
  {
    name: "appointment-card",
    title: "Appointment card",
    description: "Groups supplied appointment time, timezone, clinician, location, and status with an optional action slot.",
    category: "health",
    classes: ["rs-appointment-card", "rs-appointment-card-header", "rs-appointment-card-title", "rs-appointment-card-status", "rs-appointment-card-when", "rs-appointment-card-date", "rs-appointment-card-time", "rs-appointment-card-details", "rs-appointment-card-field", "rs-appointment-card-label", "rs-appointment-card-value", "rs-appointment-card-actions"],
    css: ["components/appointment-card.css"],
    react: "components/appointment-card.tsx",
    registryDependencies: [],
    snippet: '<div class="rs-appointment-card" role="group" aria-label="Care team check-in"><div class="rs-appointment-card-header"><p class="rs-appointment-card-title">Care team check-in</p><span class="rs-appointment-card-status">Confirmed</span></div><div class="rs-appointment-card-when"><span class="rs-appointment-card-date">18 September 2026</span><span class="rs-appointment-card-time">10:30–11:00 · Europe/Amsterdam, UTC+02:00</span></div><dl class="rs-appointment-card-details"><div class="rs-appointment-card-field"><dt class="rs-appointment-card-label">Clinician</dt><dd class="rs-appointment-card-value">Alex Morgan</dd></div><div class="rs-appointment-card-field"><dt class="rs-appointment-card-label">Location</dt><dd class="rs-appointment-card-value">Room 04, demo clinic</dd></div></dl></div>',
    example: 'import { AppointmentCard } from "@noorddev/vlak-react";\n\n<AppointmentCard appointmentTitle="Care team check-in" dateLabel="18 September 2026" timeLabel="10:30–11:00" timeZone="Europe/Amsterdam, UTC+02:00" dateTime="2026-09-18T10:30:00+02:00" clinician="Alex Morgan" location="Room 04, demo clinic" status="Confirmed" />\n\n// Supply children for real navigation links or application-owned actions.',
    usage: {
      use: ["Confirmed, proposed, cancelled, or otherwise explicitly supplied appointments.", "Add real links or buttons as children when navigation or an action is available."],
      avoid: ["Inferring confirmation, converting timezones, or deriving a relative date from the system clock.", "Rendering placeholder Join, Cancel, or Reschedule buttons without working actions."],
    },
    keyboard: [{ keys: "Tab, Enter, Space", does: "Supplied links and buttons retain their native keyboard interactions. The card adds no tab stop." }],
    a11y: ["Appointment title names a group. Date, time, timezone, and status are text; clinician and location use a description list.", "Missing clinician and location are explicitly labelled as not supplied.", "Use native action controls with accessible names and at least 44px targets in the children slot.", "Native root attributes and the div ref pass through. The caller owns status updates and announcements."],
    aliases: ["AppointmentCard", "Visit card", "Booking card", "Care appointment", "Consultation details"],
  },
  {
    name: "care-plan",
    title: "Care plan",
    description: "Lists supplied care tasks, owners, due labels, and statuses with controlled completion requests.",
    category: "health",
    classes: ["rs-care-plan", "rs-care-plan-description", "rs-care-plan-list", "rs-care-plan-row", "rs-care-plan-title", "rs-care-plan-check", "rs-care-plan-detail", "rs-care-plan-metadata", "rs-care-plan-field", "rs-care-plan-label", "rs-care-plan-value", "rs-care-plan-pending", "rs-care-plan-empty"],
    css: ["components/care-plan.css"],
    react: "components/care-plan.tsx",
    registryDependencies: ["checkbox"],
    snippet: '<div class="rs-care-plan" role="group" aria-label="Care plan"><ul class="rs-care-plan-list"><li class="rs-care-plan-row"><p class="rs-care-plan-title">Confirm the next visit</p><dl class="rs-care-plan-metadata"><div class="rs-care-plan-field"><dt class="rs-care-plan-label">Owner</dt><dd class="rs-care-plan-value">Robin Ellis</dd></div><div class="rs-care-plan-field"><dt class="rs-care-plan-label">Due</dt><dd class="rs-care-plan-value">17 September</dd></div><div class="rs-care-plan-field"><dt class="rs-care-plan-label">Status</dt><dd class="rs-care-plan-value">Open</dd></div></dl></li></ul></div>',
    example: 'import { CarePlan } from "@noorddev/vlak-react";\n\n<CarePlan tasks={[{ id: "visit", title: "Confirm the next visit", owner: "Robin Ellis", dueLabel: "17 September", status: "Open", completed: false }]} />\n\n// Pass onCompletedChange(taskId, completed) to request changes.\n// The caller persists completion and supplies updated tasks and pending states.',
    usage: {
      use: ["Existing care plans with named owners and application-supplied deadlines and task status.", "Supply an explicit completed boolean and onCompletedChange to enable a completion control."],
      avoid: ["Generating treatment plans or deriving task urgency from dates.", "Treating an unknown completion state as unchecked or showing success before the caller updates the record."],
    },
    keyboard: [{ keys: "Tab", does: "Moves between enabled completion checkboxes when editing is available." }, { keys: "Space", does: "Requests a completion change through onCompletedChange. The checkbox stays at the supplied value until the caller updates it." }],
    a11y: ["Task labels name native checkboxes with at least 44px label targets; the recorded status describes each checkbox.", "Pending or disabled tasks cannot be changed. Pending text is visible in a polite status region with aria-busy on the task.", "Tasks with unknown completion or no change callback render as static text, without an invented checkbox state.", "Owner and due-date omissions are explicitly marked as not supplied. Dates are never parsed or inferred."],
    aliases: ["CarePlan", "Care tasks", "Patient checklist", "Care coordination", "Treatment task list"],
  },
];
