import type { VlakComponent } from "./schema";

export const aiComponents: VlakComponent[] = [
  {
    name: "chat",
    title: "Chat",
    description: "A subtle 1px outline with 4px corners, a named header, scrollable conversation, and a composer anchored below the history.",
    category: "ai",
    classes: ["rs-chat", "rs-chat-header", "rs-chat-heading", "rs-chat-title", "rs-chat-description", "rs-chat-actions", "rs-chat-history", "rs-chat-composer", "rs-chat-footer"],
    css: ["components/chat.css"],
    react: "components/chat.tsx",
    registryDependencies: ["conversation"],
    snippet: `<section class="rs-chat" aria-labelledby="project-chat-title"><header class="rs-chat-header"><div class="rs-chat-heading"><span class="rs-chat-title" id="project-chat-title">Project brief</span><div class="rs-chat-description">Ask about the current draft</div></div></header><div class="rs-chat-history rs-conversation" style="height:28rem"><div class="rs-conversation-viewport" role="log" aria-label="Project brief messages" aria-live="off" tabindex="0" style="max-height:100%"><div class="rs-conversation-content"><p>You: What needs to change?</p><p>Assistant: Name the owner and next step.</p></div></div></div><div class="rs-chat-composer"><form aria-label="Message composer" style="display:flex;align-items:flex-end;gap:4px"><textarea aria-label="Message" name="message" rows="1" style="flex:1;min-width:0;min-height:44px;max-height:10rem"></textarea><button type="submit" aria-label="Send message" style="width:44px;height:44px;flex:none"><svg viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" aria-hidden="true"><path d="M8 12.5v-9M4.5 7 8 3.5 11.5 7" /></svg></button></form></div></section>`,
    example: "import { Chat, MessageComposer, Reasoning, Response, ResponseActions, type ComposedMessage } from \"@noorddev/vlak-react\";\n\nexport function ProjectChat({ onSend, generating, onStop }: {\n  onSend: (message: ComposedMessage) => void | Promise<void>;\n  generating: boolean;\n  onStop: () => void;\n}) {\n  return <Chat title=\"Project brief\" description=\"Ask about the current draft\" conversationLabel=\"Project brief messages\" historyHeight=\"28rem\"\n    composer={<MessageComposer compact maxRows={6} sendOnEnter onSend={onSend} generating={generating} onStop={onStop} />}>\n    <Response from=\"user\">What needs to change?</Response>\n    <Response actions={<ResponseActions text=\"Name the owner and next step.\" />}>\n      <Reasoning variant=\"inline\" title=\"Reviewed the brief\" status=\"complete\">\n        <p>Checked the supplied scope and responsibilities.</p>\n      </Reasoning>\n      <p>Name the owner and next step.</p>\n    </Response>\n  </Chat>;\n}",
    usage: {
      use: ["A complete chat surface with a stable header and composer around scrolling messages.", "Supply Response elements as children and MessageComposer through the composer slot. Compact mode starts on one line, uses icon send and stop controls, and grows up to maxRows.", "Set historyHeight to reserve message space and let the frame fill its container width.", "Use actions for header controls and footer for supporting text below the composer.", "CSS-only markup provides the frame and native scrolling; following, draft growth, and send handling require React or application code."],
      avoid: ["Nesting another Conversation inside the supplied children.", "Using this component to connect a model, store messages, or execute tools.", "Using a fixed page overlay when the surrounding application needs to control placement."],
    },
    keyboard: [
      { keys: "Tab", does: "Moves through supplied header actions, the message history, and composer controls" },
      { keys: "Arrow keys, Page Up, Page Down", does: "Scrolls the focused history using native browser behavior" },
      { keys: "Enter, Space", does: "Activates Jump to latest and returns focus to the history" },
    ],
    a11y: ["The section is named by its visible title unless an accessible name override is supplied.", "conversationLabel names the scrollable message log independently of the frame.", "The built-in Conversation keeps its live region off and preserves the reader's position when they scroll back.", "The composer and its supporting footer remain outside the scrollable history.", "Native attributes and the forwarded ref reach the outer section. The application supplies accessible controls in the actions and composer slots."],
    aliases: ["AI chat", "Chat interface", "Chat panel", "Assistant chat", "Chat shell"],
  },
  {
    name: "conversation",
    title: "Conversation",
    description: "Keeps a scrollable message history at the latest response until the reader scrolls back.",
    category: "ai",
    classes: ["rs-conversation", "rs-conversation-viewport", "rs-conversation-content", "rs-conversation-footer"],
    css: ["components/conversation.css"],
    react: "components/conversation.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-conversation"><div class="rs-conversation-viewport" role="log" aria-label="Conversation" aria-live="off" tabindex="0" style="max-height:28rem"><div class="rs-conversation-content"><p>You: Summarize this document.</p><p>Assistant: The document has three sections.</p></div></div></div>`,
    example: "import { Conversation, MessageComposer, Response, ResponseActions, type ComposedMessage } from \"@noorddev/vlak-react\";\n\nexport function DocumentConversation({ onSend, generating, onStop }: {\n  onSend: (message: ComposedMessage) => void | Promise<void>;\n  generating: boolean;\n  onStop: () => void;\n}) {\n  return <>\n    <Conversation label=\"Document conversation\" maxHeight=\"28rem\">\n      <Response from=\"user\">Summarize this document.</Response>\n      <Response actions={<ResponseActions text=\"The document has three sections.\" />}>\n        <p>The document has three sections.</p>\n      </Response>\n    </Conversation>\n    <MessageComposer compact maxRows={6} sendOnEnter onSend={onSend} generating={generating} onStop={onStop} />\n  </>;\n}",
    usage: {
      use: ["A message history whose contents grow during a streamed response.", "Keep MessageComposer outside the scrollable history.", "Set autoScroll={false} to keep scrolling entirely manual.", "CSS-only markup provides native scrolling; following and the jump action require React or application code."],
      avoid: ["Putting an entire workbench in the message log.", "Using this component to fetch messages, render Markdown, or own a model connection."],
    },
    keyboard: [
      { keys: "Tab", does: "Focuses the scrollable log and its interactive contents" },
      { keys: "Arrow keys, Page Up, Page Down", does: "Scrolls the focused history using native browser behavior" },
      { keys: "Enter, Space", does: "Activates Jump to latest and returns focus to the history" },
    ],
    a11y: ["The message log has a supplied accessible label and a keyboard entry point.", "The log uses aria-live=off; use Response status announcements rather than announcing every streamed token.", "New content follows only while the reader is within 24px of the end. Scrolling back preserves the reading position.", "Jump to latest is a native 44px Button. Automatic scrolling is immediate and never moves focus.", "The ref and native attributes reach the outer div; maxHeight sets the inner scrollable history."],
    aliases: ["AI Elements Conversation", "Chat history", "Message log", "Auto scroll", "Chatbot"],
  },
  {
    name: "widget",
    title: "Widget",
    description: "A surface with a subtle 1px outline and 4px corners for React content and provider iframes, with attribution, data states, actions, and supporting context.",
    category: "ai",
    classes: ["rs-widget", "rs-widget-header", "rs-widget-icon", "rs-widget-heading", "rs-widget-title", "rs-widget-provider", "rs-widget-label", "rs-widget-content", "rs-widget-description", "rs-widget-state", "rs-widget-message", "rs-widget-actions", "rs-widget-footer", "rs-widget-embed"],
    css: ["components/widget.css"],
    react: "components/widget.tsx",
    registryDependencies: ["button"],
    snippet: '<section class="rs-widget" aria-labelledby="widget-title" data-status="ready"><header class="rs-widget-header"><div class="rs-widget-heading"><span class="rs-widget-title" id="widget-title">Recent files</span><div class="rs-widget-provider">Connected drive</div></div></header><div class="rs-widget-content"><p class="rs-widget-message">Project brief · Updated today</p></div><div class="rs-widget-footer">Supplied by the connected application</div></section>',
    example: "import { Button, Widget, WidgetEmbed, type WidgetStatus } from \"@noorddev/vlak-react\";\n\nexport function ConnectedWidgets({ status, onRetry, onOpenFiles, embedUrl }: {\n  status: WidgetStatus;\n  onRetry: () => void | Promise<void>;\n  onOpenFiles: () => void;\n  embedUrl: string;\n}) {\n  return <>\n    <Widget title=\"Recent files\" provider=\"Connected drive\" status={status} onRetry={onRetry}\n      emptyMessage=\"No files match this request.\" errorMessage=\"The drive could not be reached.\"\n      actions={<Button variant=\"subtle\" onClick={onOpenFiles}>Open files</Button>} footer=\"Updated just now\">\n      <p>Project brief · Ready for review</p>\n    </Widget>\n    <Widget title=\"Project board\" provider=\"Connected board\">\n      <WidgetEmbed title=\"Project board from the connected provider\" src={embedUrl} height={360} />\n    </Widget>\n  </>;\n}",
    usage: {
      use: ["Present application data and third-party results with the same title, provider, content, action, and footer slots.", "Map your integration's result to ready, loading, empty, or error. Supply rendered React content in children for the ready state.", "Use WidgetEmbed in children for a provider iframe. Supply its embed address, a descriptive title, and an explicit height; the default height is 320px.", "WidgetEmbed fills the available width and defaults to lazy loading, no-referrer, and a sandbox allowing scripts and forms. Set sandbox and allow for the provider's application-approved permissions.", "Show the source in provider and an update time or other context in footer.", "Use subtle Button actions and subtle ToggleGroup controls for supporting actions and visible view choices within a widget.", "Use onRetry for an application-owned reload. Update status when data arrives; the widget does not fetch data or infer success.", "CSS-only markup supplies the frame; data transitions and retry handling require React or application code."],
      avoid: ["Treating this surface as a connector, authentication flow, or tool execution engine.", "Passing untrusted markup or model-selected component names directly into rendered content.", "Assuming the parent stylesheet can style a cross-origin iframe's interior. Provider theming, messaging, and automatic height coordination belong to the application integration.", "Hiding consequential actions inside a widget without the application's normal confirmation step."],
    },
    keyboard: [
      { keys: "Tab", does: "Moves through provider links, ready content, supplied actions, and the error state's retry button" },
      { keys: "Enter, Space", does: "Activates the focused retry button or supplied native button" },
      { keys: "Tab inside an embed", does: "Follows the provider document's native focus order; its keyboard interactions are supplied by that document" },
    ],
    a11y: ["The section is named by its visible title unless an accessible name override is supplied.", "Empty and loading messages use a status region; failures use an alert. Progress remains outside a busy region so it can be announced promptly.", "A rejected retry remains readable and permits another attempt. Pending retries prevent duplicate activation, and changed data states invalidate stale retry results.", "The decorative icon is hidden from assistive technology. Provider content and supplied actions remain in the normal reading and tab order.", "WidgetEmbed requires a title that identifies the embedded document. The provider supplies the document's accessible content and keyboard behavior.", "Native section attributes, className, style, and the section ref are forwarded. WidgetEmbed forwards native iframe attributes, permission overrides, and the iframe ref. The application supplies accessible content and controls for each integration."],
    aliases: ["AI widget", "Tool result card", "Connected service widget", "Integration widget", "Generative UI", "WidgetEmbed", "Embedded widget", "iframe"],
  },
  {
    name: "response-actions",
    title: "Response actions",
    description: "Four subtle 44px icon controls for copying, reading aloud, rating through a combined feedback menu, and sharing an assistant response.",
    category: "ai",
    classes: ["rs-response-actions-bar", "rs-response-actions-selected", "rs-response-actions-icon", "rs-response-actions-status", "rs-response-actions-menu"],
    css: ["components/response-actions.css"],
    react: "components/response-actions.tsx",
    registryDependencies: ["button", "dropdown-menu"],
    snippet: '<div class="rs-response-actions-bar" role="group" aria-label="Response actions"><button class="rs-btn-subtle rs-btn-icon" type="button" aria-label="Copy response" title="Copy response"><svg class="rs-response-actions-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><rect x="8" y="8" width="12" height="13" rx="1"/><path d="M16 8V3H4v13h4"/></svg></button><button class="rs-btn-subtle rs-btn-icon" type="button" aria-label="Read aloud" title="Read aloud"><svg class="rs-response-actions-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="m11 4-6 5H2v6h3l6 5V4ZM15 8a6 6 0 0 1 0 8"/></svg></button><button class="rs-btn-subtle rs-btn-icon" type="button" aria-label="Rate response" title="Rate response" aria-haspopup="menu" aria-expanded="false"><svg class="rs-response-actions-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M1 7h3v7H1zM4 7l3-5c1.5 0 2 1 1 4h4a1 1 0 0 1 1 1l-1.5 6a1 1 0 0 1-1 .8H4M23 17h-3v-7h3zM20 17l-3 5c-1.5 0-2-1-1-4h-4a1 1 0 0 1-1-1l1.5-6a1 1 0 0 1 1-.8H20"/></svg></button><button class="rs-btn-subtle rs-btn-icon" type="button" aria-label="Share response" title="Share response"><svg class="rs-response-actions-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M12 16V2m-5 5 5-5 5 5M5 12H3v10h18V12h-2"/></svg></button><span class="rs-response-actions-status" role="status" aria-live="polite" aria-atomic="true"></span></div>',
    example: "\"use client\";\nimport { useState } from \"react\";\nimport { Response, ResponseActions, type ResponseFeedback } from \"@noorddev/vlak-react\";\n\nexport function AnswerActions() {\n  const [feedback, setFeedback] = useState<ResponseFeedback>(null);\n  const answer = \"The brief now names one owner and one next step.\";\n  return <Response actions={<ResponseActions text={answer} feedback={feedback} onFeedback={setFeedback} />}>\n    <p>{answer}</p>\n  </Response>;\n}",
    usage: {
      use: ["Place in the actions slot of Response and supply the same plain text the reader sees.", "Each action composes a subtle icon Button. Muted text turns to ink on hover while the surface stays transparent.", "The combined feedback icon opens helpful and unhelpful choices. Selecting the checked choice again clears it.", "Use onFeedback to persist positive, negative, or cleared feedback. A rejected promise keeps the previous selection available for retry.", "Use feedback for controlled selection or defaultFeedback for an initial local selection.", "Supply onShare for an application-owned share flow. Otherwise the browser shares the text or copies it when native sharing is unavailable.", "Read aloud uses browser speech only after activation. onReadingChange can coordinate an avatar with narration.", "CSS-only markup supplies named controls; clipboard, speech, the feedback menu, and sharing require React or application code."],
      avoid: ["Adding copyText to the same Response, which would duplicate its copy control.", "Assuming local feedback has been stored on a server without supplying onFeedback.", "Passing raw markup as text or automatically starting narration when a message appears."],
    },
    keyboard: [
      { keys: "Tab", does: "Moves through the available copy, narration, feedback, and share controls" },
      { keys: "Enter, Space", does: "Activates the focused action or feedback choice; choosing the checked feedback item again clears it" },
      { keys: "Arrow Down, Arrow Up", does: "Opens feedback on the first or last choice, then moves between choices" },
      { keys: "Home, End", does: "Moves to the first or last feedback choice" },
      { keys: "Escape", does: "Closes the feedback menu and returns focus to its trigger" },
      { keys: "Tab", does: "Closes the feedback menu and moves focus to the next action" },
    ],
    a11y: ["Every icon button has a readable name and title, a 44px target, and a visible focus outline.", "One Rate response trigger exposes its expanded menu state. Helpful and unhelpful menu choices expose aria-checked and remain mutually exclusive.", "The menu moves focus between choices and returns focus on selection or Escape. Outside interaction dismisses it without stealing focus.", "A polite, atomic status region announces completed actions and recoverable errors. Clipboard success is reported only after the write resolves.", "Read aloud is disabled when browser speech is unavailable and becomes Stop reading while this response is narrated. Replacing the text or unmounting stops this component's narration.", "Pending asynchronous actions prevent duplicate activation. The feedback trigger remains focusable with aria-disabled while saving. Replacing the response text closes its menu and invalidates stale results.", "The group accepts native div attributes, children for extra actions, className, style, and a forwarded div ref."],
    aliases: ["AI response actions", "Message toolbar", "Read aloud", "Message feedback", "Thumbs up", "Thumbs down"],
  },
];
