import type { VlakComponent } from "./schema";

export const electronicsComponents: VlakComponent[] = [
  {
    name: "pad-inspector", title: "Pad inspector", category: "electronics",
    description: "Circuit-board pad selection with supplied footprint references, net and layer records, pad types and a dimension table with explicit units.",
    classes: ["rs-pad-inspector", "rs-pad-inspector-legend", "rs-pad-inspector-label", "rs-pad-inspector-control", "rs-pad-inspector-properties", "rs-pad-inspector-term", "rs-pad-inspector-detail", "rs-pad-inspector-table", "rs-pad-inspector-caption", "rs-pad-inspector-cell", "rs-pad-inspector-note"],
    css: ["components/pad-inspector.css"], react: "components/pad-inspector.tsx", registryDependencies: ["select", "dropdown-menu"],
    snippet: '<fieldset class="rs-pad-inspector"><legend class="rs-pad-inspector-legend">Connector pads</legend><div class="rs-pad-inspector-label"><span id="pad-choice-label">Pad</span><div class="rs-select rs-select-fluid rs-pad-inspector-control"><button type="button" class="rs-dropdown" role="combobox" aria-labelledby="pad-choice-label" aria-expanded="false" aria-haspopup="listbox">J1 / Pad 1 · pad-a</button></div></div><dl class="rs-pad-inspector-properties"><div><dt class="rs-pad-inspector-term">Net</dt><dd class="rs-pad-inspector-detail">Supply</dd></div><div><dt class="rs-pad-inspector-term">Layers</dt><dd class="rs-pad-inspector-detail">Front copper, Back copper</dd></div></dl><table class="rs-pad-inspector-table"><caption class="rs-pad-inspector-caption">Supplied geometry</caption><thead><tr><th class="rs-pad-inspector-cell" scope="col">Dimension</th><th class="rs-pad-inspector-cell" scope="col">Value</th><th class="rs-pad-inspector-cell" scope="col">Unit</th></tr></thead><tbody><tr><th class="rs-pad-inspector-cell" scope="row">Pad diameter</th><td class="rs-pad-inspector-cell">1.80</td><td class="rs-pad-inspector-cell">mm</td></tr></tbody></table></fieldset>',
    example: `import { PadInspector } from "@noorddev/vlak-react";

<PadInspector label="Connector pads" name="pad" boardLabel="Example board, revision C" defaultValue="pad-a" pads={[
  { id: "pad-a", reference: "J1", number: "1", net: "Supply", layers: ["Front copper", "Back copper"], type: "Through hole", shape: "Circle", geometry: [
    { id: "diameter", label: "Pad diameter", value: "1.80", unit: "mm" },
    { id: "drill", label: "Drill diameter", value: "0.90", unit: "mm" },
  ] },
  { id: "pad-b", reference: "J1", number: "2", net: "Return", layers: ["Front copper"], type: "Surface mount", shape: "Rectangle" },
]} />`,
    usage: { use: ["Inspecting a bounded collection of pad records supplied by a board editor or manufacturing export.", "Supply unique, non-empty pad ids and unique measurement ids within each pad. Pad numbers may repeat; ids identify the actual records.", "Use value and onValueChange for host-owned selection and board or schematic cross-highlighting. No connectivity or geometry calculation runs in the component.", "Supply geometry values as strings to preserve significant figures. Null fields remain explicitly missing; an empty layers array means none recorded."], avoid: ["Inferring that a missing net means unconnected, a missing drill means no hole, or an unknown layer list means every copper layer.", "Treating selection as a board edit or inferring dimensions from the shape name."] },
    keyboard: [{ keys: "Tab", does: "Focuses the Vlak pad selector." }, { keys: "Arrow keys, Home, End", does: "Opens or moves through available pad choices." }, { keys: "Enter, Space", does: "Chooses the focused pad. Controlled selection waits for a host update." }, { keys: "Escape", does: "Closes the selector and keeps the current choice." }],
    a11y: ["A fieldset legend names the inspector. Pad choices include their record id, so repeated pad numbers remain distinguishable.", "Vlak Select supplies the 44px trigger, keyboard listbox and disabled choices. Pad properties use a description list and dimensions use a captioned table with row and column headers.", "Missing records, unavailable selections, non-finite measurements and missing units have explicit text. Numeric zero and string precision are retained.", "Native form association and reset are supported. Read-only valid selection remains submittable, while disabled selection is omitted.", "The fieldset ref, native attributes, className and style pass through."],
    aliases: ["Footprint pad", "Circuit board pad properties", "Pad geometry", "Copper pad inspector", "Board pad selector"],
  },
  {
    name: "design-rule-results", title: "Design rule results", category: "electronics",
    description: "Supplied board-check violations with severity and status filters, object and location details, and host-confirmed selection and resolution actions.",
    classes: ["rs-design-rule-results", "rs-design-rule-results-legend", "rs-design-rule-results-filters", "rs-design-rule-results-label", "rs-design-rule-results-control", "rs-design-rule-results-list", "rs-design-rule-results-item", "rs-design-rule-results-selected", "rs-design-rule-results-title", "rs-design-rule-results-properties", "rs-design-rule-results-term", "rs-design-rule-results-detail", "rs-design-rule-results-actions", "rs-design-rule-results-action", "rs-design-rule-results-note"],
    css: ["components/design-rule-results.css"], react: "components/design-rule-results.tsx", registryDependencies: ["select", "button"],
    snippet: '<fieldset class="rs-design-rule-results"><legend class="rs-design-rule-results-legend">Reported design rules</legend><p class="rs-design-rule-results-note">Synthetic check run 042</p><ul class="rs-design-rule-results-list"><li class="rs-design-rule-results-item"><p class="rs-design-rule-results-title">Copper clearance</p><dl class="rs-design-rule-results-properties"><div><dt class="rs-design-rule-results-term">Severity</dt><dd class="rs-design-rule-results-detail">Error</dd></div><div><dt class="rs-design-rule-results-term">Confirmed status</dt><dd class="rs-design-rule-results-detail">Open</dd></div><div><dt class="rs-design-rule-results-term">Layer</dt><dd class="rs-design-rule-results-detail">Front copper</dd></div><div><dt class="rs-design-rule-results-term">Location</dt><dd class="rs-design-rule-results-detail">X: 24.5, Y: 18; unit: mm</dd></div></dl></li></ul></fieldset>',
    example: `import { DesignRuleResults } from "@noorddev/vlak-react";

<DesignRuleResults label="Reported design rules" runLabel="Synthetic check run 042" violations={[
  { id: "clearance-1", title: "Copper clearance", severity: "error", status: "open", rule: "Supplied clearance rule", layer: "Front copper", net: "Supply", location: { x: 24.5, y: 18, unit: "mm" }, objects: ["J1 pad 1", "Track 17"] },
  { id: "label-2", title: "Silkscreen overlap", severity: "warning", status: "excluded", layer: "Front silkscreen", objects: ["J1 reference", "J1 outline"] },
]} />`,
    usage: { use: ["Reviewing a bounded set of results supplied by a board design-rule checker.", "Supply unique result ids, the confirmed severity and status, and any available layer, net, object and location records. Null severity or status means unknown.", "onSelect requests host selection; selectedId confirms it. onResolve requests resolution of an open result unless canResolve is false. Pending and disabled records cannot invoke actions.", "Use filter and onFilterChange for host-owned filters; uncontrolled filters start from defaultFilter. Named filters submit as name.severity and name.status."], avoid: ["Treating an action click as a resolved board defect or treating an excluded result as resolved.", "Inferring that an empty result array means a check ran or passed. The component does not run rules, edit the board or invent clearance limits."] },
    keyboard: [{ keys: "Tab", does: "Moves through the Vlak filter selectors and available action buttons." }, { keys: "Arrow keys, Home, End", does: "Navigates a focused filter's choices." }, { keys: "Enter, Space", does: "Chooses a filter or requests the focused selection or resolution action." }, { keys: "Escape", does: "Closes an open filter selector." }],
    a11y: ["A fieldset legend names the results. Vlak Select and Button provide shared control paint, focus states and 44px targets.", "Visible description lists distinguish reported severity, confirmed status, layer, net and coordinate units. Action names include the unique result id and title.", "The polite count distinguishes filtered results from the complete supplied set. Empty results and unmatched filters use different messages.", "Selected records use a full-surface fill and Selected text. Pending actions keep confirmed data readable and disable the action controls.", "Native form reset restores uncontrolled filters; controlled filters remain with the application. Disabled fieldsets omit filter values and block actions.", "The fieldset ref, native attributes, className and style pass through."],
    aliases: ["Board rule check", "Circuit board violations", "Clearance results", "Design-rule review", "Board verification results"],
  },
];
