"use client";
import { useCallback, useState, type ComponentType } from "react";
import { Button, ButtonGroup, Checkpoint, ConversationDownload, GeneratedImage, Plan, Response, ResponseActions, ResponseBranch, ResponseEditor, Shimmer, Suggestion, Suggestions, Task, ThoughtSteps, WorkQueue } from "@noorddev/vlak-react";

const stack = { display: "grid", gap: 24, width: "100%", minWidth: 0 } as const;
function PlanPreview() { const [approved, setApproved] = useState(false); return <Plan title="Review plan" description="Check the supplied brief before proposing changes." statusLabel={approved ? "Approved locally" : "Proposed"} actions={<Button variant="subtle" disabled={approved} onClick={() => setApproved(true)}>{approved ? "Approved" : "Approve plan"}</Button>}><ol><li>Read the current scope and responsibilities.</li><li>Flag decisions without an owner.</li><li>Prepare a draft for review.</li></ol></Plan>; }
function TaskPreview() { const [complete, setComplete] = useState(false); return <div style={stack}><Task title="Read project sources" status={complete ? "complete" : "streaming"} items={[{ id: "brief", content: "Read the launch brief", state: "complete", file: "launch-brief.md" }, { id: "owners", content: "Compare responsibilities", state: complete ? "complete" : "active", file: "owners.md" }]} /><Button variant="subtle" onClick={() => setComplete(value => !value)}>{complete ? "Replay task" : "Mark complete"}</Button></div>; }
function ThoughtStepsPreview() { const [step, setStep] = useState(1); return <div style={stack}><ThoughtSteps defaultOpen status={step < 2 ? "streaming" : "complete"} title="Review summary" steps={[{ id: "read", title: "Read the supplied brief", state: "complete", description: "Found the proposed scope and three responsibilities.", sources: <a className="rs-link" href="/ai/widgets/">Project source example</a> }, { id: "compare", title: "Compare responsibilities", state: step < 2 ? "active" : "complete", content: step < 2 ? "Checking the owner of each decision." : "Two decisions need an owner." }]} /><Button variant="subtle" onClick={() => setStep(value => value < 2 ? 2 : 1)}>{step < 2 ? "Complete the review" : "Replay review"}</Button></div>; }
function CheckpointPreview() { const [restored, setRestored] = useState(false); const restore = useCallback(async () => { setRestored(true); }, []); return <div style={stack}><Checkpoint label="Before editing the brief" onRestore={restore} /><p role="status">{restored ? "The saved draft is restored in this local example." : "A saved point in the conversation."}</p></div>; }
function SuggestionsPreview() { const [draft, setDraft] = useState(""); return <div style={stack}><Suggestions wrap><Suggestion value="Review the launch brief" onSelect={setDraft}>Review brief</Suggestion><Suggestion value="Find decisions without owners" onSelect={setDraft}>Find missing owners</Suggestion><Suggestion value="Prepare a short summary" onSelect={setDraft}>Summarize</Suggestion></Suggestions><p role="status">{draft || "Select a suggested prompt."}</p></div>; }
export function WorkQueuePreview({ label = "Work queue" }: { label?: string } = {}) { const [done, setDone] = useState(false); const [queued, setQueued] = useState(true); return <WorkQueue label={label} onItemCheckedChange={(_section, _item, checked) => setDone(checked)} sections={[{ id: "messages", title: "Queued prompts", items: queued ? [{ id: "prompt", content: "Prepare a review draft", description: "Waiting for the current reply.", actions: <Button variant="subtle" onClick={() => setQueued(false)}>Remove</Button> }] : [] }, { id: "todos", title: "Next steps", items: [{ id: "owner", content: "Name the owner for each decision", completed: done }] }]} />; }
function ShimmerPreview() { const [active, setActive] = useState(true); return <div style={stack}><Shimmer active={active}>Reading the launch brief…</Shimmer><ButtonGroup><Button variant="subtle" aria-pressed={active} onClick={() => setActive(true)}>Active</Button><Button variant="subtle" aria-pressed={!active} onClick={() => setActive(false)}>Complete</Button></ButtonGroup></div>; }
function GeneratedImagePreview() { return <GeneratedImage alt="A monochrome diagram of three connected workflow steps" width={480} height={160} image={{ mediaType: "image/svg+xml", base64: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0ODAiIGhlaWdodD0iMTYwIiB2aWV3Qm94PSIwIDAgNDgwIDE2MCI+PHJlY3Qgd2lkdGg9IjQ4MCIgaGVpZ2h0PSIxNjAiIGZpbGw9IiNmN2Y3ZjciLz48ZyBmaWxsPSJub25lIiBzdHJva2U9IiM3Nzc3NzciPjxyZWN0IHg9IjMwIiB5PSI1MCIgd2lkdGg9IjEwMCIgaGVpZ2h0PSI2MCIgcng9IjQiLz48cmVjdCB4PSIxOTAiIHk9IjUwIiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjYwIiByeD0iNCIvPjxyZWN0IHg9IjM1MCIgeT0iNTAiIHdpZHRoPSIxMDAiIGhlaWdodD0iNjAiIHJ4PSI0Ii8+PHBhdGggZD0iTTEzMCA4MGg2MG0xMDAgMGg2MCIvPjwvZz48L3N2Zz4=" }} />; }
function ConversationExportPreview() { return <div style={stack}><Response from="user">Review the launch brief.</Response><Response>The brief has two decisions without owners.</Response><ConversationDownload title="Project review" messages={[{ role: "user", content: "Review the launch brief." }, { role: "assistant", parts: [{ type: "text", text: "The brief has two decisions without owners." }, { type: "file", filename: "launch-brief.md" }] }]} /></div>; }
export function ResponseEditorPreview({ label = "Edit message" }: { label?: string } = {}) {
  const [editing, setEditing] = useState(true);
  const [text, setText] = useState("Review the brief and identify missing owners.");
  const [versions, setVersions] = useState([{ id: "original", text: "Two decisions need an owner." }]);
  const [selected, setSelected] = useState("original");
  const regenerate = () => { const id = `version-${versions.length}`; setVersions(current => [...current, { id, text: "Name an owner for the launch date and review checklist." }]); setSelected(id); };
  return <div style={stack}>{editing ? <ResponseEditor label={label} text={text} onSave={async value => { setText(value); setEditing(false); regenerate(); }} onCancel={() => setEditing(false)} saveLabel="Save and regenerate" /> : <Response from="user" actions={<Button variant="subtle" onClick={() => setEditing(true)}>Edit message</Button>}>{text}</Response>}<ResponseBranch value={selected} onValueChange={setSelected} branches={versions.map(version => ({ id: version.id, content: <Response actions={<ResponseActions text={version.text}><Button variant="subtle" onClick={regenerate}>Regenerate</Button></ResponseActions>}>{version.text}</Response> }))} /><p>This local example uses recorded response alternatives.</p></div>;
}
export const aiWorkPatternPreviews: Record<string, ComponentType> = {
  plan: PlanPreview,
  task: TaskPreview,
  "thought-steps": ThoughtStepsPreview,
  checkpoint: CheckpointPreview,
  suggestions: SuggestionsPreview,
  "work-queue": WorkQueuePreview,
  shimmer: ShimmerPreview,
  "generated-image": GeneratedImagePreview,
  "conversation-export": ConversationExportPreview,
  "response-editor": ResponseEditorPreview
};
