"use client";

import * as React from "react";
import { Button, Icon, Input, NativeSelect, NumberField, Progress, Select, Textarea, ToggleGroup } from "@noorddev/vlak-react";
import type { IconName } from "@noorddev/vlak-react";
import { cancelIOSMotion, iosLaunchOrigin, runIOSMotion } from "./ios-motion";
import { IOSCamera } from "./ios-camera";
import { IOSMaps } from "./ios-maps";
import { IOSPhotos } from "./ios-photos";
import { IOSClock } from "./ios-clock";
import { IOSCalendar } from "./ios-calendar";
import type { IOSCalendarEvent } from "./ios-calendar";
import { IOSSearchField } from "./ios-search-field";
import { IOSAppGlyph } from "./ios-app-glyph";
import { AndroidAppGlyph } from "./android-app-glyph";
import { PlatformGlyph } from "./platform-glyph";
import type { PlatformGlyphName } from "./platform-glyph";
import { DeviceFrame, StatusSignals } from "./device-chrome";
import { AndroidSettings, androidSettingsTitles } from "./android-settings";
import { PlatformRange as Slider, PlatformSwitch as Switch } from "./platform-controls";
import { trackSiteEvent } from "@/lib/site-analytics";

import { deviceProfiles } from "./device-profiles";
import type { DeviceProfile, Platform } from "./device-profiles";
type AppId = "home" | "phone" | "contacts" | "messages" | "mail" | "calendar" | "clock" | "notes" | "photos" | "camera" | "files" | "calculator" | "weather" | "maps" | "music" | "browser" | "settings";
type App = { id: Exclude<AppId, "home">; name: string; icon: IconName };
const apps: App[] = [
  { id: "phone", name: "Phone", icon: "phone" }, { id: "messages", name: "Messages", icon: "message" }, { id: "mail", name: "Mail", icon: "mail" }, { id: "calendar", name: "Calendar", icon: "calendar" },
  { id: "clock", name: "Clock", icon: "clock" }, { id: "notes", name: "Notes", icon: "edit" }, { id: "photos", name: "Photos", icon: "image" }, { id: "camera", name: "Camera", icon: "camera" },
  { id: "files", name: "Files", icon: "folder" }, { id: "calculator", name: "Calculator", icon: "grid" }, { id: "weather", name: "Weather", icon: "sun" }, { id: "maps", name: "Maps", icon: "map" },
  { id: "music", name: "Music", icon: "music" }, { id: "browser", name: "Browser", icon: "globe" }, { id: "contacts", name: "Contacts", icon: "users" }, { id: "settings", name: "Settings", icon: "settings" },
];
const dockIds: AppId[] = ["phone", "messages", "browser", "music"];
const photosInitial = [{ id: "photo-1", name: "Print studies", src: "/interfaces/threads/posters-v2.jpg", favorite: false }, { id: "photo-2", name: "The press room", src: "/interfaces/threads/press-sheet-v2.jpg", favorite: false }, { id: "photo-3", name: "At the table", src: "/interfaces/food/de-buren-v2.jpg", favorite: false }];
const tones = [[261.63, 329.63, 392, 329.63, 293.66, 349.23, 440, 349.23], [220, 261.63, 329.63, 392, 329.63, 261.63, 246.94, 293.66], [293.66, 369.99, 440, 493.88, 440, 369.99, 329.63, 246.94]];
const trackNames = ["Paper morning", "Quiet current", "A little further"];
const bookmarks = [{ address: "studio.local", title: "Studio journal", text: "Small observations from a working studio. Today: fresh paper, a careful proof, and a little room to think." }, { address: "guide.local", title: "A slower morning", text: "Open the window. Put the kettle on. Write down one thing you want to make room for today." }, { address: "vlak.local", title: "Made with Vlak", text: "Paper, ink, hairlines, and useful controls. This page is bundled with the prototype and opens entirely on your device." }];
const time = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;
function calculate(expression: string): string {
  const input = expression.replaceAll("−", "-").replaceAll("×", "*").replaceAll("÷", "/");
  let cursor = 0;
  function number(): number {
    const match = input.slice(cursor).match(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)/);
    if (!match) throw new Error("Incomplete");
    cursor += match[0].length; return Number(match[0]);
  }
  function term(): number {
    let value = number();
    while (input[cursor] === "*" || input[cursor] === "/") { const operator = input[cursor++]; const right = number(); value = operator === "*" ? value * right : value / right; }
    return value;
  }
  try {
    let result = term();
    while (input[cursor] === "+" || input[cursor] === "-") { const operator = input[cursor++]; const right = term(); result = operator === "+" ? result + right : result - right; }
    if (cursor !== input.length) return "Incomplete";
    return Number.isFinite(result) ? String(Number(result.toPrecision(12))) : "Cannot divide by zero";
  } catch { return "Incomplete"; }
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="mo-field"><span>{label}</span>{children}</div>; }
function SystemIcon({ name }: { name: IconName }) {
  const glyphs: Partial<Record<IconName, PlatformGlyphName>> = { wifi: "wifi", link: "bluetooth", send: "airplane", globe: "cellular", power: "battery", lock: "orientation-lock", unlock: "orientation-unlock" };
  const glyph = glyphs[name];
  return glyph ? <PlatformGlyph name={glyph} /> : <Icon name={name} size={24} />;
}

function SearchField({ platform, label, placeholder, value, onValueChange }: { platform: Platform; label: string; placeholder: string; value: string; onValueChange: (value: string) => void }) {
  return platform === "ios" ? <IOSSearchField label={label} placeholder={placeholder} value={value} onValueChange={onValueChange} /> : <Input type="search" className="mo-app-search" aria-label={label} placeholder={placeholder} value={value} onChange={event => onValueChange(event.target.value)} />;
}

export function Board({ platform = "ios" }: { platform?: Platform }) {
  const profiles = deviceProfiles.filter(device => device.platform === platform);
  const [deviceId, setDeviceId] = React.useState(profiles[0]!.id);
  const [expanded, setExpanded] = React.useState(false);
  const [inspectionAngle, setInspectionAngle] = React.useState<number | null>(null);
  const prepareFold = React.useRef<(() => void) | null>(null);
  const [rotated, setRotated] = React.useState(false);
  const [narrow, setNarrow] = React.useState(false);
  const [liveOverride, setLiveOverride] = React.useState<boolean | null>(null);
  React.useEffect(() => {
    const query = matchMedia("(max-width: 640px)");
    const update = () => setNarrow(query.matches);
    update(); query.addEventListener("change", update);
    return () => query.removeEventListener("change", update);
  }, []);
  const live = narrow && (liveOverride ?? true);
  const device = profiles.find(item => item.id === deviceId) ?? profiles[0]!;
  const isDuo = platform === "ios" && device.id === "iphone-duo";
  React.useEffect(() => {
    if (!isDuo) return;
    trackSiteEvent("duo_open");
  }, [isDuo]);
  React.useEffect(() => {
    if (!isDuo) return;
    trackSiteEvent(expanded ? "inner_screen" : "outer_screen");
  }, [expanded, isDuo]);
  return <section className="mo mo-single" aria-label={`${platform === "ios" ? "iOS" : "Android"} operating system workspace`}>
    <header className="mo-workspace-header"><div><strong>Your phone, your way</strong><span>Everyday apps, in Vlak</span></div><div className="mo-device-controls"><NativeSelect aria-label="Device" value={device.id} onChange={event => { if (platform === "ios") cancelIOSMotion(); setInspectionAngle(null); setDeviceId(event.target.value); }}>{profiles.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</NativeSelect>{device.expanded && <Button variant="ghost" aria-pressed={expanded} onClick={() => { if (platform === "ios") cancelIOSMotion(); trackSiteEvent("fold_transition"); prepareFold.current?.(); setLiveOverride(false); setInspectionAngle(null); setExpanded(value => !value); }}>{expanded ? "Fold display" : "Open display"}</Button>}{device.expanded && <Button variant="ghost" aria-pressed={inspectionAngle !== null} onClick={() => { if (platform === "ios") cancelIOSMotion(); trackSiteEvent("fold_transition"); prepareFold.current?.(); setLiveOverride(false); setExpanded(true); setInspectionAngle(value => value === null ? 110 : null); }}>{inspectionAngle === null ? "Inspect fold" : "Return to app"}</Button>}<Button variant="ghost" aria-label="Rotate device" aria-pressed={rotated} onClick={() => { if (platform === "ios") cancelIOSMotion(); setLiveOverride(false); setInspectionAngle(null); setRotated(value => !value); }}><Icon name="refresh" />Rotate</Button>{narrow && <Button variant="ghost" onClick={() => { if (platform === "ios") cancelIOSMotion(); setInspectionAngle(null); setLiveOverride(!live); }}>{live ? "View device" : "Use phone"}</Button>}</div></header>
    {inspectionAngle !== null && <div className="mo-fold-tools"><label htmlFor="mo-hinge-angle">Hinge angle</label><input id="mo-hinge-angle" aria-label="Hinge angle" type="range" min="0" max="180" step="1" value={inspectionAngle} onChange={event => { if (platform === "ios") cancelIOSMotion(); setInspectionAngle(Number(event.target.value)); }} /><output htmlFor="mo-hinge-angle">{inspectionAngle}°</output><span>Adjust the hinge, then return to the app.</span></div>}
    <div className="mo-stage"><Device platform={platform} device={device} expanded={expanded && Boolean(device.expanded)} rotated={rotated} live={live} prepareFold={prepareFold} inspectionAngle={inspectionAngle} /></div>
    <footer className="mo-workspace-footer"><span>Local apps and sample data. Your work stays here as you change devices.</span></footer>
  </section>;
}

function Device({ platform, device, expanded, rotated, live, prepareFold, inspectionAngle }: { platform: Platform; device: DeviceProfile; expanded: boolean; rotated: boolean; live: boolean; prepareFold: React.RefObject<(() => void) | null>; inspectionAngle: number | null }) {
  React.useEffect(() => () => { if (platform === "ios") cancelIOSMotion(); }, [platform]);
  const [app, setApp] = React.useState<AppId>("home");
  const [screen, setScreenRaw] = React.useState("");
  const launchOrigins = React.useRef<Partial<Record<AppId, ReturnType<typeof iosLaunchOrigin>>>>({});
  function setScreen(next: string) {
    if (platform !== "ios" || next === screen) { if (platform === "ios") cancelIOSMotion(); setScreenRaw(next); return; }
    const sheet = ["new", "compose", "recipients", "edit-contact"];
    runIOSMotion(sheet.includes(next) ? "sheet" : sheet.includes(screen) ? "dismiss" : next ? "push" : "back", () => setScreenRaw(next));
  }
  const [overlay, setOverlay] = React.useState<"" | "quick" | "notifications" | "recents" | "library">("");
  const [recent, setRecent] = React.useState<AppId[]>([]);
  const [search, setSearch] = React.useState("");
  const [appearance, setAppearance] = React.useState("system");
  const [textSize, setTextSize] = React.useState(100);
  const [wifi, setWifi] = React.useState(true);
  const [bluetooth, setBluetooth] = React.useState(true);
  const [lowPower, setLowPower] = React.useState(false);
  const [focusMode, setFocusMode] = React.useState(false);
  const [airplaneMode, setAirplaneMode] = React.useState(false);
  const [cellular, setCellular] = React.useState(true);
  const [orientationLocked, setOrientationLocked] = React.useState(true);
  const [network, setNetwork] = React.useState("Studio network");
  const [brightness, setBrightness] = React.useState(80);
  const [notice, setNotice] = React.useState("Sample system · Changes stay in this tab");
  const [notifications, setNotifications] = React.useState([{ id: "welcome", title: "Welcome home", text: "Your local phone is ready to explore." }, { id: "note", title: "A note from the studio", text: "The autumn proofs are on the table." }]);
  const [contacts, setContacts] = React.useState([{ id: "mara", name: "Mara Vos", phone: "+31 20 555 0101" }, { id: "elias", name: "Elias Noor", phone: "+31 20 555 0102" }]);
  const [contactName, setContactName] = React.useState(""); const [contactPhone, setContactPhone] = React.useState(""); const [dial, setDial] = React.useState(""); const [call, setCall] = React.useState("");
  const [conversation, setConversation] = React.useState("mara");
  const [messages, setMessages] = React.useState([{ id: "msg-1", contact: "mara", mine: false, text: "The proofs look good. Shall we meet at the studio?" }, { id: "msg-2", contact: "elias", mine: false, text: "I’ll bring the new paper samples." }]); const [messageDraft, setMessageDraft] = React.useState("");
  const [mails, setMails] = React.useState([{ id: "mail-1", from: "Mara", subject: "A small update", body: "The final proofs are ready. I left a copy on your desk. Let me know what you think.", sent: false }, { id: "mail-2", from: "Studio 03", subject: "Friday in the studio", body: "A shared lunch and a little time to review the week’s work. Bring something you want to show.", sent: false }]);
  const [mailTo, setMailTo] = React.useState(""); const [mailSubject, setMailSubject] = React.useState(""); const [mailBody, setMailBody] = React.useState("");
  const [date, setDate] = React.useState("2026-09-08"); const [events, setEvents] = React.useState<IOSCalendarEvent[]>([{ id: "event-1", date: "2026-09-08", time: "10:30", title: "Studio review" }, { id: "event-2", date: "2026-09-08", time: "13:00", title: "Lunch with Mara" }]); const [eventTitle, setEventTitle] = React.useState(""); const [eventTime, setEventTime] = React.useState("15:00");
  const [clockTab, setClockTab] = React.useState("timer"); const [timerSeconds, setTimerSeconds] = React.useState(60); const [remaining, setRemaining] = React.useState(60); const [timerRunning, setTimerRunning] = React.useState(false); const timerDeadline = React.useRef(0);
  const [stopwatchRunning, setStopwatchRunning] = React.useState(false); const [elapsed, setElapsed] = React.useState(0); const stopwatchBase = React.useRef(0); const [laps, setLaps] = React.useState<number[]>([]); const [alarmTime, setAlarmTime] = React.useState("07:30"); const [alarmOn, setAlarmOn] = React.useState(false);
  const [notes, setNotes] = React.useState([{ id: "note-1", title: "A little room to think", body: "Paper samples\nAutumn poster proofs\nTake the long way home" }, { id: "note-2", title: "Things to make", body: "A small edition of prints. A useful shelf. More time." }]); const [noteTitle, setNoteTitle] = React.useState(""); const [noteBody, setNoteBody] = React.useState("");
  const [photos, setPhotos] = React.useState(photosInitial); const [files, setFiles] = React.useState([{ id: "file-1", name: "welcome.txt", body: "Welcome to your local phone. Files are created and downloaded in this browser." }]); const [fileName, setFileName] = React.useState(""); const [fileBody, setFileBody] = React.useState("");
  const [expression, setExpression] = React.useState("0"); const [calculated, setCalculated] = React.useState(false); const [city, setCity] = React.useState("Alkmaar"); const [weatherUnit, setWeatherUnit] = React.useState("c");
  const [destination, setDestination] = React.useState("station"); const [routing, setRouting] = React.useState(false); const [routeStep, setRouteStep] = React.useState(0); const [mapZoom, setMapZoom] = React.useState(1);
  const [track, setTrack] = React.useState(0); const [musicPlaying, setMusicPlaying] = React.useState(false); const [volume, setVolume] = React.useState(35); const [beat, setBeat] = React.useState(0); const audio = React.useRef<AudioContext | null>(null); const gain = React.useRef<GainNode | null>(null); const audioMounted = React.useRef(true); const audioRequest = React.useRef(0);
  const [address, setAddress] = React.useState("studio.local"); const [browserPage, setBrowserPage] = React.useState("studio.local"); const [browserError, setBrowserError] = React.useState("");
  const gesture = React.useRef<{ x: number; y: number; time: number } | null>(null); const gestureHandled = React.useRef(false);
  const savedScreens = React.useRef<Partial<Record<AppId, string>>>({});
  const sequence = React.useRef(0); const id = React.useId(); const appTitle = React.useRef<HTMLHeadingElement>(null); const overlayTrigger = React.useRef<HTMLElement | null>(null); const formId = `${id}-form`;
  const previousScreen = React.useRef({ app, screen, call });
  React.useEffect(() => {
    const previous = previousScreen.current;
    previousScreen.current = { app, screen, call };
    if (!overlay && (previous.app !== app || previous.screen !== screen || previous.call !== call)) appTitle.current?.focus({ preventScroll: true });
  }, [app, screen, call, overlay]);
  const unique = (prefix: string) => `${prefix}-${++sequence.current}`;
  const currentApp = apps.find(row => row.id === app);
  const displayName = (row: App) => platform === "ios" && row.id === "browser" ? "Safari" : row.name;
  const selectedContact = contacts.find(row => row.id === conversation) ?? contacts[0]!;
  const selectedPhoto = photos.find(row => row.id === screen);
  const selectedMail = mails.find(row => row.id === screen);
  function announce(text: string) { setNotice(text); }
  function launch(next: AppId, nextScreen?: string, trigger?: Element) {
    const origin = next === "home" ? launchOrigins.current[app] : iosLaunchOrigin(trigger ?? document.activeElement);
    if (next !== "home" && app === "home") launchOrigins.current[next] = origin;
    const update = () => { savedScreens.current[app] = screen; setSearch(""); setApp(next); setScreenRaw(nextScreen ?? (next === "home" ? "" : savedScreens.current[next] ?? "")); setOverlay(""); setCall(""); if (next !== "home") setRecent(current => [next, ...current.filter(value => value !== next)].slice(0, 6)); requestAnimationFrame(() => appTitle.current?.focus({ preventScroll: true })); };
    if (platform === "ios" && app !== next) runIOSMotion(next === "home" ? "close" : app === "home" ? "open" : "push", update, origin); else { if (platform === "ios") cancelIOSMotion(); update(); }
  }
  function goBack() { if (overlay) closeOverlay(); else if (call) setCall(""); else if (app === "mail" && selectedMail) setScreen(selectedMail.sent ? "sent" : "inbox"); else if (screen === "edit-contact") setScreen("contact"); else if (screen) setScreen(""); else launch("home"); }
  function openOverlay(next: Exclude<typeof overlay, "">) {
    overlayTrigger.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const update = () => { setOverlay(next); requestAnimationFrame(() => appTitle.current?.focus({ preventScroll: true })); };
    if (platform === "ios") runIOSMotion(next === "library" ? "push" : "overlay-open", update, iosLaunchOrigin(overlayTrigger.current)); else update();
  }
  function closeOverlay() {
    const update = () => { setOverlay(""); requestAnimationFrame(() => overlayTrigger.current?.isConnected && overlayTrigger.current.focus()); };
    if (platform === "ios") runIOSMotion(overlay === "library" ? "back" : "overlay-close", update, iosLaunchOrigin(overlayTrigger.current)); else update();
  }
  function openNote(note?: typeof notes[number]) { setScreen(note?.id ?? "new"); setNoteTitle(note?.title ?? ""); setNoteBody(note?.body ?? ""); }
  function openFile(file?: typeof files[number]) { setScreen(file?.id ?? "new"); setFileName(file?.name ?? ""); setFileBody(file?.body ?? ""); }
  function saveNote(event: React.FormEvent) { event.preventDefault(); if (!noteTitle.trim()) return; const note = { id: screen === "new" ? unique("note") : screen, title: noteTitle.trim(), body: noteBody }; setNotes(current => screen === "new" ? [note, ...current] : current.map(row => row.id === screen ? note : row)); setScreen(""); announce("Note saved locally"); }
  function saveFile(event: React.FormEvent) { event.preventDefault(); if (!fileName.trim()) return; const file = { id: screen === "new" ? unique("file") : screen, name: fileName.trim(), body: fileBody }; setFiles(current => screen === "new" ? [...current, file] : current.map(row => row.id === screen ? file : row)); setScreen(""); announce("File saved locally"); }
  function downloadFile() { const url = URL.createObjectURL(new Blob([fileBody], { type: "text/plain;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = fileName.replace(/[/\\]/g, "-") || "note.txt"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); announce("Text file downloaded"); }
  function key(value: string) { if (value === "±" || value === "%") { const result = Number(calculate(expression)); if (Number.isFinite(result)) { setExpression(String(value === "±" ? -result : result / 100)); setCalculated(true); } return; } if (value === "Clear") { setExpression("0"); setCalculated(false); return; } if (value === "Delete") { setExpression(current => current.length > 1 ? current.slice(0, -1) : "0"); return; } if (value === "=") { setExpression(calculate(expression)); setCalculated(true); return; } const operator = /[+−×÷]/.test(value); setExpression(current => { if (calculated || !/^[\d.+−×÷]+$/.test(current)) return operator && /^-?\d/.test(current) ? current.replace("-", "−") + value : operator ? "0" : value; if (current.length > 30) return current; if (operator) return /[+−×÷]$/.test(current) ? current.slice(0, -1) + value : current + value; if (value === "." && current.split(/[+−×÷]/).at(-1)?.includes(".")) return current; return current === "0" && value !== "." ? value : current + value; }); setCalculated(false); }
  async function toggleMusic() {
    const request = ++audioRequest.current;
    if (musicPlaying) { setMusicPlaying(false); announce("Music paused"); return; }
    try {
      if (!audio.current || audio.current.state === "closed") {
        const context = new AudioContext();
        audio.current = context;
        gain.current = context.createGain();
        gain.current.connect(context.destination);
        context.onstatechange = () => {
          if (!audioMounted.current || audio.current !== context || context.state === "running") return;
          setMusicPlaying(false);
          announce("Audio paused by the browser. Press Play to resume.");
        };
      }
      const context = audio.current;
      await context.resume();
      if (!audioMounted.current || audio.current !== context || request !== audioRequest.current) return;
      if (context.state !== "running") { setMusicPlaying(false); announce("Audio is still suspended. Press Play to try again."); return; }
      setMusicPlaying(true);
      announce("Playing locally synthesized tones");
    } catch { if (audioMounted.current && request === audioRequest.current) { setMusicPlaying(false); announce("Audio could not start in this browser. Press Play to try again."); } }
  }
  React.useEffect(() => { if (!timerRunning) return; const tick = () => { const next = Math.max(0, Math.ceil((timerDeadline.current - Date.now()) / 1000)); setRemaining(next); if (!next) { setTimerRunning(false); setNotice("Timer complete"); setNotifications(current => [{ id: `timer-${Date.now()}`, title: "Timer complete", text: "Your local timer has finished." }, ...current]); } }; tick(); const handle = window.setInterval(tick, 200); return () => clearInterval(handle); }, [timerRunning]);
  React.useEffect(() => { if (!stopwatchRunning) return; const handle = window.setInterval(() => setElapsed(Date.now() - stopwatchBase.current), 100); return () => clearInterval(handle); }, [stopwatchRunning]);
  React.useEffect(() => { if (!musicPlaying || !audio.current || !gain.current) return; const ctx = audio.current; const output = gain.current; output.gain.setValueAtTime(volume / 100 * 0.12, ctx.currentTime); let index = 0; const play = () => { if (ctx.state !== "running") return; const oscillator = ctx.createOscillator(); const envelope = ctx.createGain(); oscillator.type = "sine"; oscillator.frequency.value = tones[track]![index % 8]!; envelope.gain.setValueAtTime(0, ctx.currentTime); envelope.gain.linearRampToValueAtTime(0.8, ctx.currentTime + 0.02); envelope.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.38); oscillator.connect(envelope); envelope.connect(output); oscillator.start(); oscillator.stop(ctx.currentTime + 0.4); oscillator.onended = () => { oscillator.disconnect(); envelope.disconnect(); }; index++; setBeat(index % 8); }; play(); const handle = window.setInterval(play, 450); return () => clearInterval(handle); }, [musicPlaying, track, volume]);
  React.useEffect(() => {
    audioMounted.current = true;
    return () => {
      audioMounted.current = false;
      audioRequest.current++;
      const context = audio.current;
      audio.current = null;
      gain.current?.disconnect();
      gain.current = null;
      if (context) { context.onstatechange = null; if (context.state !== "closed") void context.close().catch(() => {}); }
    };
  }, []);

  const iosHomeSearch = (rail = false) => <Button variant="ghost" className={`mo-search-pill${rail ? " mo-ios-home-search-rail" : ""}`} onClick={() => openOverlay("library")}><Icon name="search" size={12} style={device.id === "iphone-duo" && !live ? { width: 20, height: 20 } : undefined} />Search</Button>;
  const launchIcon = (row: App) => <Button className="mo-app-icon" variant="ghost" key={row.id} aria-label={`Open ${displayName(row)}`} onClick={event => launch(row.id, undefined, event.currentTarget)}><span data-app-icon={row.id}>{platform === "ios" ? <IOSAppGlyph id={row.id} icon={row.icon} /> : <AndroidAppGlyph id={row.id} icon={row.icon} />}{row.id === "messages" && <i aria-hidden="true">2</i>}</span><strong>{displayName(row)}</strong></Button>;
  const quickControls: { label: string; value: boolean; update: React.Dispatch<React.SetStateAction<boolean>>; icon: IconName }[] = [{ label: "Wi-Fi", value: wifi, update: setWifi, icon: "wifi" }, { label: "Bluetooth", value: bluetooth, update: setBluetooth, icon: "link" }, { label: "Focus", value: focusMode, update: setFocusMode, icon: "moon" }, { label: "Low power", value: lowPower, update: setLowPower, icon: "power" }];
  let content: React.ReactNode; let actions: React.ReactNode = null;
  const quickTiles = <div className="mo-quick-grid">{quickControls.map(row => <Button variant="ghost" key={row.label} aria-pressed={row.value} onClick={() => { row.update(!row.value); announce(`${row.label} ${row.value ? "off" : "on"}, locally`); }}><SystemIcon name={row.icon} /><strong>{row.label}</strong><span>{row.value ? "On" : "Off"}</span></Button>)}</div>;
  const musicTile = <div className="mo-now-playing"><Icon name="music" /><span><strong>{trackNames[track]}</strong><span>{musicPlaying ? "Playing local tones" : "Paused"}</span></span><Button variant="ghost" aria-label={musicPlaying ? "Pause music" : "Play music"} onClick={() => void toggleMusic()}><Icon name={musicPlaying ? "pause" : "play"} /></Button></div>;
  const notificationList = notifications.length ? notifications.map(row => <article className="mo-notification" key={row.id}><Icon name="bell" /><div><h3>{row.title}</h3><p>{row.text}</p></div><Button variant="ghost" aria-label={`Dismiss ${row.title}`} onClick={() => setNotifications(current => current.filter(item => item.id !== row.id))}><Icon name="close" /></Button></article>) : <div className="mo-empty"><Icon name="check" size={24} /><h3>You’re all caught up</h3><p>No local notifications remain.</p></div>;
  if (overlay === "library") {
    const matches = apps.filter(row => displayName(row).toLowerCase().includes(search.toLowerCase()));
    const groups: { name: string; ids: AppId[] }[] = [{ name: "Communication", ids: ["phone", "messages", "mail", "contacts"] }, { name: "Creativity", ids: ["notes", "photos", "camera", "music"] }, { name: "Utilities", ids: ["settings", "calculator", "clock", "files"] }, { name: "Information", ids: ["weather", "maps", "browser", "calendar"] }];
    content = <><SearchField platform={platform} label="Search apps" placeholder={platform === "ios" ? "App Library" : "Search your apps"} value={search} onValueChange={setSearch} />{platform === "ios" && !search ? <div className="mo-library-groups">{groups.map(group => <section key={group.name}><div className="mo-app-grid">{apps.filter(row => group.ids.includes(row.id)).map(launchIcon)}</div><h3>{group.name}</h3></section>)}</div> : <div className="mo-app-grid mo-all-apps">{[...matches].sort((a, b) => a.name.localeCompare(b.name)).map(launchIcon)}</div>}{!matches.length && <p className="mo-caption">No matching apps.</p>}</>;
  } else if (overlay === "quick") {
    content = platform === "ios" ? <div className="mo-ios-control-layout">
      <div className="mo-quick-grid mo-ios-connectivity">{[
        { label: "Airplane Mode", value: airplaneMode, update: setAirplaneMode, icon: "send" as const },
        { label: "Cellular data", value: cellular, update: setCellular, icon: "globe" as const },
        { label: "Wi-Fi", value: wifi, update: setWifi, icon: "wifi" as const },
        { label: "Bluetooth", value: bluetooth, update: setBluetooth, icon: "link" as const },
      ].map(row => <Button variant="ghost" key={row.label} aria-label={`${row.label}: ${row.value ? "On" : "Off"}`} aria-pressed={row.value} onClick={() => { row.update(!row.value); announce(`${row.label} ${row.value ? "off" : "on"}, locally`); }}><SystemIcon name={row.icon} /><span className="mo-sr-only">{row.label}</span></Button>)}</div>
      <div className="mo-ios-media-control"><Icon name="music" size={24} /><strong>{trackNames[track]}</strong><span>{musicPlaying ? "Playing local tones" : "Not playing"}</span><Button variant="ghost" aria-label={musicPlaying ? "Pause music" : "Play music"} onClick={() => void toggleMusic()}><Icon name={musicPlaying ? "pause" : "play"} /></Button></div>
      <Button variant="ghost" className="mo-ios-focus-control" aria-pressed={focusMode} onClick={() => setFocusMode(value => !value)}><Icon name="moon" /><strong>{focusMode ? "Do Not Disturb" : "Focus"}</strong><Icon name="chevron-right" /></Button>
      <div className="mo-control-sliders"><Field label="Brightness"><div className="mo-vertical-slider" style={{ "--mo-level": `${(brightness - 30) / 70 * 100}%` } as React.CSSProperties}><Slider aria-label="Display brightness" aria-orientation="vertical" min={30} max={100} value={brightness} onValueChange={setBrightness} /><Icon name="sun" /></div></Field><Field label="Volume"><div className="mo-vertical-slider" style={{ "--mo-level": `${volume}%` } as React.CSSProperties}><Slider aria-label="Media volume" aria-orientation="vertical" min={0} max={100} value={volume} onValueChange={setVolume} /><Icon name="volume" /></div></Field></div>
      <div className="mo-ios-control-pair"><Button variant="ghost" aria-label="Portrait orientation lock" aria-pressed={orientationLocked} onClick={() => setOrientationLocked(value => !value)}><SystemIcon name={orientationLocked ? "lock" : "unlock"} /></Button><Button variant="ghost" aria-label="Low power mode" aria-pressed={lowPower} onClick={() => setLowPower(value => !value)}><SystemIcon name="power" /></Button></div>
      <div className="mo-ios-control-shortcuts">{apps.filter(row => ["clock", "calculator", "camera", "settings"].includes(row.id)).map(row => <Button variant="ghost" key={row.id} aria-label={`Open ${row.name}`} onClick={event => launch(row.id, undefined, event.currentTarget)}><Icon name={row.icon} size={24} /></Button>)}</div>
    </div> : <><div className="mo-shade-clock"><strong>09:41</strong><span>Tue, 8 Sep</span></div><div className="mo-android-brightness"><Slider aria-label="Display brightness" min={30} max={100} value={brightness} onValueChange={setBrightness} /></div>{quickTiles}{musicTile}<div className="mo-shade-actions"><span>Sample system</span><Button variant="ghost" aria-label="Open Settings" onClick={() => launch("settings")}><Icon name="settings" /></Button></div></>;
  } else if (overlay === "notifications") {
    content = <>{platform === "ios" ? <div className="mo-notification-clock"><span>Tuesday, 8 September</span><strong>9:41</strong></div> : <><div className="mo-shade-compact">{quickControls.slice(0, 2).map(row => <Button variant="ghost" key={row.label} aria-pressed={row.value} onClick={() => row.update(!row.value)}><SystemIcon name={row.icon} /><span>{row.label}</span></Button>)}<Button variant="ghost" aria-label="Expand Quick Settings" onClick={() => setOverlay("quick")}><Icon name="chevron-down" /></Button></div><span className="mo-caption">Tue, 8 Sep · Sample system</span></>}<div className="mo-notification-heading"><h3>{platform === "ios" ? "Notification Center" : "Notifications"}</h3><Button variant="ghost" aria-label="Clear notifications" disabled={!notifications.length} onClick={() => setNotifications([])}><Icon name="close" /></Button></div>{focusMode && <p className="mo-caption">Focus is on</p>}{notificationList}</>;
  } else if (overlay === "recents") {
    content = <div className="mo-recents">{recent.length ? recent.map(appId => { const row = apps.find(item => item.id === appId)!; return <article className="mo-recent-task" key={row.id}><header><span className="mo-mini-icon"><Icon name={row.icon} /></span><strong>{row.name}</strong><Button variant="ghost" aria-label={`Dismiss ${row.name} from recent apps`} onClick={() => setRecent(current => current.filter(value => value !== row.id))}><Icon name="close" /></Button></header><Button variant="ghost" className="mo-recent-preview" aria-label={`Return to ${row.name}`} onClick={event => launch(row.id, undefined, event.currentTarget)}><Icon name={row.icon} size={24} /><h3>{row.name}</h3><span>{row.id === "notes" ? `${notes.length} notes` : row.id === "messages" ? `${messages.length} local messages` : row.id === "files" ? `${files.length} files` : row.id === "music" ? trackNames[track] : "Pick up where you left off"}</span></Button></article>; }) : <div className="mo-empty"><Icon name="layers" size={24} /><h3>No recent apps yet</h3><p>Open an app from the home screen.</p></div>}</div>;
    if (platform === "android") actions = <Button variant="ghost" disabled={!recent.length} onClick={() => setRecent([])}>Clear all</Button>;
  } else if (app === "home") {
    content = platform === "ios" ? <><div className="mo-ios-widgets"><Button variant="ghost" className="mo-ios-weather-widget" onClick={event => launch("weather", undefined, event.currentTarget)}><span>Alkmaar</span><strong>18°</strong><Icon name="cloud" /><span>Overcast</span></Button><Button variant="ghost" className="mo-ios-calendar-widget" onClick={event => launch("calendar", undefined, event.currentTarget)}><span>Tuesday</span><strong>8</strong><span>Studio review</span><span>10:30</span></Button></div><div className="mo-app-grid mo-home-apps">{apps.filter(row => !dockIds.includes(row.id)).map(launchIcon)}</div><div className="mo-ios-home-tools">{iosHomeSearch()}<Button variant="ghost" aria-label="App Library" className="mo-library-page" onClick={() => openOverlay("library")}><span aria-hidden="true">••</span><Icon name="chevron-right" size={12} /></Button></div></> : <><Button variant="ghost" className="mo-at-a-glance" onClick={event => launch("calendar", undefined, event.currentTarget)}><span>Tuesday, 8 Sep</span><span><Icon name="sun" size={12} />18°C</span></Button><Button variant="ghost" className="mo-android-clock-widget" aria-label="Open Clock widget" onClick={() => launch("clock")}><span>09</span><span>41</span></Button><div className="mo-app-grid mo-home-apps">{apps.filter(row => ["camera", "photos", "mail", "settings"].includes(row.id)).map(launchIcon)}</div></>;
  } else if (app === "phone" || app === "contacts") {
    if (call) {
      content = <div className="mo-call"><span className="mo-call-avatar"><Icon name="user" size={24} style={platform === "ios" ? { width: 56, height: 56 } : undefined} /></span><h3>{call}</h3><p>Simulated call</p><span className="mo-caption">No phone call is placed.</span></div>;
      actions = <Button onClick={() => { setCall(""); announce("Simulated call ended"); }}><Icon name="phone" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />End call</Button>;
    } else if (screen === "new" || platform === "ios" && screen === "edit-contact") {
      content = <form id={formId} className="mo-form mo-contact-form" onSubmit={event => { event.preventDefault(); if (!contactName.trim() || !contactPhone.trim()) return; setContacts(current => screen === "edit-contact" ? current.map(row => row.id === conversation ? { ...row, name: contactName.trim(), phone: contactPhone.trim() } : row) : [...current, { id: unique("contact"), name: contactName.trim(), phone: contactPhone.trim() }]); setContactName(""); setContactPhone(""); setScreen(screen === "edit-contact" ? "contact" : ""); announce("Contact saved locally"); }}><Field label="Full name"><Input aria-label="Full name" placeholder={platform === "ios" ? "Name" : undefined} value={contactName} maxLength={60} required onChange={event => setContactName(event.target.value)} /></Field><Field label="Phone number"><Input type="tel" aria-label="Phone number" placeholder={platform === "ios" ? "Phone number" : undefined} value={contactPhone} maxLength={30} required pattern={"[+0-9\\s\\(\\)\\-]+"} onChange={event => setContactPhone(event.target.value)} /></Field></form>;
      actions = <Button type="submit" form={formId} aria-label="Save contact" disabled={!contactName.trim() || !contactPhone.trim()}>{platform === "ios" ? "Done" : "Save contact"}</Button>;
    } else if (platform === "ios" && screen === "contact") {
      content = <article className="mo-contact-card"><div className="mo-contact-portrait" aria-hidden="true">{selectedContact.name.split(" ").map(part => part[0]).join("").slice(0, 2)}</div><h3>{selectedContact.name}</h3><div className="mo-contact-quick-actions"><Button variant="ghost" aria-label={`Message ${selectedContact.name}`} onClick={() => { launch("messages", "thread"); }}><Icon name="message" style={{ width: 24, height: 24 }} /><span>message</span></Button><Button variant="ghost" aria-label={`Call ${selectedContact.name}`} onClick={() => { setCall(selectedContact.name); announce("Simulated call started. No phone call is placed."); }}><Icon name="phone" style={{ width: 24, height: 24 }} /><span>call</span></Button></div><Button variant="ghost" className="mo-contact-number" onClick={() => { setCall(selectedContact.name); announce("Simulated call started. No phone call is placed."); }}><span>mobile</span><strong>{selectedContact.phone}</strong></Button></article>;
      actions = <Button variant="ghost" onClick={() => { setContactName(selectedContact.name); setContactPhone(selectedContact.phone); setScreen("edit-contact"); }}>Edit</Button>;
    } else if (platform === "ios" && screen === "recent-calls") {
      content = <><div className="mo-caption">Sample recent calls</div>{contacts.map(row => <Button key={row.id} variant="ghost" className="mo-list-row" onClick={() => { setCall(row.name); announce("Simulated call started. No phone call is placed."); }}><Icon name="phone" style={platform === "ios" ? { width: 24, height: 24 } : undefined} /><span><strong>{row.name}</strong><span>Outgoing · Yesterday</span></span><Icon name="info" /></Button>)}</>;
    } else if (screen === "dial") {
      content = <><Input aria-label="Dial number" type="tel" value={dial} onChange={event => setDial(event.target.value.replace(/[^\d+*#]/g, "").slice(0, 20))} placeholder="Enter a number" /><div className="mo-keypad">{"123456789*0#".split("").map(value => <Button variant="ghost" key={value} aria-label={value} onClick={() => setDial(current => (current + value).slice(0, 20))}>{platform === "ios" ? <><span className="mo-dial-digit">{value}</span><small aria-hidden="true">{({ "2": "ABC", "3": "DEF", "4": "GHI", "5": "JKL", "6": "MNO", "7": "PQRS", "8": "TUV", "9": "WXYZ", "0": "+" } as Record<string, string>)[value] ?? " "}</small></> : value}</Button>)}</div><Button variant="ghost" disabled={!dial} onClick={() => setDial(current => current.slice(0, -1))}>Delete last digit</Button><p className="mo-caption">Local dial pad. No telephone service is connected.</p></>;
      actions = <Button disabled={!dial} onClick={() => { setCall(dial); announce("Simulated call started. No phone call is placed."); }}><Icon name="phone" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Simulate call</Button>;
    } else {
      content = <>{platform === "ios" ? <SearchField platform={platform} label="Search contacts" placeholder="Search" value={search} onValueChange={setSearch} /> : <div className="mo-section-intro"><h3>Your people</h3><p>{contacts.length} saved contacts</p></div>}{contacts.filter(row => platform === "android" || row.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => platform === "ios" ? (a.name.split(" ").at(-1) ?? a.name).localeCompare(b.name.split(" ").at(-1) ?? b.name) : 0).map(row => <div className="mo-contact-row" key={row.id}><Button variant="ghost" className="mo-list-row" aria-label={row.name} onClick={() => { if (platform === "ios") { setConversation(row.id); setScreen("contact"); } else { setCall(row.name); announce("Simulated call started. No phone call is placed."); } }}>{platform === "ios" ? <span><span className="mo-contact-name">{row.name.split(" ").slice(0, -1).join(" ")}{row.name.includes(" ") && " "}<strong>{row.name.split(" ").at(-1)}</strong></span></span> : <><span className="mo-initials">{row.name.split(" ").map(part => part[0]).join("").slice(0, 2)}</span><span><strong>{row.name}</strong><span>{row.phone}</span></span><Icon name="phone" /></>}</Button>{platform === "android" && <Button variant="ghost" aria-label={`Message ${row.name}`} onClick={() => { setConversation(row.id); launch("messages", "thread"); }}><Icon name="message" /></Button>}</div>)}</>;
      actions = <>{app === "phone" && platform === "android" && <Button variant="ghost" onClick={() => setScreen("dial")}><Icon name="grid" />Keypad</Button>}<Button onClick={() => setScreen("new")}><Icon name="plus" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />New contact</Button></>;
    }
  } else if (app === "messages") {
    if (screen === "recipients") {
      content = <><SearchField platform={platform} label="Search recipients" placeholder="Name or phone number" value={search} onValueChange={setSearch} />{contacts.filter(row => `${row.name} ${row.phone}`.toLowerCase().includes(search.toLowerCase())).map(row => <Button variant="ghost" className="mo-list-row" key={row.id} onClick={() => { setConversation(row.id); setScreen("thread"); setSearch(""); }}><span className="mo-initials">{row.name[0]}</span><span><strong>{row.name}</strong><span>{row.phone}</span></span></Button>)}</>;
    } else if (screen === "thread") {
      content = <><div className="mo-thread-recipient">{platform === "android" && <span className="mo-initials" aria-hidden="true">{selectedContact.name.split(" ").map(part => part[0]).join("")}</span>}<span>Today, 9:41</span></div><div className="mo-messages">{messages.filter(row => row.contact === conversation).map(row => <article key={row.id} className={`mo-message${row.mine ? " mo-message-mine" : ""}`}><span>{row.mine ? "You · Saved locally" : selectedContact.name}</span><p>{row.text}</p></article>)}{!messages.some(row => row.contact === conversation) && <p className="mo-caption">Start a local conversation.</p>}</div></>;
      actions = <form className="mo-message-compose" onSubmit={event => { event.preventDefault(); if (!messageDraft.trim()) return; setMessages(current => [...current, { id: unique("message"), contact: conversation, mine: true, text: messageDraft.trim() }]); setMessageDraft(""); announce("Message saved locally. Nothing was sent externally."); }}><Input aria-label="Message" placeholder="Write a message" value={messageDraft} maxLength={500} onChange={event => setMessageDraft(event.target.value)} /><Button type="submit" aria-label="Send local message" disabled={!messageDraft.trim()}><Icon name={platform === "ios" ? "arrow-up" : "send"} size={24} /></Button></form>;
    } else {
      content = <>{platform === "ios" ? <SearchField platform={platform} label="Search messages" placeholder="Search" value={search} onValueChange={setSearch} /> : <div className="mo-section-intro"><h3>A little conversation</h3><p>Messages stay on this sample phone.</p></div>}{contacts.filter(row => platform === "android" || row.name.toLowerCase().includes(search.toLowerCase()) || messages.some(message => message.contact === row.id && message.text.toLowerCase().includes(search.toLowerCase()))).map(row => <Button variant="ghost" className="mo-list-row" key={row.id} onClick={() => { setConversation(row.id); setScreen("thread"); }}><span className="mo-initials">{row.name[0]}</span><span><strong>{row.name}</strong><span>{messages.filter(message => message.contact === row.id).at(-1)?.text ?? "Start a conversation"}</span></span><Icon name="chevron-right" /></Button>)}</>;
      actions = <Button onClick={() => { setSearch(""); setScreen("recipients"); }}><Icon name="edit" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />New message</Button>;
    }
  } else if (app === "mail") {
    if (platform === "ios" && !screen) {
      content = <><Button variant="ghost" className="mo-list-row mo-mailbox-row" onClick={() => setScreen("inbox")}><Icon name="inbox" style={{ width: 24, height: 24 }} /><strong>Inbox</strong><span className="mo-mailbox-count">{mails.filter(row => !row.sent).length}</span><Icon name="chevron-right" style={{ width: 14, height: 14 }} /></Button><Button variant="ghost" className="mo-list-row mo-mailbox-row" onClick={() => setScreen("sent")}><Icon name="send" style={{ width: 24, height: 24 }} /><strong>Sent</strong><span className="mo-mailbox-count">{mails.filter(row => row.sent).length}</span><Icon name="chevron-right" style={{ width: 14, height: 14 }} /></Button><p className="mo-caption">Mail saved on this sample phone. No email service is connected.</p></>;
      actions = <Button variant={platform === "ios" ? "ghost" : "primary"} onClick={() => setScreen("compose")}><Icon name="edit" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Compose</Button>;
    } else if (screen === "compose") {
      content = <form id={formId} className="mo-form" onSubmit={event => { event.preventDefault(); if (!mailTo.trim() || !mailSubject.trim() || !mailBody.trim()) return; setMails(current => [{ id: unique("mail"), from: mailTo.trim(), subject: mailSubject.trim(), body: mailBody.trim(), sent: true }, ...current]); setMailTo(""); setMailSubject(""); setMailBody(""); setScreen("sent"); announce("Email saved in local Sent. No email was delivered."); }}><Field label="To"><Input type="email" aria-label="To" placeholder="name@example.invalid" value={mailTo} required onChange={event => setMailTo(event.target.value)} /></Field><Field label="Subject"><Input aria-label="Subject" value={mailSubject} maxLength={100} required onChange={event => setMailSubject(event.target.value)} /></Field><Field label="Message body"><Textarea aria-label="Message body" value={mailBody} rows={5} maxLength={2000} required onChange={event => setMailBody(event.target.value)} /></Field><p className="mo-caption">This saves a local copy. No mail server is connected.</p></form>;
      actions = <Button type="submit" form={formId}>Save to local Sent<Icon name="send" style={platform === "ios" ? { width: 24, height: 24 } : undefined} /></Button>;
    } else if (selectedMail) {
      content = <article className="mo-mail-read"><span className="mo-eyebrow">{selectedMail.sent ? "To" : "From"}: {selectedMail.from}</span><h3>{selectedMail.subject}</h3><p>{selectedMail.body}</p><span className="mo-caption">{selectedMail.sent ? "Saved locally · Not delivered" : "Sample email"}</span></article>;
      actions = <><Button variant="ghost" onClick={() => { setMails(current => current.filter(row => row.id !== screen)); setScreen(""); announce("Email removed locally"); }}><Icon name="trash" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Delete</Button><Button onClick={() => { setMailTo("mara@example.invalid"); setMailSubject(`Re: ${selectedMail.subject}`); setMailBody(""); setScreen("compose"); }}>Reply</Button></>;
    } else {
      content = <>{platform === "android" && <ToggleGroup aria-label="Mail folder" value={screen === "sent" ? "sent" : "inbox"} options={[{ value: "inbox", label: "Inbox" }, { value: "sent", label: "Sent" }]} onValueChange={value => setScreen(value === "inbox" ? "" : "sent")} />}{mails.filter(row => row.sent === (screen === "sent")).map(row => <Button variant="ghost" className={`mo-list-row${platform === "ios" ? " mo-ios-mail-row" : ""}`} key={row.id} onClick={() => setScreen(row.id)}>{platform === "ios" ? <span className="mo-ios-mail-copy"><strong>{row.sent ? `To: ${row.from}` : row.from}</strong><span className="mo-ios-mail-subject">{row.subject}</span><span className="mo-ios-mail-preview">{row.body}</span></span> : <><Icon name="mail" /><span><strong>{row.subject}</strong><span>{row.sent ? "Local copy to " : "From "}{row.from}</span></span></>}<Icon name="chevron-right" style={platform === "ios" ? { width: 14, height: 14 } : undefined} /></Button>)}{!mails.some(row => row.sent === (screen === "sent")) && <p className="mo-caption">No messages in this folder.</p>}</>;
      actions = <Button variant={platform === "ios" ? "ghost" : "primary"} onClick={() => setScreen("compose")}><Icon name="edit" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Compose</Button>;
    }
  } else if (app === "calendar" && platform === "android") {
    content = <><Field label="Selected date"><Input type="date" aria-label="Selected date" value={date} onChange={event => setDate(event.target.value)} /></Field>{screen === "new" ? <form id={formId} className="mo-form" onSubmit={event => { event.preventDefault(); if (!eventTitle.trim() || !date || !eventTime) return; setEvents(current => [...current, { id: unique("event"), date, time: eventTime, title: eventTitle.trim() }]); setEventTitle(""); setScreen(""); announce("Calendar event saved locally"); }}><Field label="Event title"><Input aria-label="Event title" value={eventTitle} maxLength={80} required onChange={event => setEventTitle(event.target.value)} /></Field><Field label="Event time"><Input type="time" aria-label="Event time" value={eventTime} required onChange={event => setEventTime(event.target.value)} /></Field></form> : <><div className="mo-section-intro"><h3>Your day, with room</h3><p>{date || "Choose a date"}</p></div>{events.filter(row => row.date === date).sort((a, b) => a.time.localeCompare(b.time)).map(row => <article className="mo-event" key={row.id}><time>{row.time}</time><h3>{row.title}</h3><Button variant="ghost" aria-label={`Delete ${row.title}`} onClick={() => { setEvents(current => current.filter(item => item.id !== row.id)); announce("Event removed locally"); }}><Icon name="trash" /></Button></article>)}{!events.some(row => row.date === date) && <p className="mo-caption">Nothing scheduled for this day.</p>}</>}</>;
    actions = screen === "new" ? <Button type="submit" form={formId} aria-label="Save event" disabled={!date || !eventTitle.trim()}>Save event</Button> : <Button disabled={!date} onClick={() => setScreen("new")}><Icon name="plus" />New event</Button>;
  } else if (app === "clock" && platform === "android") {
    content = <>{clockTab === "timer" ? <><div className="mo-clock-face" role="timer" aria-label="Time remaining">{time(remaining)}</div><NumberField label="Timer seconds" value={timerSeconds} min={1} max={3600} step={1} disabled={timerRunning} onValueChange={value => { const next = Math.max(1, Math.min(3600, Math.round(value ?? 1))); setTimerSeconds(next); setRemaining(next); }} /><p className="mo-caption">The timer keeps running while you use other local apps.</p></> : clockTab === "stopwatch" ? <><div className="mo-clock-face" role="timer" aria-label="Stopwatch elapsed">{time(elapsed / 1000)}<small>.{Math.floor(elapsed % 1000 / 100)}</small></div>{laps.map((lap, index) => <div className="mo-data-row" key={`${index}-${lap}`}><span>Lap {index + 1}</span><span>{time(lap / 1000)}.{Math.floor(lap % 1000 / 100)}</span></div>)}</> : <><div className="mo-clock-face">{alarmTime || "--:--"}</div><Field label="Alarm time"><Input aria-label="Alarm time" type="time" value={alarmTime} onChange={event => setAlarmTime(event.target.value)} /></Field><div className="mo-setting-switch"><span>Alarm enabled</span><Switch aria-label="Alarm enabled" checked={alarmOn} disabled={!alarmTime} onCheckedChange={value => { setAlarmOn(value); announce(value ? "Sample alarm saved" : "Sample alarm disabled"); }} /></div><p className="mo-caption">This saves an alarm preference in the prototype. It does not wake your device or run after you close the tab.</p></>}</>;
    actions = clockTab === "timer" ? <><Button variant="ghost" onClick={() => { setTimerRunning(false); setRemaining(timerSeconds); }}>Reset</Button><Button onClick={() => { if (timerRunning) setTimerRunning(false); else { const next = remaining || timerSeconds; setRemaining(next); timerDeadline.current = Date.now() + next * 1000; setTimerRunning(true); } }}>{timerRunning ? "Pause timer" : "Start timer"}</Button></> : clockTab === "stopwatch" ? <><Button variant="ghost" onClick={() => { if (stopwatchRunning) setLaps(current => [...current, elapsed]); else { setElapsed(0); setLaps([]); } }}>{stopwatchRunning ? "Lap" : "Reset"}</Button><Button onClick={() => { if (stopwatchRunning) setStopwatchRunning(false); else { stopwatchBase.current = Date.now() - elapsed; setStopwatchRunning(true); } }}>{stopwatchRunning ? "Stop" : "Start stopwatch"}</Button></> : null;
  } else if (app === "notes") {
    if (screen) {
      content = <form id={formId} className="mo-form" onSubmit={saveNote}><Field label="Note title">{platform === "ios" ? <Textarea className="mo-note-title" aria-label="Note title" placeholder="Title" value={noteTitle} rows={1} maxLength={80} required onChange={event => setNoteTitle(event.target.value.replaceAll("\n", " "))} /> : <Input aria-label="Note title" value={noteTitle} maxLength={80} required onChange={event => setNoteTitle(event.target.value)} />}</Field><Field label="Note text"><Textarea aria-label="Note text" value={noteBody} rows={7} maxLength={3000} onChange={event => setNoteBody(event.target.value)} /></Field></form>;
      actions = <>{screen !== "new" && <Button variant="ghost" onClick={() => { setNotes(current => current.filter(row => row.id !== screen)); setScreen(""); announce("Note removed locally"); }}><Icon name="trash" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Delete</Button>}<Button type="submit" form={formId} aria-label="Save note" disabled={!noteTitle.trim()}>{platform === "ios" ? "Done" : "Save note"}</Button></>;
    } else {
      content = <>{platform === "ios" ? <SearchField platform={platform} label="Search notes" placeholder="Search" value={search} onValueChange={setSearch} /> : <div className="mo-section-intro"><h3>Thoughts, kept close</h3><p>{notes.length} notes on this phone</p></div>}{notes.filter(row => platform === "android" || `${row.title} ${row.body}`.toLowerCase().includes(search.toLowerCase())).map(row => <Button variant="ghost" className="mo-list-row" key={row.id} onClick={() => openNote(row)}><Icon name="edit" style={platform === "ios" ? { width: 24, height: 24 } : undefined} /><span><strong>{row.title}</strong><span>{row.body.split("\n")[0] || "Empty note"}</span></span><Icon name="chevron-right" /></Button>)}</>;
      actions = <Button onClick={() => openNote()}><Icon name="plus" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />New note</Button>;
    }
  } else if (app === "photos") {
    if (selectedPhoto) {
      content = <><img className="mo-photo-detail" src={selectedPhoto.src} alt={selectedPhoto.name} /><h3>{selectedPhoto.name}</h3><p className="mo-caption">Sample image · Stored in this local library</p></>;
      actions = <><Button variant="ghost" aria-pressed={selectedPhoto.favorite} onClick={() => setPhotos(current => current.map(row => row.id === screen ? { ...row, favorite: !row.favorite } : row))}><Icon name="star" />Favorite</Button><Button variant="ghost" onClick={() => { setPhotos(current => current.filter(row => row.id !== screen)); setScreen(""); announce("Photo removed from the local library"); }}><Icon name="trash"  />Remove</Button></>;
    } else if (platform === "ios") { content = <IOSPhotos photos={photos} onOpen={setScreen} onCamera={() => launch("camera")} />; }
    else { content = <><div className="mo-section-intro"><h3>A few moments</h3><p>{photos.length} local images</p></div><div className="mo-photo-grid">{photos.map(row => <Button variant="ghost" key={row.id} aria-label={`Open ${row.name}`} onClick={() => setScreen(row.id)}><img src={row.src} alt={row.name} />{row.favorite && <Icon name="star" />}</Button>)}</div>{!photos.length && <p className="mo-caption">Capture a sample scene to add a photo.</p>}</>; actions = <Button variant="ghost" onClick={() => launch("camera")}><Icon name="camera"  />Open camera</Button>; }
  } else if (app === "camera") {
    const captureSample = () => { setPhotos(current => [{ id: unique("capture"), name: `Studio capture ${current.filter(row => row.id.startsWith("capture")).length + 1}`, src: "/interfaces/threads/posters-v2.jpg", favorite: false }, ...current]); announce("Sample capture saved to Photos"); };
    if (platform === "ios") content = <IOSCamera photoSrc="/interfaces/threads/posters-v2.jpg" onCapture={captureSample} onLibrary={() => launch("photos", "")} />;
    else { content = <><div className="mo-camera"><img src="/interfaces/threads/posters-v2.jpg" alt="Illustrative camera scene of studio posters" /><div aria-hidden="true" className="mo-camera-grid" /><span>Sample scene</span></div><p className="mo-caption">This illustrative camera saves the shown sample scene. It does not access your camera.</p></>;
      actions = <><Button variant="ghost" onClick={() => launch("photos")}><Icon name="image" />Library</Button><Button onClick={captureSample}><Icon name="camera" />Capture</Button></>;
    }
  } else if (app === "files") {
    if (screen) { content = <form id={formId} className="mo-form" onSubmit={saveFile}><Field label="File name"><Input aria-label="File name" value={fileName} maxLength={80} required onChange={event => setFileName(event.target.value)} /></Field><Field label="File contents"><Textarea aria-label="File contents" value={fileBody} rows={7} maxLength={5000} onChange={event => setFileBody(event.target.value)} /></Field>{screen !== "new" && <div className="mo-inline-actions"><Button variant="ghost" onClick={downloadFile}><Icon name="download" />Download</Button><Button variant="ghost" onClick={() => { setFiles(current => current.filter(row => row.id !== screen)); setScreen(""); announce("File removed locally"); }}><Icon name="trash" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />Delete</Button></div>}</form>; actions = <Button type="submit" form={formId} aria-label="Save file" disabled={!fileName.trim()}>{platform === "ios" ? "Done" : "Save file"}</Button>; }
    else { content = <>{platform === "ios" ? <SearchField platform={platform} label="Search files" placeholder="Search" value={search} onValueChange={setSearch} /> : <div className="mo-section-intro"><h3>On this phone</h3><p>Text files you can edit and download.</p></div>}<div className="mo-file-list">{files.filter(row => platform === "android" || row.name.toLowerCase().includes(search.toLowerCase())).map(row => <Button variant="ghost" className="mo-list-row" key={row.id} onClick={() => openFile(row)}><span className="mo-file-preview"><Icon name="file" style={platform === "ios" ? { width: 24, height: 30 } : undefined} /></span><span><strong>{row.name}</strong><span>{new Blob([row.body]).size} bytes · Local text</span></span><Icon name="chevron-right" /></Button>)}</div></>; actions = <Button onClick={() => openFile()}><Icon name="plus" style={platform === "ios" ? { width: 24, height: 24 } : undefined} />New text file</Button>; }
  } else if (app === "calculator") {
    content = <><output className="mo-calculator-display" aria-label="Calculation result">{expression}</output><div className="mo-calculator">{(platform === "ios" ? ["Clear", "±", "%", "÷", "7", "8", "9", "×", "4", "5", "6", "−", "1", "2", "3", "+", "Delete", "0", ".", "="] : ["Clear", "Delete", "÷", "7", "8", "9", "×", "4", "5", "6", "−", "1", "2", "3", "+", "0", ".", "="]).map(value => <Button key={value} variant={value === "=" ? "primary" : "ghost"} data-key={value} className={platform === "android" && (value === "Clear" || value === "0") ? "mo-wide-key" : undefined} aria-label={value === "=" ? "Equals" : value} onClick={() => key(value)}>{value === "Delete" ? <Icon name="arrow-left" style={platform === "ios" ? { width: 24, height: 24 } : undefined} /> : platform === "ios" && value === "Clear" ? "AC" : value}</Button>)}</div></>;
  } else if (app === "weather") {
    const temperature = city === "Alkmaar" ? 18 : 17; const shown = (value: number) => weatherUnit === "c" ? value : Math.round(value * 9 / 5 + 32);
    const locationControls = <Select fullWidth aria-label="Weather location" value={city} options={[{ value: "Alkmaar", label: "Alkmaar" }, { value: "Utrecht", label: "Utrecht" }]} onValueChange={setCity} />;
    if (platform === "ios" && screen === "locations") {
      content = <><div className="mo-weather-locations">{["Alkmaar", "Utrecht"].map(name => <Button variant="ghost" key={name} aria-pressed={city === name} onClick={() => { setCity(name); setScreen(""); }}><span><strong>{name}</strong><span>{name === "Alkmaar" ? "Overcast" : "Sunny intervals"}</span></span><b>{shown(name === "Alkmaar" ? 18 : 17)}°</b></Button>)}</div><p className="mo-caption">Sample forecasts stored on this phone.</p></>;
      actions = null;
    } else {
    content = <>{platform === "android" && <Field label="Location">{locationControls}</Field>}<div className="mo-weather"><Icon name={city === "Alkmaar" ? "cloud" : "sun"} size={24} /><h3>{city}</h3><strong>{shown(temperature)}°</strong><span>{city === "Alkmaar" ? "Overcast" : "Sunny intervals"}</span><span className="mo-caption">Sample weather · Not a live forecast</span></div>{platform === "android" ? <ToggleGroup aria-label="Temperature unit" value={weatherUnit} options={[{ value: "c", label: "Celsius" }, { value: "f", label: "Fahrenheit" }]} onValueChange={setWeatherUnit} /> : <div className="mo-weather-hourly" role="group" aria-label="Hourly sample forecast">{["Now", "10", "11", "12", "13", "14"].map((hour, index) => <div key={hour}><span>{hour}</span><Icon name={index < 3 ? "cloud" : "sun"} style={{ width: 24, height: 24 }} /><strong>{shown(temperature + Math.floor(index / 2))}°</strong></div>)}</div>}<section className="mo-weather-forecast">{platform === "ios" && <h3><Icon name="calendar" style={{ width: 14, height: 14 }} />4-day forecast</h3>}{["Today", "Wednesday", "Thursday", "Friday"].map((day, index) => <div className="mo-data-row" key={day}><span>{day}</span><Icon name={index % 2 ? "sun" : "cloud"} style={platform === "ios" ? { width: 22, height: 22 } : undefined} />{platform === "ios" ? <><span className="mo-weather-low">{shown(temperature - 4 + index)}°</span><span className="mo-weather-range" aria-hidden="true"><i style={{ marginLeft: `${index * 8}%`, width: "65%" }} /></span><span className="mo-weather-high">{shown(temperature + index)}°</span></> : <span>{shown(temperature - 4 + index)}° / {shown(temperature + index)}°</span>}</div>)}</section></>;
    if (platform === "ios") actions = <div className="mo-weather-toolbar"><Button variant="ghost" aria-label={`Use ${weatherUnit === "c" ? "Fahrenheit" : "Celsius"}`} onClick={() => setWeatherUnit(value => value === "c" ? "f" : "c")}>{weatherUnit === "c" ? "°C" : "°F"}</Button><span aria-hidden="true">{city === "Alkmaar" ? "● ○" : "○ ●"}</span><Button variant="ghost" aria-label="Weather locations" onClick={() => setScreen("locations")}><Icon name="list" style={{ width: 24, height: 24 }} /></Button></div>;
    }
  } else if (app === "maps") {
    if (platform === "ios") content = <IOSMaps destination={destination} routing={routing} step={routeStep} zoom={mapZoom} onDestination={value => { setDestination(value); setRouting(false); setRouteStep(0); }} onZoom={setMapZoom} onStart={() => { setRouting(true); setRouteStep(0); }} onNext={() => setRouteStep(current => Math.min(2, current + 1))} onEnd={() => setRouting(false)} />;
    else {
    const steps = destination === "station" ? ["Leave the studio on Langestraat", "Continue toward the canal", "Arrive at the sample station"] : ["Leave the studio courtyard", "Follow the canal path", "Arrive at the sample park"];
    content = <><Field label="Destination"><Select fullWidth aria-label="Destination" value={destination} options={[{ value: "station", label: "Station · 1.2 km" }, { value: "park", label: "Park · 850 m" }]} onValueChange={value => { setDestination(value); setRouting(false); setRouteStep(0); }} /></Field><div className="mo-map" role="group" aria-label="Illustrative neighbourhood map"><svg viewBox="0 0 300 240" aria-hidden="true"><g transform={`translate(${150 - 150 * mapZoom} ${120 - 120 * mapZoom}) scale(${mapZoom})`}><path className="mo-map-roads" d="M0 45H300M0 195H300M45 0V240M250 0V240M0 120L300 80M140 0L195 240" /><path className="mo-map-route" data-active={routing} d={destination === "station" ? "M45 195V120L145 105L250 80V45" : "M45 195H190L165 105L145 45"} /><circle cx="45" cy="195" r="6" /><circle cx={destination === "station" ? 250 : 145} cy="45" r="6" /></g></svg><span>Illustrative map</span><div><Button variant="ghost" aria-label="Zoom out" disabled={mapZoom <= 1} onClick={() => setMapZoom(current => Math.max(1, current - 0.25))}><Icon name="minus" /></Button><Button variant="ghost" aria-label="Zoom in" disabled={mapZoom >= 2} onClick={() => setMapZoom(current => Math.min(2, current + 0.25))}><Icon name="plus"  /></Button></div></div>{routing ? <div className="mo-route-step"><span className="mo-eyebrow">Step {routeStep + 1} of 3 · Local route</span><h3>{steps[routeStep]}</h3></div> : <p className="mo-caption">Choose a destination and step through the sample route. No location service is used.</p>}</>;
    actions = routing ? <><Button variant="ghost" onClick={() => setRouting(false)}>End route</Button><Button disabled={routeStep === 2} onClick={() => setRouteStep(current => Math.min(2, current + 1))}>{routeStep === 2 ? "Arrived" : "Next step"}</Button></> : <Button onClick={() => { setRouting(true); setRouteStep(0); }}>Start local route<Icon name="arrow-right" /></Button>;
    }
  } else if (app === "music") {
    content = <><div className="mo-album" aria-hidden="true"><div /><Icon name="music" size={24} style={platform === "ios" ? { width: 40, height: 40 } : undefined} /><span>Vlak sessions · Vol. 01</span></div><div className="mo-track"><h3>{trackNames[track]}</h3><p>Studio tones · Synthesized locally</p></div><div className="mo-music-beats" role="img" aria-label={musicPlaying ? "Music is playing" : "Music is paused"}>{Array.from({ length: 8 }, (_, index) => <i key={index} data-active={musicPlaying && index === beat} />)}</div><div className="mo-music-controls"><Button variant="ghost" aria-label="Previous track" onClick={() => setTrack(current => (current + 2) % 3)}><Icon name="skip-back" style={platform === "ios" ? { width: 30, height: 30 } : undefined} /></Button><Button aria-label={musicPlaying ? "Pause music" : "Play music"} onClick={() => void toggleMusic()}><Icon name={musicPlaying ? "pause" : "play"} style={platform === "ios" ? { width: 40, height: 40 } : undefined} /></Button><Button variant="ghost" aria-label="Next track" onClick={() => setTrack(current => (current + 1) % 3)}><Icon name="skip-forward" style={platform === "ios" ? { width: 30, height: 30 } : undefined} /></Button></div><Field label={`Volume · ${volume}%`}><Slider aria-label="Music volume" min={0} max={100} value={volume} onValueChange={setVolume} /></Field>{platform === "android" && <>{trackNames.map((name, index) => <Button variant="ghost" className="mo-list-row" key={name} aria-pressed={track === index} onClick={() => setTrack(index)}><span className="mo-track-number">0{index + 1}</span><span><strong>{name}</strong><span>Local tone sequence</span></span><Icon name="music" /></Button>)}</>}</>;
    if (platform === "ios") {
      if (screen === "queue") content = <section className="mo-music-queue"><header><h3>Playing next</h3><Button variant="ghost" aria-label="Close queue" onClick={() => setScreen("")}><Icon name="close" style={{ width: 24, height: 24 }} /></Button></header>{trackNames.map((name, index) => <Button variant="ghost" className="mo-list-row" key={name} aria-pressed={track === index} onClick={() => setTrack(index)}><span className="mo-track-number">0{index + 1}</span><span><strong>{name}</strong><span>Local tone sequence</span></span><Icon name="music" /></Button>)}</section>;
      else actions = <Button variant="ghost" className="mo-music-queue-toggle" aria-label="Show queue" onClick={() => setScreen("queue")}><Icon name="list" style={{ width: 24, height: 24 }} /></Button>;
    }
  } else if (app === "browser") {
    const bookmark = bookmarks.find(row => row.address === browserPage)!;
    content = <><form className="mo-address" onSubmit={event => { event.preventDefault(); const next = address.trim().replace(/^https?:\/\//, "").replace(/\/$/, ""); if (bookmarks.some(row => row.address === next)) { setBrowserPage(next); setAddress(next); setBrowserError(""); } else setBrowserError("This local browser includes studio.local, guide.local, and vlak.local."); }}><Input aria-label="Page address" value={address} onChange={event => setAddress(event.target.value)} /><Button type="submit" aria-label="Open local page"><Icon name="arrow-right" /></Button></form>{browserError && <p className="mo-caption" role="status">{browserError}</p>}<article className="mo-browser-page"><Icon name="globe" size={24} /><span className="mo-eyebrow">{bookmark.address}</span><h3>{bookmark.title}</h3><p>{bookmark.text}</p><span className="mo-caption">Included local page · No external browsing</span></article><h3 className="mo-small-heading">Bookmarks</h3><div className="mo-browser-bookmarks">{bookmarks.map(row => <Button variant="ghost" className="mo-list-row" key={row.address} onClick={() => { setAddress(row.address); setBrowserPage(row.address); setBrowserError(""); }}><Icon name="bookmark" style={platform === "ios" ? { width: 60, height: 60 } : undefined} /><span><strong>{row.title}</strong><span>{row.address}</span></span><Icon name="arrow-right" /></Button>)}</div></>;
  } else if (app === "settings" && platform === "ios") {
    const settingRow = (title: string, subtitle: string, target: string, icon: IconName) => <Button variant="ghost" className="mo-ios-setting-row" onClick={() => setScreen(target)}><span className="mo-ios-setting-glyph"><SystemIcon name={icon} /></span><strong>{title}</strong><span>{subtitle}</span><Icon name="chevron-right" /></Button>;
    const restoreSettings = () => { setAppearance("system"); setTextSize(100); setWifi(true); setBluetooth(true); setLowPower(false); setFocusMode(false); setAirplaneMode(false); setCellular(true); setBrightness(80); setNetwork("Studio network"); setOrientationLocked(true); announce("Local settings restored"); };
    if (screen === "display") content = <><div className="mo-ios-appearance-cards" role="group" aria-label="Appearance">{(["light", "dark"] as const).map(mode => <label key={mode} data-dark={mode === "dark"} data-selected={appearance === mode}><input type="radio" name={`${id}-appearance`} value={mode} checked={appearance === mode} onChange={() => setAppearance(mode)} /><i aria-hidden="true" /><span>{mode === "light" ? "Light" : "Dark"}</span><b className="mo-appearance-check" aria-hidden="true">{appearance === mode && <Icon name="check" size={12} />}</b></label>)}</div><div className="mo-ios-settings-group"><div className="mo-setting-switch"><span>Automatic</span><Switch aria-label="Automatic appearance" checked={appearance === "system"} onCheckedChange={value => setAppearance(value ? "system" : "light")} /></div><Field label={`Brightness · ${brightness}%`}><Slider aria-label="Display brightness" min={30} max={100} value={brightness} onValueChange={setBrightness} /></Field><Field label={`Text size · ${textSize}%`}><Slider aria-label="Text size" min={100} max={125} step={5} value={textSize} onValueChange={setTextSize} /></Field></div></>;
    else if (screen === "wifi") content = <><div className="mo-ios-settings-group"><div className="mo-setting-switch"><span>Wi-Fi</span><Switch aria-label="Wi-Fi" checked={wifi} onCheckedChange={setWifi} /></div></div><p className="mo-ios-group-label">Networks</p><div className="mo-ios-settings-group mo-ios-settings-rows">{["Studio network", "Guest network", "Home network"].map(name => <Button variant="ghost" className="mo-ios-setting-row" key={name} disabled={!wifi} aria-pressed={wifi && network === name} onClick={() => { setNetwork(name); announce(`${name} selected locally`); }}><Icon name={network === name && wifi ? "check" : "wifi"} /><strong>{name}</strong><Icon name="lock" /></Button>)}</div><p className="mo-caption">Sample networks. This setting does not change your device connection.</p></>;
    else if (screen === "bluetooth") content = <><div className="mo-ios-settings-group"><div className="mo-setting-switch"><span>Bluetooth</span><Switch aria-label="Bluetooth" checked={bluetooth} onCheckedChange={setBluetooth} /></div></div><p className="mo-ios-group-label">My devices</p><div className="mo-ios-settings-group"><div className="mo-data-row"><span>Studio headphones</span><span>{bluetooth ? "Available" : "Off"}</span></div></div><p className="mo-caption">Sample device. No Bluetooth connection is made.</p></>;
    else if (screen === "battery") content = <><div className="mo-ios-battery-summary"><span>Battery level</span><strong>84%</strong><Progress value={84} aria-label="Sample battery charge" /><span>Sample reading · Updated 9:41</span></div><div className="mo-ios-settings-group"><div className="mo-setting-switch"><span>Low power mode</span><Switch aria-label="Low power mode" checked={lowPower} onCheckedChange={setLowPower} /></div></div><p className="mo-caption">Low power mode changes this sample phone only.</p></>;
    else if (screen === "focus") content = <><div className="mo-ios-settings-group"><div className="mo-setting-switch"><span>Do Not Disturb</span><Switch aria-label="Do Not Disturb" checked={focusMode} onCheckedChange={setFocusMode} /></div></div><p className="mo-caption">Focus is shown in this phone’s Notification Center. Your real notifications are unaffected.</p></>;
    else if (screen === "profile") content = <><div className="mo-ios-account"><span className="mo-initials">AV</span><h3>Avery Vos</h3><p>avery@example.invalid</p></div><div className="mo-ios-settings-group"><div className="mo-data-row"><span>Device</span><strong>{device.name}</strong></div><div className="mo-data-row"><span>Storage</span><span>This browser tab</span></div></div><p className="mo-caption">Fictional profile. No Apple Account or cloud service is connected.</p></>;
    else content = <><SearchField platform={platform} label="Search settings" placeholder="Search" value={search} onValueChange={setSearch} />{!search && <Button variant="ghost" className="mo-ios-profile-row" onClick={() => setScreen("profile")}><span className="mo-initials">AV</span><span><strong>Avery Vos</strong><span>Local profile and sample device</span></span><Icon name="chevron-right" /></Button>}<div className="mo-ios-settings-group mo-ios-settings-rows">{!search && <div className="mo-ios-setting-row"><span className="mo-ios-setting-glyph"><SystemIcon name="send" /></span><strong>Airplane Mode</strong><Switch aria-label="Airplane Mode" checked={airplaneMode} onCheckedChange={setAirplaneMode} /></div>}{"wi-fi".includes(search.toLowerCase()) && settingRow("Wi-Fi", wifi ? network : "Off", "wifi", "wifi")}{"bluetooth".includes(search.toLowerCase()) && settingRow("Bluetooth", bluetooth ? "On" : "Off", "bluetooth", "link")}</div><div className="mo-ios-settings-group mo-ios-settings-rows">{"display brightness text appearance".includes(search.toLowerCase()) && settingRow("Display & Brightness", "", "display", "sun")}{"focus do not disturb".includes(search.toLowerCase()) && settingRow("Focus", focusMode ? "On" : "", "focus", "moon")}{"battery low power".includes(search.toLowerCase()) && settingRow("Battery", "84%", "battery", "power")}</div><Button variant="ghost" className="mo-ios-restore" onClick={restoreSettings}>Restore default settings</Button><p className="mo-caption">All settings stay in this tab.</p></>;
  } else {
    content = <AndroidSettings deviceName={device.name} androidVersion={device.system.replace("Android ", "")} screen={screen} navigate={setScreen} search={search} onSearch={setSearch} appearance={appearance} setAppearance={setAppearance} textSize={textSize} setTextSize={setTextSize} brightness={brightness} setBrightness={setBrightness} wifi={wifi} setWifi={setWifi} bluetooth={bluetooth} setBluetooth={setBluetooth} airplane={airplaneMode} setAirplane={setAirplaneMode} lowPower={lowPower} setLowPower={setLowPower} focus={focusMode} setFocus={setFocusMode} />;
  }
  const iosClockActive = platform === "ios" && app === "clock" && !overlay;
  const iosCalendarActive = platform === "ios" && app === "calendar" && !overlay;
  const clockNavigation = platform === "android" && app === "clock" && !overlay ? <nav className="mo-clock-tabs" aria-label="Clock mode">{[{ value: "alarm", label: "Alarm", icon: "bell" }, { value: "stopwatch", label: "Stopwatch", icon: "timer" }, { value: "timer", label: "Timer", icon: "clock" }].map(row => <Button key={row.value} variant="ghost" aria-pressed={clockTab === row.value} onClick={() => setClockTab(row.value)}><Icon name={row.icon === "bell" ? "bell" : row.icon === "timer" ? "timer" : "clock"} size={16} /><span>{row.label}</span></Button>)}</nav> : null;
  const phoneTabRoot = platform === "ios" && app === "phone" && ["", "recent-calls", "dial"].includes(screen);
  const rootApp = (!screen || phoneTabRoot) && !call && !overlay;
  const iosEditorAction = platform === "ios" && !!screen && ["new", "compose", "edit-contact"].includes(screen) || platform === "ios" && !!screen && ["notes", "files"].includes(app);
  const iosHeaderAction = platform === "ios" && (rootApp && ["contacts", "messages"].includes(app) || iosEditorAction || ["contacts", "phone"].includes(app) && screen === "contact");
  const iosPhoneNavigation = platform === "ios" && app === "phone" && !overlay && !call && !["new", "edit-contact"].includes(screen) ? <nav className="mo-clock-tabs mo-ios-phone-tabs" aria-label="Phone sections">{([{ value: "recent-calls", label: "Recents", icon: "clock" }, { value: "", label: "Contacts", icon: "users" }, { value: "dial", label: "Keypad", icon: "grid" }] as const).map(row => <Button key={row.value} variant="ghost" aria-pressed={screen === row.value} onClick={() => setScreen(row.value)}><Icon name={row.icon} size={24} style={{ width: 24, height: 24 }} /><span>{row.label}</span></Button>)}</nav> : null;
  const iosTitle = app === "files" && !screen ? "On My iPhone" : screen === "edit-contact" && ["contacts", "phone"].includes(app) ? "Edit contact" : iosEditorAction && screen === "new" ? (({ contacts: "New contact", phone: "New contact", notes: "New note", files: "New file", calendar: "New event" } as Partial<Record<AppId, string>>)[app] ?? currentApp?.name) : app === "settings" ? ({ display: "Display & Brightness", wifi: "Wi-Fi", bluetooth: "Bluetooth", battery: "Battery", focus: "Focus", profile: "Local profile" }[screen] ?? "Settings") : app === "mail" ? !screen ? "Mailboxes" : screen === "inbox" ? "Inbox" : screen === "sent" ? "Sent" : currentApp?.name : app === "messages" && screen === "recipients" ? "New message" : app === "messages" && screen === "thread" ? selectedContact.name : app === "browser" ? "Safari" : app === "phone" && !call ? screen === "dial" ? "Keypad" : screen === "recent-calls" ? "Recents" : "Contacts" : currentApp?.name;
  const iosSplit = platform === "ios" && device.id === "iphone-duo" && expanded && !rotated && !live && !overlay && !call && !!screen && !["new", "compose", "recipients"].includes(screen) && ["notes", "files", "mail", "settings"].includes(app);
  const iosMasterList = iosSplit ? <nav className="mo-ios-master-list" aria-label={`${currentApp?.name} sidebar`}>
    <Button variant="ghost" className="mo-ios-master-heading" onClick={() => setScreen("")}><Icon name="chevron-left" size={24} style={{ width: 24, height: 24 }} />{app === "mail" ? "Mailboxes" : currentApp?.name}</Button>
    {app === "notes" && notes.map(note => <Button variant="ghost" key={note.id} aria-pressed={screen === note.id} onClick={() => openNote(note)}><strong>{note.title}</strong><span>{note.body.split("\n")[0] || "Empty note"}</span></Button>)}
    {app === "files" && files.map(file => <Button variant="ghost" key={file.id} aria-pressed={screen === file.id} onClick={() => openFile(file)}><strong>{file.name}</strong><span>{new Blob([file.body]).size} bytes</span></Button>)}
    {app === "mail" && <><Button variant="ghost" aria-pressed={screen === "inbox"} onClick={() => setScreen("inbox")}><strong>Inbox</strong><span>{mails.filter(mail => !mail.sent).length} messages</span></Button><Button variant="ghost" aria-pressed={screen === "sent"} onClick={() => setScreen("sent")}><strong>Sent</strong><span>{mails.filter(mail => mail.sent).length} local copies</span></Button>{mails.filter(mail => mail.sent === Boolean(selectedMail?.sent || screen === "sent")).map(mail => <Button variant="ghost" key={mail.id} aria-pressed={screen === mail.id} onClick={() => setScreen(mail.id)}><strong>{mail.subject}</strong><span>{mail.from}</span></Button>)}</>}
    {app === "settings" && [{ id: "profile", title: "Avery Vos" }, { id: "wifi", title: "Wi-Fi" }, { id: "bluetooth", title: "Bluetooth" }, { id: "display", title: "Display & Brightness" }, { id: "focus", title: "Focus" }, { id: "battery", title: "Battery" }].map(item => <Button variant="ghost" key={item.id} aria-pressed={screen === item.id} onClick={() => setScreen(item.id)}><strong>{item.title}</strong></Button>)}
  </nav> : null;
  const floatingAction = platform === "android" && rootApp && ["contacts", "mail", "calendar", "notes", "files", "messages"].includes(app);
  function startGesture(event: React.PointerEvent<HTMLElement>) { gesture.current = { x: event.clientX, y: event.clientY, time: Date.now() }; gestureHandled.current = false; }
  function endHomeGesture(event: React.PointerEvent<HTMLElement>) {
    const from = gesture.current; gesture.current = null; if (!from) return;
    if (from.y - event.clientY > 16) { gestureHandled.current = true; if (Date.now() - from.time > 350) openOverlay("recents"); else launch("home"); }
  }
  return <section className="mo-device" data-platform={platform} data-device={device.id} data-posture={expanded ? "expanded" : "compact"} data-orientation={!live && rotated ? "landscape" : "portrait"} aria-label={platform === "ios" ? "iOS phone" : "Android phone"}><div className="mo-device-label"><span>{device.name}</span><span>{platform === "ios" ? "iOS 27" : "Material 3 Expressive"}</span></div><DeviceFrame device={device} expanded={expanded} rotated={rotated} live={live} prepareFold={prepareFold} inspectionAngle={inspectionAngle}><div className="mo-phone" data-split={iosSplit || undefined} data-duo-layout={device.id === "iphone-duo" && !live ? expanded && rotated ? "horizontal" : "vertical" : undefined} data-duo-orientation={device.id === "iphone-duo" && !live ? expanded ? rotated ? "portrait" : "landscape" : rotated ? "landscape" : "portrait" : undefined} data-duo-display={device.id === "iphone-duo" && !live ? expanded ? "inner" : "outer" : undefined} data-sheet={platform === "ios" && ["new", "compose", "recipients", "edit-contact"].includes(screen) || undefined} data-app={app} data-screen={screen} data-root-app={rootApp} data-overlay={overlay || undefined} data-theme={appearance === "system" ? undefined : appearance} style={{ "--mo-text-scale": textSize / 100, "--mo-brightness": 0.7 + brightness / 100 * 0.3 } as React.CSSProperties} onKeyDown={event => { if (event.key === "Escape" && overlay) { event.preventDefault(); event.stopPropagation(); closeOverlay(); } }}>
    <span className="mo-camera-cutout" aria-hidden="true" /><div className="mo-status-bar"><Button variant="ghost" aria-label="09:41, open notifications" onClick={() => openOverlay("notifications")}>{platform === "ios" ? "9:41" : "09:41"}{platform === "android" && notifications.length > 0 && <span className="mo-notification-dot" aria-hidden="true" />}</Button><Button variant="ghost" aria-label={platform === "ios" ? "Open Control Center" : "Open Quick Settings"} onClick={() => openOverlay("quick")}><StatusSignals platform={platform} wifi={wifi} cellular={cellular && !airplaneMode} duo={device.id === "iphone-duo" && !live} /></Button></div>
    <div className="mo-screen" data-fab={floatingAction}>
      {app !== "home" && !overlay && !iosCalendarActive && !iosClockActive && <header className="mo-app-header">{!rootApp && <Button variant="ghost" aria-label="Back" onClick={goBack}><Icon name={platform === "ios" ? "chevron-left" : "arrow-left"} size={platform === "ios" ? 24 : 16} style={platform === "ios" ? { width: 24, height: 24 } : undefined} />{platform === "android" && <span>Back</span>}</Button>}<h2 ref={appTitle} tabIndex={-1} className={platform === "ios" && (app === "notes" && !!screen || ["contacts", "phone"].includes(app) && screen === "contact") ? "mo-sr-only" : undefined}>{platform === "ios" ? iosTitle : app === "messages" && screen === "recipients" ? "New message" : app === "messages" && screen === "thread" ? selectedContact.name : app === "settings" ? androidSettingsTitles[screen] ?? "Settings" : currentApp?.name}</h2>{iosHeaderAction && <div key={`${app}:${screen}`} className={`mo-ios-navigation-actions${iosEditorAction ? " mo-ios-editor-actions" : ""}`}>{actions}</div>}</header>}
      {iosMasterList}
      {platform === "ios" && <div className="mo-calendar-host" hidden={!iosCalendarActive}>
        {iosCalendarActive && <h2 className="mo-sr-only" ref={appTitle} tabIndex={-1}>Calendar</h2>}
        <IOSCalendar active={iosCalendarActive} date={date} events={events} onDateChange={setDate} onEventsChange={setEvents} onAnnounce={announce} />
      </div>}
      {platform === "ios" && <IOSClock active={iosClockActive} onAnnounce={announce} onTimerComplete={label => { const notification = { id: unique("timer"), title: "Timer complete", text: label ? `${label} has finished.` : "Your local timer has finished." }; setNotifications(current => [notification, ...current]); }} />}
      {!iosCalendarActive && !iosClockActive && <div className={`mo-scroll${app === "home" && !overlay ? " mo-home" : ""}`} tabIndex={app === "camera" && !overlay ? 0 : undefined} key={`${app}-${screen}-${overlay}`} onPointerDown={event => { gestureHandled.current = false; if (app === "home" && !overlay && !(event.target as HTMLElement).closest(platform === "ios" ? "input,textarea,select" : "button,input")) startGesture(event); }} onClickCapture={event => { if (gestureHandled.current) { gestureHandled.current = false; if (event.detail > 0) { event.preventDefault(); event.stopPropagation(); } } }} onPointerCancel={() => { gesture.current = null; gestureHandled.current = false; }} onPointerUp={event => { const from = gesture.current; if (!from || app !== "home" || overlay) return; gesture.current = null; const dx = from.x - event.clientX, dy = from.y - event.clientY; if (platform === "ios" && dx > 60 && dx > Math.abs(dy) || platform === "android" && dy > 60) { gestureHandled.current = true; event.preventDefault(); openOverlay("library"); } }}>
        {(app === "home" || overlay) && <h2 className="mo-sr-only" ref={appTitle} tabIndex={-1}>{overlay === "quick" ? platform === "ios" ? "Control Center" : "Quick Settings" : overlay === "notifications" ? platform === "ios" ? "Notification Center" : "Notifications" : overlay === "recents" ? platform === "ios" ? "App Switcher" : "Recent apps" : overlay === "library" ? platform === "ios" ? "App Library" : "All apps" : "Home screen"}</h2>}{content}
      </div>}
      {platform === "ios" && app === "home" && !overlay && iosHomeSearch(true)}
      {actions && !iosHeaderAction && <div className="mo-app-actions">{actions}</div>}{clockNavigation}{iosPhoneNavigation}
      {app === "home" && !overlay && <div className="mo-dock" role="group" aria-label="Favorite apps">{dockIds.map(appId => { const row = apps.find(item => item.id === appId)!; return <Button variant="ghost" key={row.id} aria-label={`Open ${displayName(row)} from dock`} onClick={event => launch(row.id, undefined, event.currentTarget)}><span data-app-icon={row.id}>{platform === "ios" ? <IOSAppGlyph id={row.id} icon={row.icon} /> : <AndroidAppGlyph id={row.id} icon={row.icon} />}</span><span>{displayName(row)}</span></Button>; })}</div>}
      {platform === "android" && app === "home" && !overlay && <Button variant="ghost" className="mo-android-search" aria-label="All apps" onClick={() => openOverlay("library")}><Icon name="search" /><span>Search your apps</span><Icon name="grid" /></Button>}
    </div>
    {platform === "android" ? <nav className="mo-system-nav mo-android-gesture-nav" aria-label="Android system navigation"><Button variant="ghost" className="mo-home-indicator-button" aria-label="Home" aria-keyshortcuts="ArrowUp" aria-description="Swipe up for Home, or swipe up and hold for Recent apps." onPointerDown={event => { startGesture(event); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={endHomeGesture} onKeyDown={event => { if (event.key === "ArrowUp") { event.preventDefault(); openOverlay("recents"); } }} onClick={() => { if (gestureHandled.current) { gestureHandled.current = false; return; } if (overlay) closeOverlay(); else launch("home"); }}><span /></Button></nav> : <nav className="mo-system-nav mo-ios-gesture-nav" aria-label="iOS Home gesture"><Button variant="ghost" className="mo-home-indicator-button" aria-label="Home" aria-keyshortcuts="ArrowUp" aria-description="Swipe up to go home. Swipe up and hold, or press ArrowUp, to open App Switcher." onPointerDown={event => { startGesture(event); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={endHomeGesture} onKeyDown={event => { if (event.key === "ArrowUp") { event.preventDefault(); openOverlay("recents"); } }} onClick={() => { if (gestureHandled.current) { gestureHandled.current = false; return; } if (overlay === "quick" || overlay === "notifications") closeOverlay(); else launch("home"); }}><span /></Button></nav>}
    <div className="mo-notice mo-sr-only" role="status">{notice}</div>
  </div></DeviceFrame>{platform === "android" && <div className="mo-device-tools"><Button variant="ghost" aria-label="System back" onClick={goBack}><Icon name="arrow-left" />Back</Button><Button variant="ghost" onClick={() => openOverlay("recents")}><Icon name="layers" />Recent apps</Button></div>}</section>;
}
