export type Format = "widescreen" | "desktop" | "phone";
export type Wallpaper = { id: string; name: string; background: string; ink: string; signal: string; quiet: string; grid: number; horizon: number; blockX: number; blockY: number; blockW: number; blockH: number; discX: number; discY: number; discR: number; stripeX: number; stripeGap: number; diagonal: number };
export const WALLPAPER_GENERATOR_VERSION = 1 as const;
export const WALLPAPER_RENDERER_VERSION = 1 as const;
export const formats: Record<Format, { label: string; width: number; height: number }> = { widescreen: { label: "Widescreen", width: 6144, height: 3456 }, desktop: { label: "Desktop", width: 6144, height: 3840 }, phone: { label: "Phone", width: 3456, height: 6144 } };
const palettes = [["#ede8dc", "#121212", "#2142c7", "#b9b3a5"], ["#dcd9cf", "#171714", "#d44825", "#aaa69c"], ["#111310", "#eeeae0", "#d6d16a", "#51544c"], ["#e7e5dd", "#14251d", "#2a7364", "#aaa99f"]] as const;
export function hash(value: string) { let result = 2166136261; for (let index = 0; index < value.length; index += 1) { result ^= value.charCodeAt(index); result = Math.imul(result, 16777619); } return result >>> 0; }
function random(seed: number) { let value = seed; return () => { value += 0x6d2b79f5; let number = value; number = Math.imul(number ^ (number >>> 15), number | 1); number ^= number + Math.imul(number ^ (number >>> 7), number | 61); return ((number ^ (number >>> 14)) >>> 0) / 4294967296; }; }
export function makeWallpapers(prompt: string, variation: number, generation: number) { return Array.from({ length: 3 }, (_, index): Wallpaper => { const seed = hash(`${prompt}:${variation}:${generation}:${index}`); const next = random(seed); const palette = palettes[Math.floor(next() * palettes.length)]!; return { id: `${seed}-${generation}-${index}`, name: ["Primary field", "Open structure", "Signal study"][index]!, background: palette[0], ink: palette[1], signal: palette[2], quiet: palette[3], grid: 4 + Math.floor(next() * 6), horizon: 0.34 + next() * 0.34, blockX: 0.08 + next() * 0.35, blockY: 0.08 + next() * 0.34, blockW: 0.2 + next() * 0.28, blockH: 0.18 + next() * 0.3, discX: 0.56 + next() * 0.3, discY: 0.16 + next() * 0.56, discR: 0.055 + next() * 0.09, stripeX: 0.12 + next() * 0.7, stripeGap: 0.012 + next() * 0.012, diagonal: 0.18 + next() * 0.46 }; }); }
const colors = new Set(palettes.flat());
const payloadKeys = ["prompt", "variation", "generation", "selected", "format", "results", "generatorVersion", "rendererVersion"] as const;
const resultKeys = ["id", "name", "background", "ink", "signal", "quiet", "grid", "horizon", "blockX", "blockY", "blockW", "blockH", "discX", "discY", "discR", "stripeX", "stripeGap", "diagonal"] as const;
const exact = (value: unknown, allowed: readonly string[], path: string): Record<string, unknown> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`Invalid wallpaper project: ${path} must be an object`);
  const record = value as Record<string, unknown>; const extra = Object.keys(record).find(key => !allowed.includes(key));
  if (extra) throw new Error(`Invalid wallpaper project: ${path}.${extra} is unsupported`);
  for (const key of allowed) if (!Object.hasOwn(record, key)) throw new Error(`Invalid wallpaper project: ${path}.${key} is required`);
  return record;
};
const bounded = (value: unknown, path: string) => { if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > 1) throw new Error(`Invalid wallpaper project: ${path} is out of range`); return value; };
const text = (value: unknown, path: string, max: number) => { if (typeof value !== "string" || !value.trim() || value.length > max) throw new Error(`Invalid wallpaper project: ${path} is invalid`); return value; };
export type WallpaperProject = { prompt: string; variation: number; generation: number; selected: number; format: Format; results: Wallpaper[]; generatorVersion: 1; rendererVersion: 1 };
export function validateWallpaperProject(value: unknown): WallpaperProject {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid wallpaper project: payload must be an object");
  const item = exact(value, payloadKeys, "payload");
  if (item.generatorVersion !== 1 || item.rendererVersion !== 1) throw new Error("Invalid wallpaper project: unsupported generator or renderer version");
  if (typeof item.prompt !== "string" || item.prompt.length > 500 || !Number.isInteger(item.variation) || (item.variation as number) < 0 || (item.variation as number) > 100 || !Number.isSafeInteger(item.generation) || (item.generation as number) < 0 || (item.generation as number) > 1_000_000 || !Number.isInteger(item.selected) || (item.selected as number) < 0 || (item.selected as number) > 2 || !(item.format === "widescreen" || item.format === "desktop" || item.format === "phone") || !Array.isArray(item.results) || item.results.length !== 3) throw new Error("Invalid wallpaper project: unsupported payload values");
  const results = item.results.map((raw, index) => { const result = exact(raw, resultKeys, `result ${index}`); const numeric = ["horizon", "blockX", "blockY", "blockW", "blockH", "discX", "discY", "discR", "stripeX", "stripeGap", "diagonal"] as const; text(result.id, `result ${index}.id`, 120); text(result.name, `result ${index}.name`, 96); if (!Number.isInteger(result.grid) || (result.grid as number) < 4 || (result.grid as number) > 9 || !["background", "ink", "signal", "quiet"].every(key => colors.has(result[key] as never))) throw new Error(`Invalid wallpaper project: result ${index} has unsupported values`); numeric.forEach(key => { bounded(result[key], `result ${index}.${key}`); }); return { id: result.id as string, name: result.name as string, background: result.background as string, ink: result.ink as string, signal: result.signal as string, quiet: result.quiet as string, grid: result.grid as number, ...Object.fromEntries(numeric.map(key => [key, result[key]])) } as Wallpaper; });
  if (new Set(results.map(result => result.id)).size !== results.length) throw new Error("Invalid wallpaper project: result IDs must be unique");
  return { prompt: item.prompt as string, variation: item.variation as number, generation: item.generation as number, selected: item.selected as number, format: item.format as Format, results, generatorVersion: 1, rendererVersion: 1 };
}
export function migrateLegacyWallpaperProject(value: unknown): WallpaperProject {
  const item = exact(value, ["prompt", "variation", "generation", "selected", "format", "results"], "legacy payload");
  return validateWallpaperProject({ ...item, generatorVersion: 1, rendererVersion: 1 });
}
export function parseWallpaperProject(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid wallpaper project: project must be an object"); const item = value as Record<string, unknown>; if (item.schema === "vlak.project" && item.kind === "wallpaper") { if (item.envelopeVersion !== 1 || item.documentVersion !== 1) throw new Error("Invalid wallpaper project: unsupported envelope version"); return parseWallpaperProject(item.payload); } if (Object.hasOwn(item, "generatorVersion") || Object.hasOwn(item, "rendererVersion")) return validateWallpaperProject(value); return migrateLegacyWallpaperProject(value); }
